Repository golemfactory/golem, pull requests merged in 2018-04, with the labels that each got.

#2545 Update version and product code for 0.15.0
  Installer/Installer_Win/Golem.aip
Labels: needs review, to be merged

#2537 Handle gracefully errors in add_task
  golem/client.py
Labels: bug, needs review

#2546 Prevent self payments for tasks
  golem/network/concent/helpers.py
  tests/factories/messages.py
  tests/golem/network/concent/test_helpers.py
  tests/golem/task/test_tasksession.py
Labels: to be merged

#2548 Use geth.golem.network domain
  golem/ethereum/node.py
Labels: to be merged

#2550 Payment trust
  golem/task/taskserver.py
  golem/transactions/incomeskeeper.py
Labels: needs review

#2552 Enable talkback on testnet by default
  golem/appconfig.py
  golemapp.py
Labels: to be merged

#2536 Updated icons and split main vs test desktop shortcuts
  Installer/Installer_Win/Golem.aip
  Installer/favicon-mainnet.ico
  Installer/favicon-testnet.ico
  Installer/favicon.ico
Labels: needs review, to be merged

#2551 Validate computation time
  golem/task/taskmanager.py
  tests/golem/task/test_taskmanager.py
  tests/golem/task/test_taskserver.py
Labels: bug, needs review, to be merged

#2553 Payments: quickfix for lack of proper timezone info
  golem/core/common.py
  golem/transactions/paymentskeeper.py
  golem/transactions/transactionsystem.py
  tests/golem/test_client.py
Labels: to be merged

#2557 Prevent batch payments to zero address
  golem/network/concent/helpers.py
  tests/golem/network/concent/test_helpers.py
Labels: to be merged

#2559 Updated terms of use (+rpc method name fix)
  golem/TERMS.html
  golem/rpc/mapping/rpcmethodnames.py
  golem/terms.py
Labels: important, to be merged, user interface

#2565 Mainnet SCI
  requirements.txt
Labels: needs review, to be merged

#2566 Fix closure_time in batchTransfer
  golem/ethereum/paymentprocessor.py
  tests/golem/transactions/ethereum/test_paymentprocessor.py
Labels: to be merged

#2563 Fixed `remaining` in `golemcli tasks show`
  golem/interface/client/tasks.py
  golem/task/taskmanager.py
  golem/task/taskstate.py
  tests/golem/interface/test_client_commands.py
Labels: needs review, user interface

#2570 change default price
  golem/appconfig.py
Labels: to be merged

#2572 Handle errors in ping_request + tests
  golem/monitor/monitor.py
  tests/golem/monitor/test_monitor.py
Labels: bug, monitor, needs review

#2567 Fix __prepare_resources (Windows)
  golem/task/localcomputer.py
  tests/golem/task/test_localcomputer.py
Labels: to be merged

#2577 Converted terms of use to pure ASCII
  golem/TERMS.html
Labels: bug, to be merged, windows

#2578 Lock base eth payment cost once.
  golem/transactions/ethereum/ethereumtransactionsystem.py
  golem/transactions/ethereum/fundslocker.py
  tests/golem/test_client.py
  tests/golem/transactions/ethereum/test_fundslocker.py
Labels: to be merged

#2575 Use real GNTB
  requirements.txt
Labels: to be merged

#2580 Validate address on withdrawal
  golem/transactions/ethereum/ethereumtransactionsystem.py
  tests/golem/transactions/ethereum/test_ethereumtransactionsystem.py
Labels: to be merged

#2584 Command line: Issue RPC calls in the main thread
  golem/interface/websockets.py
  tests/golem/interface/test_websocket_cli.py
Labels: needs review, to be merged

#2582 Add withdraw method to cli
  golem/interface/client/account.py
Labels: to be merged

#2587 Add gate balance to the GNT balance
  golem/ethereum/paymentprocessor.py
  tests/golem/transactions/ethereum/test_paymentprocessor.py
Labels: to be merged

#2591 Decrease severity of log for receiving info about finished tasks
  golem/task/taskkeeper.py
Labels: needs review, to be merged

#2589 Node.quit RPC call
  golem/node.py
  golem/rpc/mapping/rpcmethodnames.py
  tests/golem/test_opt_node.py
Labels: needs review, to be merged

#2571 Improved tests for --peer flag
  tests/golem/test_opt_node.py
Labels: ci & tests, needs review

#2543 Check that subtask_id was generated from key_id
  golem/core/idgenerator.py
  golem/task/taskkeeper.py
  tests/golem/task/test_taskkeeper.py
  tests/golem/task/test_taskserver.py
Labels: needs review

#2539 Check that task_id was generated from requestor key_id in task_keeper
  apps/core/task/coretask.py
  golem/core/idgenerator.py
  golem/task/taskkeeper.py
  tests/golem/task/dummy/runner.py
  tests/golem/task/dummy/task.py
  tests/golem/task/test_taskkeeper.py
  tests/golem/task/test_taskserver.py
Labels: needs review

#2581 2518 concent/forced download integration unit tests
  golem/core/variables.py
  golem/network/concent/client.py
  golem/network/concent/filetransfers.py
  requirements-test.txt
  requirements.txt
  scripts/__init__.py
  scripts/concent_integration_tests/__init__.py
  scripts/concent_integration_tests/base.py
  scripts/concent_integration_tests/basic/__init__.py
  scripts/concent_integration_tests/basic/test_basic.py
  scripts/concent_integration_tests/force_download/__init__.py
  scripts/concent_integration_tests/force_download/test_filetransfers.py
  scripts/concent_integration_tests/force_download/test_messages.py
  scripts/concent_integration_tests/test_base.py
  scripts/test-concent.py
  tests/factories/messages.py
  tests/golem/network/concent/test_concent_client.py
  tests/golem/network/concent/test_filetransfers.py
Labels: concent

#2602 Merge b0.15.0 to develop
  Installer/Golem_284x284.png
  Installer/Golem_600x600.png
  Installer/Installer_Win/Golem.aip
  golem/TERMS.html
  golem/appconfig.py
  golem/ethereum/paymentprocessor.py
  golem/interface/client/account.py
  golem/interface/websockets.py
  golem/monitor/monitor.py
  golem/network/concent/helpers.py
  golem/node.py
  golem/rpc/mapping/rpcmethodnames.py
  golem/task/localcomputer.py
  golem/task/taskkeeper.py
  golem/terms.py
  golem/transactions/ethereum/ethereumtransactionsystem.py
  golem/transactions/ethereum/fundslocker.py
  requirements.txt
  tests/golem/interface/test_websocket_cli.py
  tests/golem/monitor/test_monitor.py
  tests/golem/network/concent/test_helpers.py
  tests/golem/task/test_localcomputer.py
  tests/golem/test_client.py
  tests/golem/test_opt_node.py
  tests/golem/transactions/ethereum/test_ethereumtransactionsystem.py
  tests/golem/transactions/ethereum/test_fundslocker.py
  tests/golem/transactions/ethereum/test_paymentprocessor.py
Labels: needs review

#2590 More info in withdraw failure ValueError
  golem/transactions/ethereum/ethereumtransactionsystem.py
  tests/golem/transactions/ethereum/test_ethereumtransactionsystem.py
Labels: needs review

#2600 Fix restoring task resources
  golem/client.py
  golem/resource/base/resourceserver.py
  golem/task/server/resources.py
  golem/task/taskstate.py
  tests/golem/task/test_taskmanager.py
  tests/golem/task/test_taskserver.py
  tests/golem/test_client.py
Labels: bug, needs review

#2638 DummyTask fix no 34
  tests/golem/task/dummy/runner.py
  tests/golem/task/dummy/task.py
Labels: needs review

#2643 Pre 0.15.1 compatibility for restore_resources
  golem/task/server/resources.py
Labels: needs review

#2620 Sync PaymentProcessor on startup
  golem/client.py
  golem/ethereum/paymentprocessor.py
  golem/transactions/ethereum/ethereumtransactionsystem.py
  requirements.txt
  tests/golem/test_client.py
Labels: needs review

#2544 HyperG share timeout
  golem/client.py
  golem/network/hyperdrive/client.py
  golem/resource/base/resourceserver.py
  golem/resource/client.py
  golem/resource/hyperdrive/resourcesmanager.py
  golem/resource/resourcehandshake.py
  golem/task/server/resources.py
  tests/golem/task/test_taskserver.py
  tests/golem/test_client.py
Labels: needs review

#2650 Use a shallow copy of subtasks_given while updating the preview
  apps/rendering/task/renderingtask.py
Labels: needs review

#2663 Remove finished tasks from the network
  golem/task/taskserver.py
  tests/golem/task/test_taskserver.py
Labels: needs review

#2669 2517 concent/force report integration tests
  golem/network/concent/client.py
  golem/network/concent/filetransfers.py
  requirements.txt
  requirements_to-freeze.txt
  scripts/concent_integration_tests/base.py
  scripts/concent_integration_tests/basic/test_basic.py
  scripts/concent_integration_tests/force_download/base.py
  scripts/concent_integration_tests/force_download/test_filetransfers.py
  scripts/concent_integration_tests/force_download/test_messages.py
  scripts/concent_integration_tests/force_report/__init__.py
  scripts/concent_integration_tests/force_report/test_messages.py
  tests/golem/core/test_keysauth.py
  tests/golem/network/concent/test_concent_client.py
  tests/golem/network/concent/test_filetransfers.py
  tests/golem/network/p2p/test_peersession.py
  tests/golem/task/test_tasksession.py
Labels: concent

#2684 UC1 - Force Report / the last two integration tests
  scripts/concent_integration_tests/force_report/test_messages.py
Labels: concent

#2688 Return if the nonce was downloaded after a handshake timeout
  golem/resource/resourcehandshake.py
Labels: needs review, to be merged

#2691 Display proper task duration
  golem/task/taskmanager.py
Labels: bug, ux

#2692 Refactor task restarting
  golem/client.py
  golem/task/taskmanager.py
Labels: bug, needs review, to be merged

#2687 Concent/uc2 fixes
  golem/network/concent/filetransfers.py
  requirements.txt
  requirements_to-freeze.txt
  scripts/concent_integration_tests/force_download/test_filetransfers.py
  tests/golem/network/concent/test_filetransfers.py
Labels: concent

#2708 Mainnet seeds
  golem/network/p2p/p2pservice.py
Labels: to be merged

#2698 Handle key errors in CLI calls
  golem/client.py
  golem/interface/client/tasks.py
  tests/golem/interface/test_client_commands.py
Labels: enhancement, needs review, user interface

#2710 Merge b0.15.1 to develop
  Installer/Installer_Win/Golem.aip
  apps/blender/task/blendercropper.py
  apps/blender/task/verifier.py
  apps/core/task/coretask.py
  apps/images.ini
  apps/rendering/task/renderingtask.py
  golem/client.py
  golem/core/simpleexccmd.py
  golem/ethereum/paymentprocessor.py
  golem/interface/client/tasks.py
  golem/monitorconfig.py
  golem/network/hyperdrive/client.py
  golem/network/p2p/p2pservice.py
  golem/network/transport/tcpserver.py
  golem/resource/base/resourceserver.py
  golem/resource/client.py
  golem/resource/hyperdrive/resourcesmanager.py
  golem/resource/resourcehandshake.py
  golem/rpc/mapping/rpcmethodnames.py
  golem/task/server/resources.py
  golem/task/taskbase.py
  golem/task/taskmanager.py
  golem/task/taskserver.py
  golem/tools/customloggers.py
  golem/tools/talkback.py
  golem/transactions/ethereum/ethereumtransactionsystem.py
  golem/transactions/ethereum/fundslocker.py
  loggingconfig.py
  tests/apps/blender/task/test_blender_verification.py
  tests/apps/rendering/task/test_renderingtask.py
  tests/golem/ethereum/test_paymentprocessor_eth.py
  tests/golem/task/dummy/runner.py
  tests/golem/task/dummy/task.py
  tests/golem/task/test_taskserver.py
  tests/golem/test_client.py
  tests/golem/transactions/ethereum/test_paymentprocessor.py
Labels: needs review

#2720 Use locale in test_du
  tests/golem/core/test_fileshelper.py
Labels: bug, ci & tests

#2723 * adds support for `golem-messages 2.6.0`
  golem/network/concent/helpers.py
  golem/task/tasksession.py
  requirements.txt
  requirements_to-freeze.txt
  scripts/concent_integration_tests/force_report/test_messages.py
  tests/golem/network/concent/test_received_handler.py
  tests/golem/task/test_tasksession.py
Labels: concent

#2724 Refactoring & tests for restart_subtasks
  golem/task/taskmanager.py
  tests/golem/task/test_taskmanager.py
Labels: ci & tests

#2717 RPC method to add nodes to block list
  golem/client.py
  golem/interface/client/network.py
  golem/rpc/mapping/rpcmethodnames.py
  golem/task/acl.py
  tests/golem/interface/test_client_commands.py
  tests/golem/task/test_acl.py
  tests/golem/test_client.py
Labels: enhancement, needs review, user interface

#2385 Cleanup socket addresses in TaskHeader, WTR/F
  apps/core/task/coretask.py
  golem/network/p2p/p2pservice.py
  golem/task/result/resultpackage.py
  golem/task/taskbase.py
  golem/task/taskkeeper.py
  golem/task/taskmanager.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  tests/factories/taskserver.py
  tests/golem/docker/test_docker_blender_task.py
  tests/golem/network/p2p/test_peersession.py
  tests/golem/task/dummy/task.py
  tests/golem/task/test_taskarchiver.py
  tests/golem/task/test_taskbase.py
  tests/golem/task/test_taskkeeper.py
  tests/golem/task/test_taskmanager.py
  tests/golem/task/test_taskserver.py
  tests/golem/task/test_tasksession.py
Labels: needs review
