Repository golemfactory/golem, pull requests merged in 2018-02, with the labels that each got.

#2080 Iterate over a copy of subtasks_given.values() in _update_frame_task_preview
  apps/rendering/task/framerenderingtask.py
Labels: needs review

#2098 Catch EOFError 'Ran out of input'
  golem/task/taskarchiver.py
Labels: bug, important

#2077 Database migration: updated scripts and migration fallback
  golem/database/database.py
  golem/database/migration/migrate.py
  golem/database/migration/router.py
  golem/database/schemas/010_schema.py
  golem/database/schemas/011_schema.py
  golem/database/schemas/012_schema.py
  golem/database/schemas/013_schema.py
  tests/golem/database/test_migration.py
Labels: needs review

#2023 Database migration
  codecov.yml
  golem/client.py
  golem/database/__init__.py
  golem/database/database.py
  golem/database/migration/__init__.py
  golem/database/migration/create.py
  golem/database/migration/migrate.py
  golem/database/migration/router.py
  golem/database/schemas/010_schema.py
  golem/database/schemas/011_schema.py
  golem/database/schemas/012_schema.py
  golem/database/schemas/013_schema.py
  golem/database/schemas/__init__.py
  golem/model.py
  golem/testutils.py
  loggingconfig.py
  requirements.txt
  setup.py
  setup_util/setup_commons.py
  tests/golem/database/__init__.py
  tests/golem/database/test_database.py
  tests/golem/database/test_migration.py
  tests/golem/resource/test_resourcehandshake.py
  tests/golem/test_model.py
Labels: needs review

#2090 Kt split ansible ci roles
  scripts/ci/.gitignore
  scripts/ci/requirements.yml
  scripts/ci/roles/buildbot-worker-mac/tasks/main.yml
  scripts/ci/roles/buildbot-worker-windows/tasks/main.yml
  scripts/ci/roles/golem-dev-linux/tasks/main.yml
  scripts/ci/site-worker-linux.yml
  scripts/ci/site-worker-mac.yml
  scripts/ci/site-worker-windows.yml
Labels: needs review

#1871 Empty hostname fix
  golem/network/p2p/p2pservice.py
  golem/network/transport/tcpnetwork.py
  tests/golem/network/p2p/test_p2pservice.py
  tests/golem/network/transport/test_tcpnetwork.py
Labels: needs review

#2102 Use TransactionReceipt in GNTConverter
  golem/ethereum/gntconverter.py
  tests/golem/ethereum/test_gntconverter.py
Labels: needs review

#2040 Metrics verdict
  apps/blender/resources/cropgenerator.py
  apps/blender/resources/scripts/blendercrop.py.template
  apps/blender/task/blendercropper.py
  apps/blender/task/verifier.py
  appveyor.yml
  circle.yml
  scripts/pyinstaller/hooks/hook-golem.py
  tests/apps/blender/task/good_image.png
  tests/apps/blender/task/test_blender_verification.py
  tests/apps/blender/task/test_blendercropper.py
  tests/apps/blender/task/test_blenderverifier.py
  tests/apps/blender/task/very_bad_image.png
Labels: needs review

#2088 Unused services removed
  golem/client.py
  golem/rpc/mapping/rpceventnames.py
  tests/golem/test_client.py
Labels: needs review

#2030 Task name check from json file on CLI
  golem/interface/client/tasks.py
  tests/golem/interface/test_cli.py
  tests/golem/interface/test_client_commands.py
Labels: needs review

#2097 update requests dependency
  requirements.txt
Labels: needs review

#2082 Concent Ping
  golem/client.py
  golem/core/async.py
  golem/core/keysauth.py
  golem/network/concent/client.py
  golem/network/concent/constants.py
  golem/network/concent/handlers_library.py
  golem/network/concent/helpers.py
  golem/network/concent/received_handler.py
  golem/task/server/concent.py
  golem/task/server/resources.py
  golem/task/taskserver.py
  loggingconfig.py
  tests/factories/messages.py
  tests/factories/taskserver.py
  tests/golem/core/test_keysauth.py
  tests/golem/docker/test_docker_blender_task.py
  tests/golem/docker/test_docker_dummy_task.py
  tests/golem/docker/test_docker_luxrender_task.py
  tests/golem/network/concent/test_concent_client.py
  tests/golem/network/concent/test_conformance.py
  tests/golem/network/concent/test_handlers_library.py
  tests/golem/network/concent/test_received_handler.py
  tests/golem/resource/base/common.py
  tests/golem/resource/test_resourcehandshake.py
  tests/golem/task/test_taskserver.py
  tests/golem/test_client.py
Labels: needs review

#2109 Don't store public keys on disk
  golem/core/keysauth.py
  golem/core/variables.py
  tests/golem/core/test_keysauth.py
  tests/golem/network/p2p/test_p2pservice.py
Labels: in progress

#2103 Increase port ping request's timeout
  golem/monitor/monitor.py
Labels: needs review

#2106 Client.quit called many times
  golem/client.py
  golem/core/processmonitor.py
  golem/docker/job.py
  golem/ethereum/node.py
  golem/network/hyperdrive/daemon_manager.py
  golem/node.py
  tests/golem/docker/test_docker_job.py
Labels: needs review

#2004 Early RPC requests fix
  golem/client.py
  golem/task/taskmanager.py
Labels: needs review

#2116 Dont't ping concent if it's disabled
  golem/network/concent/client.py
  golem/network/concent/handlers_library.py
  golem/task/taskserver.py
  golem/tools/testwithappconfig.py
  tests/golem/network/concent/test_received_handler.py
  tests/golem/task/test_taskserver.py
  tests/golem/test_client.py
Labels: in progress

#2101 support for enhanced subtask results accepted
  golem/network/concent/received_handler.py
  golem/task/tasksession.py
  requirements.txt
  tests/factories/messages.py
  tests/golem/network/concent/test_concent_client.py
  tests/golem/network/concent/test_received_handler.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#2118 Set default datadir earlier in the flow
  golem/client.py
  golemapp.py
Labels: needs review

#2121 Stop SCI blockchain monitor thread in EthereumTransactionSystem.stop
  golem/transactions/ethereum/ethereumtransactionsystem.py
  requirements.txt
Labels: needs review

#2110 Set min timeouts for rendering tasks
  apps/rendering/task/renderingtask.py
  tests/apps/rendering/task/test_renderingtask.py
Labels: needs review

#2127 Assert fix
  tests/golem/task/test_tasksession.py
Labels: bug, needs review

#1480 Implement PoW for public keys
  golem/appconfig.py
  golem/client.py
  golem/clientconfigdescriptor.py
  golem/core/keysauth.py
  golem/network/p2p/p2pservice.py
  golem/network/p2p/peersession.py
  golem/resource/base/resourceserver.py
  golem/task/taskmanager.py
  golem/task/taskserver.py
  golem/testutils.py
  golem/tools/testwithappconfig.py
  tests/factories/p2p.py
  tests/golem/core/test_keysauth.py
  tests/golem/network/concent/test_concent_client.py
  tests/golem/network/concent/test_received_handler.py
  tests/golem/network/p2p/test_p2pservice.py
  tests/golem/network/p2p/test_peersession.py
  tests/golem/network/transport/test_tcpnetwork.py
  tests/golem/resource/base/test_base_resourceserver.py
  tests/golem/task/test_concent_logic.py
  tests/golem/task/test_taskmanager.py
  tests/golem/task/test_taskserver.py
  tests/golem/task/test_tasksession.py
  tests/golem/test_client.py
  tests/golem/transactions/ethereum/test_ethereumpaymentskeeper.py
  tests/golem/transactions/test_paymentskeeper.py
Labels: in progress

#2012 bump-up python version to 3.6
  setup.py
Labels: in progress

#2145 Sending incomes & balance snapshots to the monitor
  golem/ethereum/paymentprocessor.py
  golem/monitor/model/balancemodel.py
  golem/monitor/monitor.py
  golem/transactions/incomeskeeper.py
  tests/golem/monitor/model/test_balancemodel.py
  tests/golem/monitor/model/test_paymentmodel.py
Labels: monitor

#2139 Concent receive
  golem/network/concent/client.py
  golem/network/concent/constants.py
  golem/network/concent/handlers_library.py
  golem/network/history.py
  golem/task/tasksession.py
  scripts/test-concent.py
  tests/golem/network/concent/test_concent_client.py
  tests/golem/network/test_history.py
Labels: concent, needs review

#2158 Fix macOS startup issues
  golem/node.py
  tests/golem/test_opt_node.py
Labels: bug, needs review, to be merged

#2161 Set database version after each consecutive upgrade
  golem/database/migration/migrate.py
Labels: needs review, to be merged

#2135 Decrease network log severity
  golem/network/transport/tcpnetwork.py
  golem/resource/hyperdrive/resourcesmanager.py
  golem/task/tasksession.py
  tests/golem/task/test_tasksession.py
Labels: needs review, to be merged

#2162 Rename BigIntegerField to HexIntegerField
  golem/database/schemas/007_schema.py
  golem/database/schemas/010_schema.py
  golem/database/schemas/012_schema.py
  golem/model.py
  tests/golem/transactions/test_incomeskeeper.py
Labels: needs review, to be merged

#2117 Download timeout and resource size
  golem/client.py
  golem/network/hyperdrive/client.py
  golem/resource/base/resourceserver.py
  golem/resource/client.py
  golem/task/server/resources.py
  golem/task/tasksession.py
  tests/golem/network/hyperdrive/test_hyperdrive_client.py
  tests/golem/resource/base/test_base_resourceserver.py
  tests/golem/test_client.py
Labels: needs review, to be merged

#2131 Drop waiting_for_task_timeout
  golem/appconfig.py
  golem/clientconfigdescriptor.py
  golem/interface/client/settings.py
  golem/task/taskcomputer.py
  tests/golem/interface/test_client_commands.py
  tests/golem/task/test_taskcomputer.py
  tests/golem/task/test_taskserver.py
Labels: needs review, to be merged

#2120 HyperG version check
  .travis.yml
  appveyor.yml
  circle.yml
  golem/network/hyperdrive/client.py
  golem/network/hyperdrive/daemon_manager.py
  tests/golem/network/hyperdrive/test_hyperdrive_client.py
  tests/golem/network/hyperdrive/test_hyperdrive_daemon_manager.py
Labels: needs review

#2167 Fix loglevel commandline param
  golem/core/common.py
  golemapp.py
  tests/golem/core/test_common.py
Labels: needs review

#2165 Upgrade golem-messages to 1.10
  golem/task/tasksession.py
  requirements.txt
  tests/golem/task/test_tasksession.py
Labels: needs review

#2198 Use new_session_prepare in TaskServer connection established
  golem/task/taskserver.py
Labels: needs review

#2107 Fixed docker version lookup
  Installer/Installer_Win/Golem.aip
Labels: needs review

#2205 Pack database schema migration scripts
  scripts/pyinstaller/hooks/hook-golem.py
Labels: needs review

#2160 Check subtask owners (both providers and requestors)
  golem/task/tasksession.py
  tests/golem/task/test_concent_logic.py
  tests/golem/task/test_tasksession.py
Labels: needs review

#2201 test_renderingtask: restore hidden test case
  tests/apps/rendering/task/test_renderingtask.py
Labels: needs review

#2206 Load truncated images (issue 2059)
  apps/blender/task/blenderrendertask.py
Labels: needs review

#2199 Suppress port check errors
  golem/monitor/monitor.py
Labels: needs review, to be merged

#2218 Fix race in updating preview
  apps/blender/task/verifier.py
Labels: needs review, to be merged

#2221 Provide private key name explicitly
  golem/core/keysauth.py
  golem/node.py
  tests/golem/core/test_keysauth.py
  tests/golem/network/concent/test_concent_client.py
  tests/golem/network/p2p/test_p2pservice.py
  tests/golem/network/p2p/test_peersession.py
  tests/golem/network/transport/test_tcpnetwork.py
  tests/golem/resource/base/test_base_resourceserver.py
  tests/golem/task/dummy/runner.py
  tests/golem/task/test_concent_logic.py
  tests/golem/task/test_taskmanager.py
  tests/golem/task/test_taskserver.py
  tests/golem/test_client.py
  tests/golem/transactions/ethereum/test_ethereumpaymentskeeper.py
  tests/golem/transactions/test_paymentskeeper.py
Labels: needs review

#2178 Synchronization of node time with monitor (#2038)
  golem/client.py
  golem/core/variables.py
  golem/monitor/monitor.py
  golem/monitorconfig.py
  golem/network/p2p/node.py
  tests/golem/monitor/test_monitor.py
  tests/golem/test_client.py
Labels: needs review

#2236 Reactor imports and CLI fixes
  golem/core/async.py
  golem/interface/client/account.py
  golem/network/hyperdrive/client.py
  golem/rpc/router.py
  golemcli.py
  tests/golem/network/hyperdrive/test_hyperdrive_client.py
Labels: needs review

#2215 properly close PIL images and handle errors
  apps/blender/task/blenderrendertask.py
  apps/lux/task/luxrendertask.py
  apps/rendering/benchmark/renderingbenchmark.py
  apps/rendering/resources/imgrepr.py
  apps/rendering/resources/renderingtaskcollector.py
  apps/rendering/resources/utils.py
  apps/rendering/task/framerenderingtask.py
  apps/rendering/task/renderingtask.py
  tests/apps/core/benchmark/test_benchmark.py
  tests/apps/rendering/resources/test_utils.py
  tests/apps/rendering/task/test_renderingtask.py
Labels: needs review, to be merged

#2242 cleanup react_to_hello
  golem/network/p2p/peersession.py
  golem/network/transport/session.py
  golem/task/tasksession.py
  tests/golem/network/p2p/test_peersession.py
  tests/golem/task/test_tasksession.py
Labels: needs review

#2258 Subtask verification queue
  apps/core/task/coretask.py
  apps/core/task/verifier.py
  tests/apps/blender/task/test_blenderrendertask.py
  tests/golem/docker/test_docker_blender_task.py
  tests/golem/docker/test_docker_dummy_task.py
  tests/golem/docker/test_docker_luxrender_task.py
Labels: needs review
