Repository golemfactory/golem, pull requests merged in 2018-06, with the labels that each got.

#2839 show node info logs again
  golem/node.py
  loggingconfig.py
Labels: to be merged

#2841 App verbosity improvement
  golem/node.py
Labels: enhancement, to be merged, user interface

#2843 Asciify terms of use
  golem/TERMS.html
Labels: bug, to be merged

#2845 PyInstaller hook for SSL certs
  scripts/pyinstaller/hooks/hook-golem.py
Labels: bug, needs review, to be merged

#2850 Quick fix for size rounding
  requirements.txt
  requirements_to-freeze.txt
Labels: important, to be merged

#2824 Provider deposit for additional verification in Concent
  golem/task/tasksession.py
  golem/transactions/ethereum/ethereumtransactionsystem.py
  golem/transactions/ethereum/exceptions.py
  scripts/concent_integration_tests/force_accept/test_requestor_doesnt_send.py
  tests/golem/task/test_tasksession.py
  tests/golem/transactions/ethereum/test_ethereumtransactionsystem.py
Labels: needs review

#2855 Merge b0.16.0 to develop
  Installer/Installer_Win/Golem.aip
  golem/TERMS.html
  golem/client.py
  golem/core/common.py
  golem/node.py
  loggingconfig.py
  requirements.txt
  requirements_to-freeze.txt
  scripts/pyinstaller/hooks/hook-golem.py
Labels: needs review

#2867 Pyinstaller: include eth_hash submodules
  lint.sh
  scripts/pyinstaller/hooks/hook-eth_hash.py
Labels: needs review

#2869 + Concent tests: add a test for float deadline in TTC
  scripts/concent_integration_tests/force_report/test_messages.py
Labels: concent

#2722 don't sleep in TestSystemMonitor.test_login_logout_messages
  tests/golem/monitor/test_monitor.py
Labels: needs review

#2875 Remove unused RPC method
  golem/client.py
  golem/rpc/mapping/rpcmethodnames.py
Labels: needs review

#2881 + add checks for the `ForceReportComputedTask`'s `reason` field in Co…
  scripts/concent_integration_tests/force_report/test_messages.py
Labels: concent

#2891 Fix the --geth-address argument
  golem/argsparser.py
  golem/transactions/ethereum/ethereumtransactionsystem.py
  tests/golem/test_opt_node.py
Labels: needs review

#2266 Include registry check for vc_redis
  Installer/Installer_Win/Golem.aip
Labels: needs review

#2825 run default benchmark once
  apps/rendering/benchmark/minilight/src/minilight.py
  golem/client.py
  golem/environments/environment.py
  golem/model.py
  golem/task/benchmarkmanager.py
  tests/apps/blender/test_blenderenvironment.py
  tests/apps/dummy/test_dummyenvironment.py
  tests/apps/lux/test_luxenvironment.py
  tests/golem/environments/test_environment.py
  tests/golem/task/test_benchmarkmanager.py
  tests/golem/test_client.py
Labels: needs review

#2897 Fix concent uc 2 for 16.1
  golem/network/concent/filetransfers.py
  golem/network/concent/received_handler.py
  golem/task/result/resultmanager.py
  golem/task/result/resultpackage.py
  golem/task/taskserver.py
  tests/golem/network/concent/test_filetransfers.py
  tests/golem/network/concent/test_received_handler.py
  tests/golem/task/result/test_resultmanager.py
Labels: concent, to be merged

#2902 Fix package building process for 0.16.1
  lint.sh
  scripts/pyinstaller/hooks/hook-eth_hash.py
Labels: needs review, to be merged

#2858 Fix CLI's `settings show` and `min_price`, `max_price` formatting
  golem/client.py
  golem/clientconfigdescriptor.py
  golem/interface/client/settings.py
  tests/golem/test_client.py
Labels: needs review

#2899 Benchmarks run on linux hw cfg change
  golem/client.py
  golem/core/hardware.py
  golem/task/taskcomputer.py
Labels: to be merged

#2912 Better gas cost estimation for ETH withdrawals (#2872)
  golem/client.py
  golem/transactions/ethereum/ethereumtransactionsystem.py
  requirements.txt
  requirements_to-freeze.txt
  tests/golem/test_client.py
  tests/golem/transactions/ethereum/test_ethereumtransactionsystem.py
Labels: to be merged

#2866 Network masking for tasks
  golem/appconfig.py
  golem/client.py
  golem/clientconfigdescriptor.py
  golem/core/variables.py
  golem/environments/environment.py
  golem/network/p2p/p2pservice.py
  golem/network/p2p/peerkeeper.py
  golem/task/masking.py
  golem/task/taskbase.py
  golem/task/taskkeeper.py
  golem/task/taskmanager.py
  golem/task/taskrequestorstats.py
  golem/task/taskserver.py
  luxrender-output.exr
  tests/apps/core/task/test_coretask.py
  tests/golem/task/dummy/task.py
  tests/golem/task/test_concent_logic.py
  tests/golem/task/test_masking.py
  tests/golem/task/test_taskarchiver.py
  tests/golem/task/test_taskbase.py
  tests/golem/task/test_taskkeeper.py
  tests/golem/task/test_taskmanager.py
  tests/golem/task/test_taskserver.py
  tests/golem/test_client.py
Labels: needs review, network, optimization

#2906 hardware preset tests added
  tests/golem/config/test_presets.py
  tests/golem/core/test_hardware_presets.py
Labels: needs review

#2894 Listen to forced subtask payments from Concent
  golem/transactions/ethereum/ethereumincomeskeeper.py
  golem/transactions/incomeskeeper.py
  requirements.txt
  requirements_to-freeze.txt
  tests/golem/transactions/ethereum/test_ethereumincomeskeeper.py
Labels: needs review

#2920 Fixed 'estimated_memory' issue
  apps/core/task/coretask.py
  golem/client.py
  tests/golem/test_client.py
Labels: bug, important, to be merged

#2921 General fixes
  apps/blender/benchmark/benchmark.py
  apps/blender/resources/scripts/docker_blendertask.py
  apps/blender/task/blenderrendertask.py
  apps/core/benchmark/benchmarkrunner.py
  apps/lux/task/luxrendertask.py
  apps/rendering/task/renderingtask.py
  golem/docker/environment.py
  golem/environments/environment.py
  golem/environments/environmentsconfig.py
  golem/environments/environmentsmanager.py
  golem/task/benchmarkmanager.py
  golem/task/taskbase.py
  golem/task/taskmanager.py
  golem/task/taskserver.py
  tests/apps/blender/benchmark/test_blenderbenchmark.py
Labels: needs review

#2929 Golem sci logs
  loggingconfig.py
Labels: to be merged

#2927 Additional p2p seed and fallback eth nodes
  golem/config/environments/mainnet.py
  golem/config/environments/testnet.py
  golem/ethereum/node.py
Labels: needs review, to be merged

#2903 make dev version hash always 7 hex long cross OS
  golem/tools/version.py
Labels: needs review

#2932 Use golem_sci with fix for TransactionsStorage initialization
  golem/transactions/ethereum/ethereumincomeskeeper.py
  requirements.txt
  requirements_to-freeze.txt
  tests/golem/transactions/ethereum/test_ethereumincomeskeeper.py
Labels: to be merged

#2933 Added exc_info in Node._stop_on_error()
  golem/node.py
Labels: enhancement

#2925 TaskManager.task_needs_computation
  golem/client.py
  golem/task/taskmanager.py
Labels: enhancement, needs review

#2938 WIndows installer name
  Installer/Installer_Win/Golem.aip
  Installer/Installer_Win/Golem.buildbot.aic
Labels: needs review

#2829 TaskThread: avoid handling exceptions from task_computed with _fail
  apps/blender/task/blenderrendertask.py
  apps/core/benchmark/benchmarkrunner.py
  apps/dummy/task/dummytask.py
  golem/docker/task_thread.py
  golem/task/localcomputer.py
  golem/task/taskbase.py
  golem/task/taskcomputer.py
  golem/task/taskthread.py
  golem/vm/memorychecker.py
  golem/vm/vm.py
  tests/apps/core/benchmark/test_benchmarkrunner.py
  tests/golem/task/dummy/task.py
  tests/golem/vm/test_memorychecker.py
Labels: needs review

#2936 Fix typo in connection_for_task_verification_result_failure
  golem/task/taskserver.py
Labels: needs review

#2942 Merge b0.16.1 to develop
  Installer/Installer_Win/Golem.aip
  apps/core/task/coretask.py
  golem/argsparser.py
  golem/client.py
  golem/config/environments/mainnet.py
  golem/config/environments/testnet.py
  golem/core/hardware.py
  golem/ethereum/node.py
  golem/task/taskcomputer.py
  golem/transactions/ethereum/ethereumtransactionsystem.py
  requirements.txt
  requirements_to-freeze.txt
  tests/golem/config/test_presets.py
  tests/golem/core/test_hardware_presets.py
  tests/golem/task/test_taskcomputer.py
  tests/golem/test_client.py
  tests/golem/test_opt_node.py
Labels: needs review

#2940 Switch back provider and requestor in clean res CLI command
  golem/interface/client/resources.py
  tests/golem/interface/test_client_commands.py
Labels: needs review
