Repository golemfactory/golem, pull requests merged in 2018-11, with the labels that each got.

#3437 Sign all messages before adding to DB
  golem/network/history.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  tests/golem/network/concent/test_concent_client.py
  tests/golem/network/concent/test_received_handler.py
  tests/golem/network/test_history.py
  tests/golem/task/test_concent_logic.py
  tests/golem/task/test_tasksession.py
Labels: _current, in progress

#3518 Fix pydispatcher randomness in tests
  tests/conftest.py
Labels: in progress

#3515 Sign every message that is manually remembered
  golem/task/tasksession.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#3525 allow parametrization of the test runs
  scripts/concent_integration_tests/tasks/.gitignore
  scripts/concent_integration_tests/tasks/__init__.py
  scripts/concent_integration_tests/tests/playbooks/base.py
  scripts/concent_integration_tests/tests/playbooks/run.py
Labels: brass, in progress

#3522 Replace AppVeyor status shield with Buildbot ones
  README.md
Labels: in progress

#3523 0.18.0 port status always available
  golem/client.py
  golem/monitor/monitor.py
  tests/golem/test_client.py
Labels: brass, in progress

#3530 fix deferreds in the integration tests
  scripts/concent_integration_tests/rpc/client.py
  scripts/concent_integration_tests/tests/playbooks/base.py
  scripts/concent_integration_tests/tests/playbooks/rpc_test.py
  scripts/concent_integration_tests/tests/playbooks/task_timeout.py
Labels: in progress

#3481 Chore displaying booleans in golemcli
  golem/interface/cli.py
  golem/interface/client/settings.py
  golem/interface/formatters.py
  tests/golem/interface/test_client_commands.py
  tests/golem/interface/test_formatters.py
Labels: in progress

#3531 Add ethsig in concent acceptance tests
  scripts/concent_acceptance_tests/base.py
  scripts/concent_acceptance_tests/force_accept/test_requestor_doesnt_send.py
Labels: in progress

#3439 Environment attribute added into "provider_state"
  golem/client.py
  golem/task/taskcomputer.py
  golem/task/taskthread.py
  tests/golem/task/test_taskcomputer.py
  tests/golem/test_client.py
Labels: _current, in progress

#3532 Made node_id mandatory when fetching messages from history
  golem/network/concent/received_handler.py
  golem/network/history.py
  golem/task/tasksession.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#3533 Update os-win and remove monkey patch
  golem/docker/hypervisor/hyperv.py
  requirements.txt
  tests/golem/docker/test_hyperv.py
Labels: in progress

#3529 Remove `version` from `golemcli network dht` and adapt unit tests
  golem/interface/client/network.py
  tests/golem/interface/test_client_commands.py
Labels: in progress

#3534 Change payments fees display in golemcli
  golem/interface/client/payments.py
  tests/golem/interface/test_client_commands.py
Labels: in progress

#3489 remove eth account from golemcli settings show
  golem/appconfig.py
  golem/clientconfigdescriptor.py
  golem/task/taskstate.py
  tests/golem/task/test_taskmanager.py
Labels: in progress

#3539 Bump version 0.18.2
  Installer/Installer_Win/Golem.aip
Labels: in progress

#3526 Implement provider price function
  golem/ranking/manager/database_manager.py
  golem/task/taskcomputer.py
  golem/task/taskkeeper.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  golem/task/timer.py
  tests/golem/task/test_tasksession.py
  tests/golem/task/test_timer.py
Labels: in progress

#3547 "Waiting for task" status removed on provider state
  golem/client.py
  tests/golem/test_client.py
Labels: _current, to be merged

#3542 Add status filter for golemcli incomes | payments | deposit_payments
  golem/interface/client/payments.py
  tests/golem/interface/test_client_commands.py
Labels: in progress

#3554 Update minimal version of Docker Toolbox to 18.9
  Installer/Installer_Win/Golem.aip
Labels: in progress

#3555 Provider state fix
  golem/client.py
  tests/golem/test_client.py
Labels: in progress

#3546 Remove unnecessary ComputerState
  golem/task/taskmanager.py
  golem/task/taskstate.py
  tests/golem/task/test_taskmanager.py
  tests/golem/task/test_taskstate.py
Labels: in progress

#3559 0.18 to develop
  Installer/Installer_Win/Golem.aip
  golem/client.py
  golem/task/taskcomputer.py
  golem/task/taskthread.py
  scripts/concent_integration_tests/rpc/client.py
  scripts/concent_integration_tests/tests/playbooks/base.py
  scripts/concent_integration_tests/tests/playbooks/rpc_test.py
  scripts/concent_integration_tests/tests/playbooks/task_timeout.py
  tests/golem/task/test_taskcomputer.py
  tests/golem/test_client.py
Labels: in progress

#3561 Added availability check for Hyper-V and re-enabled VirtualBox
  golem/docker/hypervisor/hyperv.py
  golem/docker/manager.py
  requirements-win.txt
  requirements-win_to-freeze.txt
  tests/golem/docker/test_docker_manager.py
Labels: clay, docker, in progress, windows

#3560 Simplify price in CompTaskInfo
  golem/task/taskkeeper.py
  tests/golem/task/test_taskkeeper.py
Labels: in progress

#3568 Fix `deposit_contract_address` values for 'dev' and 'staging'
  golem/core/variables.py
Labels: in progress

#3563 golemcli does not need writeable access to datadir
  golemcli.py
Labels: brass, in progress

#3538 New task state: Creating the deposit
  golem/task/rpc.py
  golem/task/taskmanager.py
  golem/task/taskstate.py
  tests/golem/task/test_rpc.py
Labels: in progress

#3572 fail test on task timeout
  scripts/node_integration_tests/playbooks/base.py
Labels: brass, in progress

#3574 Bring back node_name in CLI
  golem/task/taskmanager.py
  golem/task/taskstate.py
Labels: in progress

#3571 Remove TaskResultDescriptor
  golem/core/variables.py
  golem/task/result/resultpackage.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  tests/factories/resultpackage.py
  tests/golem/task/test_taskserver.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#3549 Moved datadir locking from client to node
  golemapp.py
  golemcli.py
  requirements_to-freeze.txt
  tests/golem/test_client.py
Labels: in progress

#3576 Remove cbor leftovers
  apps/core/task/coretask.py
  golem/task/result/resultpackage.py
  golem/task/tasksession.py
  tests/apps/core/task/test_coretask.py
  tests/golem/core/test_keysauth.py
  tests/golem/task/result/test_resultpackage.py
Labels: in progress

#3537 Added some debug logs for resource pulling
  golem/resource/client.py
  golem/resource/hyperdrive/resourcesmanager.py
  tests/golem/resource/test_resourceclient.py
Labels: in progress

#3577 Marketplace: refactor timers and their method names
  golem/task/taskcomputer.py
  golem/task/taskmanager.py
  golem/task/taskserver.py
  golem/task/timer.py
  tests/golem/task/test_timer.py
Labels: in progress

#3582 Fix restore_locks
  golem/client.py
  golem/task/taskstate.py
  tests/golem/test_client.py
Labels: in progress

#3579 Fix order of preferred geth nodes
  golem/ethereum/node.py
Labels: in progress

#3575 Marketplace: statistics (provider's side)
  golem/ethereum/incomeskeeper.py
  golem/monitor/model/statssnapshotmodel.py
  golem/monitor/monitor.py
  golem/resource/resourcehandshake.py
  golem/task/taskcomputer.py
  golem/task/taskproviderstats.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  golem/task/timer.py
  tests/golem/monitor/model/test_statssnapshotmodel.py
  tests/golem/resource/test_resourcehandshake.py
  tests/golem/task/test_taskproviderstats.py
Labels: in progress, needs review

#3569 Set environment in acceptance tests
  golem/network/concent/client.py
  scripts/concent_acceptance_tests/base.py
  tests/golem/network/concent/test_concent_client.py
Labels: _current, in progress

#3556 Chore update processing subtask results accepted after it contains rct
  golem/task/tasksession.py
  requirements.txt
  requirements_to-freeze.txt
  tests/golem/task/test_tasksession.py
Labels: in progress

#3586 Add reporting of CPU / GPU provider capability to monitor
  golem/monitor/model/loginlogoutmodel.py
  golem/monitor/model/modelbase.py
  tests/golem/monitor/test_monitor.py
Labels: in progress

#3587 B0.18.0
  golem/monitor/model/loginlogoutmodel.py
  golem/monitor/model/modelbase.py
  golemcli.py
  scripts/node_integration_tests/playbooks/base.py
  tests/golem/monitor/test_monitor.py
Labels: in progress

#3540 Added warning on cli and app net mismatch
  golem/client.py
  golem/core/simpleenv.py
  golem/tools/filelock.py
  golemapp.py
  golemcli.py
  requirements.txt
  requirements_to-freeze.txt
  tests/golem/interface/test_golemcli.py
  tests/golem/test_client.py
  tests/golem/test_opt_node.py
  tests/test_golemapp.py
Labels: in progress

#3594 Marketplace: misc fixes
  golem/client.py
  golem/ethereum/paymentprocessor.py
  golem/task/taskkeeper.py
  tests/golem/task/test_taskkeeper.py
  tests/golem/task/test_tasksession.py
  tests/golem/test_client.py
Labels: in progress, needs review

#3595 Fixed datadir mocking in CLI tests
  tests/golem/interface/test_golemcli.py
Labels: in progress

#3598 + add `accept-concent-terms` to the integration test parameters
  scripts/node_integration_tests/params.py
Labels: in progress

#3599 Linux installer: link hyperg-worker
  Installer/Installer_Linux/install.sh
Labels: bug, needs review

#3603 Clean up `ClientProvider.create_task`
  golem/task/rpc.py
  tests/golem/task/test_rpc.py
Labels: in progress

#3602 Ensure that `send_to_concent` will not sign already signed msg
  golem/network/concent/client.py
  tests/golem/network/concent/test_concent_client.py
Labels: in progress

#3596 Cleanup unnecessary checks in SRA handler
  golem/ethereum/incomeskeeper.py
  golem/ethereum/transactionsystem.py
  golem/task/tasksession.py
  tests/golem/ethereum/test_incomeskeeper.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#3607 Remove listen_* args from TaskManager
  golem/task/taskmanager.py
  golem/task/taskserver.py
  tests/golem/task/test_rpc.py
  tests/golem/task/test_taskmanager.py
  tests/golem/task/test_taskserver.py
Labels: in progress

#3608 Remvoe unnecessary set/get_value methods
  golem/task/taskkeeper.py
  golem/task/taskmanager.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  golem/task/taskstate.py
  tests/golem/task/test_taskkeeper.py
  tests/golem/task/test_taskmanager.py
  tests/golem/task/test_taskserver.py
Labels: in progress

#3597 Fix #3592
  apps/blender/verification_task.py
  apps/images.ini
  requirements.txt
  requirements_to-freeze.txt
Labels: needs review

#3609 B0.18.0
  golem/ethereum/incomeskeeper.py
  golem/ethereum/transactionsystem.py
  golem/task/tasksession.py
  scripts/node_integration_tests/README.md
  scripts/node_integration_tests/playbooks/__init__.py
  scripts/node_integration_tests/playbooks/base.py
  scripts/node_integration_tests/playbooks/golem/task_timeout.py
  scripts/node_integration_tests/run_nodes.py
  scripts/node_integration_tests/run_test.py
  scripts/node_integration_tests/tests/test_golem.py
  tests/golem/ethereum/test_incomeskeeper.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#3614 Removed is_this_my_task from task manager
  golem/task/taskmanager.py
  golem/task/taskserver.py
Labels: in progress

#3589 Tweaked docker-machine settings:
  golem/docker/hypervisor/__init__.py
  golem/docker/hypervisor/docker_machine.py
  golem/docker/hypervisor/hyperv.py
  golem/docker/manager.py
  tests/golem/docker/test_docker_manager.py
Labels: in progress

#3611 Remove unused stuff from TaskManager
  golem/clientconfigdescriptor.py
  golem/task/taskmanager.py
  golem/task/taskserver.py
  tests/golem/task/test_taskmanager.py
  tests/golem/task/test_taskserver.py
  tests/golem/test_appconfig.py
  tests/test_clientconfigdescriptor.py
Labels: in progress

#3606 CPU affinity patch
  golem/core/common.py
  golem/core/hardware.py
Labels: in progress, needs review

#3620 Put order back in requirements
  lint.sh
  requirements-lint.txt
  requirements-test.txt
  requirements-test_to-freeze.txt
  requirements-win.txt
  requirements-win_to-freeze.txt
  requirements.txt
  requirements_to-freeze.txt
Labels: in progress

#3621 Fix locks in crossbar for binaries
  golemapp.py
Labels: in progress

#3618 Remove blender deps from CoreTask
  apps/core/task/coretask.py
  apps/core/verification_queue.py
  apps/core/verification_task.py
  tests/apps/blender/task/test_blenderrendertask.py
  tests/apps/blender/verification/test_verification_queue.py
Labels: in progress

#3616 Don't check created_time for overdue incomes
  golem/ethereum/incomeskeeper.py
  tests/golem/ethereum/test_incomeskeeper.py
Labels: in progress

#3615 Clean up add_payment
  golem/ethereum/paymentprocessor.py
  golem/ethereum/transactionsystem.py
  tests/golem/ethereum/test_paymentprocessor.py
Labels: in progress
