Repository golemfactory/golem, pull requests merged in 2018-09, with the labels that each got.

#3270 fix the issue that allows a provider node to be sent a TTC repeatedly…
  golem/task/taskserver.py
  golem/task/tasksession.py
  scripts/concent_integration_tests/nodes/provider/cannot_compute.py
  tests/golem/task/test_taskserver.py
Labels: brass, bug, in progress

#3266 lock additional funds when restarting subtasks
  golem/client.py
  golem/ethereum/fundslocker.py
  golem/task/taskmanager.py
  tests/golem/test_client.py
Labels: brass, in progress

#3225 solve conflicts on b0.17.1
  apps/blender/task/blenderrendertask.py
  apps/core/task/coretask.py
  apps/dummy/task/dummytask.py
  apps/lux/task/luxrendertask.py
  apps/rendering/task/framerenderingtask.py
  golem/task/taskbase.py
  golem/task/taskmanager.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  scripts/concent_integration_tests/nodes/provider/cannot_compute.py
  tests/apps/blender/task/test_blenderrendertask.py
  tests/apps/core/benchmark/test_benchmarkrunner.py
  tests/apps/core/task/test_coretask.py
  tests/apps/lux/task/test_luxrendertask.py
  tests/apps/rendering/task/test_framerenderingtask.py
  tests/apps/rendering/task/test_renderingtask.py
  tests/golem/task/dummy/runner.py
  tests/golem/task/dummy/task.py
  tests/golem/task/test_concent_logic.py
  tests/golem/task/test_taskmanager.py
  tests/golem/task/test_taskserver.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#3277 possible fix for the restart issue
  apps/core/task/coretask.py
Labels: brass, bug, in progress

#3275 fix asserts in Concent acceptance tests
  scripts/concent_acceptance_tests/force_payment/test_payment.py
Labels: concent, in progress

#3259 Deadline already passed
  golem/task/exceptions.py
  golem/task/taskbase.py
  golem/task/taskserver.py
  tests/golem/task/test_taskbase.py
  tests/golem/task/test_taskserver.py
Labels: in progress

#3247 Wait for requestors deposit confirmation
  golem/client.py
  golem/task/tasksession.py
Labels: in progress

#3269 Fix run of InfDefaultInstall command in powershell script
  Installer/Installer_Win/Golem.aip
Labels: in progress

#3283 freeze eth-hash
  requirements.txt
Labels: brass, in progress

#3281 more meaningful "incorrect socket address" error
  golem/task/taskmanager.py
Labels: brass, in progress

#3282 fix error while logging
  golem/ethereum/paymentprocessor.py
Labels: brass, in progress

#3228 Verificator improvements
  apps/blender/blender_reference_generator.py
  apps/blender/verification_queue.py
  apps/blender/verification_task.py
  apps/dummy/benchmark/benchmark.py
  apps/dummy/task/verifier.py
  apps/rendering/task/framerenderingtask.py
  requirements.txt
  requirements_to-freeze.txt
  tests/apps/blender/task/test_blenderrendertask.py
  tests/apps/blender/verification/test_verificator_integration.py
  tests/golem/docker/test_docker_dummy_task.py
  tests/golem/docker/test_docker_luxrender_task.py
Labels: in progress, needs review

#3288 dump_balance() quick fix
  scripts/concent_acceptance_tests/base.py
Labels: in progress

#3292 Update taskcollector Makefile
  apps/rendering/resources/taskcollector/Makefile
Labels: in progress

#3273 Misc log improvements
  golem/client.py
  golem/core/common.py
  golem/network/p2p/p2pservice.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  tests/golem/docker/test_docker_task.py
  tests/golem/resource/base/common.py
  tests/golem/task/test_concent_logic.py
  tests/golem/task/test_taskserver.py
  tests/golem/task/test_tasksession.py
  tests/golem/test_client.py
  tests/golem/test_opt_node.py
Labels: in progress

#3289 Merge b0.17.1 with develop
  .travis.yml
  Installer/Installer_Win/Golem.aip
  apps/blender/blender_reference_generator.py
  apps/core/task/coretask.py
  circle.yml
  golem/client.py
  golem/ethereum/fundslocker.py
  golem/ethereum/paymentprocessor.py
  golem/ethereum/web3/providers.py
  golem/network/p2p/peerkeeper.py
  golem/task/taskkeeper.py
  golem/task/taskmanager.py
  requirements.txt
  shippable.yml
  tests/golem/ethereum/test_fundslocker.py
  tests/golem/network/p2p/test_peerkeeper.py
  tests/golem/task/test_taskkeeper.py
  tests/golem/task/test_tasksession.py
  tests/golem/test_client.py
Labels: _current, brass, in progress

#3274 Add tests for subtask restart
  golem/ethereum/fundslocker.py
  tests/golem/ethereum/test_fundslocker.py
  tests/golem/task/test_taskmanager.py
  tests/golem/test_client.py
Labels: _current, brass, in progress

#3280 Another possible fix for the restart issue
  golem/task/taskmanager.py
  tests/golem/task/test_taskmanager.py
Labels: _current, brass, in progress

#3299 Simplify test_client.py
  golem/client.py
  tests/golem/test_client.py
Labels: in progress

#3306 Get rid of DuplicatedHandler warnings
  tests/golem/network/concent/test_received_handler.py
  tests/golem/task/dummy/test_runner_script.py
Labels: in progress

#3298 remove support for Concent's `receive-out-of-band` endpoint
  golem/network/concent/client.py
  scripts/concent_acceptance_tests/additional_verification/test_verification.py
  scripts/concent_acceptance_tests/base.py
  scripts/concent_acceptance_tests/force_payment/test_payment.py
  tests/golem/network/concent/test_concent_client.py
Labels: concent, in progress

#3307 bump messages to 2.13.0 (add verification of received TTC's ethsig)
  requirements.txt
  requirements_to-freeze.txt
Labels: in progress

#3315 Lock GNT during withdrawal
  golem/ethereum/transactionsystem.py
  tests/golem/ethereum/test_transactionsystem.py
Labels: in progress

#3304 Take into consideration TaskHeader.concent_enabled
  golem/environments/environment.py
  golem/resource/resourcehandshake.py
  golem/task/taskserver.py
  tests/factories/task/taskbase.py
  tests/golem/resource/test_resourcehandshake.py
  tests/golem/task/test_taskserver.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#3294 Don't return None during web3 requests
  golem/ethereum/node.py
  golem/ethereum/web3/middleware.py
  tests/golem/ethereum/web3/test_middleware.py
Labels: in progress

#3322 Removal NAT type retrieval
  golem/core/hostaddress.py
  golem/network/p2p/node.py
  golem/network/stun/pystun.py
  tests/golem/core/test_hostaddress.py
  tests/golem/task/dummy/runner.py
Labels: in progress

#3203 Docker for Mac
  golem/docker/client.py
  golem/docker/commands/__init__.py
  golem/docker/commands/docker.py
  golem/docker/commands/docker_for_mac.py
  golem/docker/commands/docker_machine.py
  golem/docker/config.py
  golem/docker/hypervisor/__init__.py
  golem/docker/hypervisor/docker_for_mac.py
  golem/docker/hypervisor/docker_machine.py
  golem/docker/hypervisor/virtualbox.py
  golem/docker/hypervisor/xhyve.py
  golem/docker/job.py
  golem/docker/manager.py
  golem/node.py
  golem/task/taskcomputer.py
  requirements-win_to-freeze.txt
  requirements.txt
  requirements_to-freeze.txt
  setup.py
  tests/conftest.py
  tests/golem/docker/test_blender_job.py
  tests/golem/docker/test_docker_commands.py
  tests/golem/docker/test_docker_config_manager.py
  tests/golem/docker/test_docker_image.py
  tests/golem/docker/test_docker_job.py
  tests/golem/docker/test_docker_manager.py
  tests/golem/docker/test_hypervisor.py
  tests/golem/task/test_benchmarkmanager.py
  tests/golem/task/test_taskcomputer.py
  tests/golem/test_opt_node.py
Labels: clay, docker, in progress, needs review

#3133 nvidia-docker packaging (pyinstaller)
  scripts/pyinstaller/hooks/hook-golem.py
Labels: clay, docker, in progress, needs review

#3094 nvidia-docker installer
  Installer/Installer_Linux/install.sh
Labels: clay, docker, in progress, needs review

#3257 Finished part 2 of installer Docker for Windows
  Installer/Installer_Win/Golem.aip
  Installer/Installer_Win/make_install_tmp.bat
Labels: in progress, needs review

#3278 RPC support for deposit transactions
  golem/client.py
  golem/database/database.py
  golem/database/schemas/021_create_deposit_payment.py
  golem/ethereum/exceptions.py
  golem/ethereum/transactionsystem.py
  golem/interface/client/payments.py
  golem/model.py
  golem/rpc/mapping/rpcmethodnames.py
  golem/task/tasksession.py
  tests/golem/ethereum/test_transactionsystem.py
  tests/golem/test_client.py
Labels: in progress

#3323 Upgrade to Golem-Messages v2.13.2
  apps/core/task/coretask.py
  golem/core/idgenerator.py
  golem/task/taskkeeper.py
  requirements.txt
  requirements_to-freeze.txt
  tests/factories/taskserver.py
  tests/golem/network/concent/test_received_handler.py
  tests/golem/task/dummy/task.py
  tests/golem/task/test_taskbase.py
  tests/golem/task/test_taskkeeper.py
  tests/golem/task/test_taskserver.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#3326 Fix constrains for the docker vms
  golem/docker/config.py
  golem/docker/hypervisor/hyperv.py
Labels: in progress

#3329 bump messages to 2.14.0
  requirements.txt
  requirements_to-freeze.txt
Labels: in progress

#3325 Added debug output printing for docker commands on
  golem/docker/commands/docker.py
  golem/docker/hypervisor/__init__.py
Labels: in progress

#3333 Set concent_enabled in task definition
  golem/client.py
  golem/task/taskmanager.py
  golem/task/taskserver.py
  tests/golem/test_client.py
Labels: in progress

#3171 RPC client wampcra auth
  .gitignore
  golem/interface/websockets.py
  golem/node.py
  golem/rpc/cert.py
  golem/rpc/mapping/rpcmethodnames.py
  golem/rpc/router.py
  golem/rpc/session.py
  golemapp.py
  golemcli.py
  tests/golem/interface/test_golemcli.py
  tests/golem/interface/test_websocket_cli.py
  tests/golem/rpc/test_cert.py
  tests/golem/rpc/test_router.py
  tests/test_golemapp.py
Labels: needs review

#3045 Nvidia docker
  Installer/Installer_Linux/install.sh
  apps/appsmanager.py
  apps/blender/benchmark/benchmark.py
  apps/blender/benchmark/test_task/bmw27_gpu.blend
  apps/blender/blenderenvironment.py
  apps/blender/resources/images/blender.Dockerfile
  apps/blender/resources/images/blender_nvgpu.Dockerfile
  apps/blender/resources/scripts/blendercrop.py.template
  apps/blender/task/blenderrendertask.py
  apps/core/nvgpu/__init__.py
  apps/core/resources/images/base.Dockerfile
  apps/core/resources/images/nvgpu.Dockerfile
  apps/core/task/coretask.py
  apps/core/task/coretaskstate.py
  apps/images.ini
  apps/registered_test.ini
  golem/core/common.py
  golem/docker/client.py
  golem/docker/environment.py
  golem/docker/job.py
  golem/docker/manager.py
  golem/environments/environmentsmanager.py
  golem/task/taskbase.py
  golem/task/taskcomputer.py
  golem/task/taskmanager.py
  requirements-win.txt
  requirements-win_to-freeze.txt
  scripts/pyinstaller/hooks/hook-golem.py
  setup_util/setup_commons.py
  tests/apps/rendering/task/test_renderingtask.py
  tests/apps/test_appsmanager.py
  tests/golem/docker/test_docker_job.py
  tests/golem/docker/test_docker_manager.py
  tests/golem/docker/test_docker_task.py
  tests/golem/task/test_benchmarkmanager.py
  tests/golem/task/test_taskkeeper.py
  tests/golem/test_client.py
Labels: clay, docker, in progress, needs review

#3338 Add the missing env variable (nvgpu)
  apps/blender/blenderenvironment.py
Labels: bug, in progress

#3337 Add current user to hyperv group
  Installer/Installer_Win/Golem.aip
Labels: clay, in progress, needs review

#3343 fix Concent integration tests after introduction of the new RPC authentication
  golem/rpc/cert.py
  scripts/concent_integration_tests/params.py
  scripts/concent_integration_tests/rpc/client.py
Labels: concent, in progress

#3344 Docker resources permissions
  golem/docker/job.py
  tests/golem/docker/test_docker_job.py
Labels: in progress

#3349 Remove perf from subtask info
  apps/blender/task/blenderrendertask.py
  apps/core/task/coretask.py
  apps/dummy/task/dummytask.py
  apps/lux/task/luxrendertask.py
  tests/apps/blender/verification/test_verificator_integration.py
Labels: in progress

#3328 Hyper-V support
  golem/client.py
  golem/docker/config.py
  golem/docker/hypervisor/__init__.py
  golem/docker/hypervisor/docker_machine.py
  golem/docker/hypervisor/hyperv.py
  golem/docker/hypervisor/virtualbox.py
  golem/docker/hypervisor/xhyve.py
  golem/docker/job.py
  golem/docker/manager.py
  golem/docker/smbshare.py
  golem/docker/task_thread.py
  golem/task/benchmarkmanager.py
  golem/task/taskcomputer.py
  golem/task/taskserver.py
  requirements-lint.txt
  requirements-test.txt
  requirements.txt
  requirements_to-freeze.txt
  scripts/create-share.ps1
  scripts/get-ip-address.ps1
  scripts/pyinstaller/hooks/hook-golem.py
  tests/apps/blender/benchmark/test_blenderbenchmark.py
  tests/apps/blender/verification/test_verificator_integration.py
  tests/golem/docker/test_docker_config_manager.py
  tests/golem/docker/test_docker_job.py
  tests/golem/docker/test_docker_manager.py
  tests/golem/docker/test_hyperv.py
  tests/golem/docker/test_hypervisor.py
  tests/golem/docker/test_smbshare.py
  tests/golem/task/test_benchmarkmanager.py
  tests/golem/task/test_taskcomputer.py
Labels: clay, docker, in progress, windows

#3346 More short node_ids, part 3
  apps/blender/task/blenderrendertask.py
  golem/network/transport/tcpserver.py
  golem/task/taskkeeper.py
  golem/task/taskmanager.py
  tests/golem/docker/test_docker_task.py
Labels: in progress

#3348 Add --mainnet parameter to golemcli
  golem/config/environments/__init__.py
  golemcli.py
Labels: in progress

#3353 First draft on using dynamic memory for hyperv
  golem/docker/hypervisor/hyperv.py
  tests/golem/docker/test_hyperv.py
Labels: clay, in progress

#3314 Feature add support for want to compute task inside task to compute
  golem/network/concent/helpers.py
  golem/resource/resourcehandshake.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  requirements.txt
  requirements_to-freeze.txt
  tests/golem/network/concent/test_helpers.py
  tests/golem/network/concent/test_received_handler.py
  tests/golem/task/dummy/runner.py
  tests/golem/task/test_concent_logic.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#3359 Fix container config
  golem/docker/job.py
Labels: bug, in progress

#3361 + some additional logging for tasksession/taskmanager to ease debuggi…
  golem/task/taskmanager.py
  golem/task/tasksession.py
Labels: in progress
