Repository golemfactory/golem, pull requests merged in 2018-10, with the labels that each got.

#3363 Minor cleanup of react_to_want_to_compute_task
  golem/task/tasksession.py
Labels: in progress

#3360 Add parameter back and increase logging
  Installer/Installer_Win/Golem.aip
Labels: in progress

#3369 Make VirtualBox driver fix run everytime (not only during upgrade)
  Installer/Installer_Win/Golem.aip
Labels: in progress

#3371 Start VM means `start` not `restart`
  golem/docker/commands/docker_machine.py
  golem/docker/hypervisor/docker_machine.py
Labels: clay, docker, in progress, windows

#3367 Fix verification paths to work again on windows
  golem/task/taskmanager.py
  golem/task/taskserver.py
  golem/testutils.py
  tests/apps/blender/benchmark/test_blenderbenchmark.py
  tests/apps/blender/verification/test_verificator_integration.py
  tests/golem/task/test_localcomputer.py
Labels: clay, docker, in progress, needs review, windows

#3373 make `concent_enabled` key optional for `TaskManager.create_task` dictionary
  golem/client.py
  golem/task/taskmanager.py
  golem/tools/assertlogs.py
  tests/golem/test_client.py
Labels: in progress

#3376 add dns as hidden import
  scripts/pyinstaller/hooks/hook-golem.py
Labels: in progress, needs review

#3374 Handle any errors on accepting results
  apps/core/task/coretask.py
Labels: needs review

#3291 Verification restart after timeout
  apps/blender/verification_queue.py
  apps/blender/verification_task.py
  requirements.txt
  requirements_to-freeze.txt
  tests/apps/blender/verification/test_verification_queue.py
Labels: needs review

#3379 Fixes from first day of testing
  Installer/Installer_Win/Golem.aip
Labels: docker, in progress, needs review, windows

#3380 Update SCI to 1.6.1
  requirements.txt
  requirements_to-freeze.txt
Labels: in progress

#3385 NVGPU on mainnet
  apps/registered.ini
  apps/registered_test.ini
Labels: in progress, needs review

#3362 Providers to send offers to multiple requestors at the same time
  golem/client.py
  golem/monitor/model/taskcomputersnapshotmodel.py
  golem/task/taskcomputer.py
  golem/task/taskkeeper.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  luxrender-output.exr
  tests/golem/monitor/model/test_taskcomputersnapshotmodel.py
  tests/golem/task/test_concent_logic.py
  tests/golem/task/test_taskcomputer.py
  tests/golem/task/test_taskkeeper.py
  tests/golem/task/test_tasksession.py
  tests/golem/test_client.py
Labels: in progress

#2702 Client.connection_status: send raw data
  golem/client.py
  golem/interface/client/network.py
  tests/golem/interface/test_client_commands.py
  tests/golem/test_client.py
Labels: 0, _current, in progress, needs review

#3062 expose testing tasks via cli
  golem/client.py
  golem/interface/client/tasks.py
  golem/interface/client/test_task.py
  golem/task/taskstate.py
  golemcli.py
  tests/golem/interface/test_client_commands.py
  tests/golem/test_client.py
Labels: _current, brass, in progress, needs review

#3313 Allow origins fix
  golem/rpc/router.py
  golem/rpc/session.py
Labels: _current, to be merged

#3388 Exact scene file
  apps/rendering/task/renderingtask.py
  tests/apps/rendering/task/test_renderingtask.py
Labels: _current, in progress

#3387 [WIP] Create vnet switch from golem before creating vm
  Installer/Installer_Win/Golem.aip
  golem/docker/hypervisor/hyperv.py
  scripts/create-vnet-switch.ps1
  scripts/pyinstaller/hooks/hook-golem.py
  tests/golem/docker/test_hyperv.py
Labels: clay, docker, in progress, windows

#3341 Add directory support to resultpackage module
  apps/core/task/coretask.py
  golem/docker/task_thread.py
  golem/task/result/resultpackage.py
  tests/golem/task/result/test_resultpackage.py
Labels: in progress, needs review

#3393 Remove too-few-public-methods pylint warning
  .pylintrc
  apps/blender/blenderenvironment.py
  apps/blender/task/blenderrendertask.py
  apps/rendering/resources/utils.py
  golem/config/environments/mainnet.py
  golem/config/environments/testnet.py
  golem/core/printable_object.py
  golem/database/migration/create.py
  golem/database/schemas/007_schema.py
  golem/database/schemas/009_schema.py
  golem/database/schemas/012_schema.py
  golem/database/schemas/014_schema.py
  golem/database/schemas/015_schema.py
  golem/database/schemas/016_schema.py
  golem/database/schemas/017_schema.py
  golem/database/schemas/018_schema.py
  golem/database/schemas/019_schema.py
  golem/database/schemas/020_income_value_received.py
  golem/database/schemas/021_create_deposit_payment.py
  golem/ethereum/fundslocker.py
  golem/interface/websockets.py
  golem/manager/nodestatesnapshot.py
  golem/model.py
  golem/monitor/model/statssnapshotmodel.py
  golem/network/concent/filetransfers.py
  golem/node.py
  golem/task/result/resultpackage.py
  golem/task/taskrequestorstats.py
  golem/vm/memorychecker.py
  tests/apps/rendering/resources/test_utils.py
  tests/factories/concent.py
  tests/factories/model.py
  tests/factories/p2p.py
  tests/factories/resultpackage.py
  tests/factories/task/taskbase.py
  tests/factories/taskserver.py
  tests/golem/core/test_printable_object.py
  tests/golem/docker/test_docker_blender_task.py
  tests/golem/docker/test_docker_task.py
  tests/golem/docker/test_hypervisor.py
  tests/golem/network/concent/test_received_handler.py
Labels: in progress

#3395 drop some noqa
  apps/dummy/benchmark/benchmark.py
  golem/network/concent/filetransfers.py
  golem/task/result/resultpackage.py
  tests/golem/docker/test_blender_job.py
  tests/golem/docker/test_docker_task.py
  tests/golem/network/concent/test_received_handler.py
  tests/golem/rpc/test_cert.py
Labels: in progress

#3365 Concent relock, unlock and withdraw
  golem/ethereum/transactionsystem.py
  tests/golem/ethereum/test_transactionsystem.py
Labels: in progress

#3368 Unburden golem.client as a sole RPC provider
  apps/rendering/task/framerenderingtask.py
  golem/client.py
  golem/config/presets.py
  golem/environments/environmentsmanager.py
  golem/environments/minperformancemultiplier.py
  golem/ethereum/transactionsystem.py
  golem/interface/client/account.py
  golem/interface/client/debug.py
  golem/interface/client/environments.py
  golem/interface/client/resources.py
  golem/interface/client/tasks.py
  golem/interface/client/terms.py
  golem/interface/websockets.py
  golem/network/concent/client.py
  golem/node.py
  golem/rpc/mapping/rpcmethodnames.py
  golem/rpc/router.py
  golem/rpc/session.py
  golem/rpc/utils.py
  golem/task/taskmanager.py
  tests/golem/docker/test_docker_task.py
  tests/golem/ethereum/test_transactionsystem.py
  tests/golem/interface/test_client_commands.py
  tests/golem/interface/test_websocket_cli.py
  tests/golem/rpc/test_router.py
  tests/golem/rpc/test_session.py
  tests/golem/test_client.py
Labels: in progress

#3320 Remove dead code from TaskComputer
  golem/task/taskcomputer.py
  tests/golem/docker/test_docker_task.py
  tests/golem/task/test_taskcomputer.py
Labels: in progress

#3401 Remove scipy and ssim dependencies
  apps/rendering/resources/imgverifier.py
  golem/network/p2p/p2pservice.py
  requirements.txt
  requirements_to-freeze.txt
  scripts/pyinstaller/hooks/hook-scipy.py
Labels: in progress

#3389 Optimize run_blender_task function
  apps/blender/resources/scripts/docker_blendertask.py
Labels: in progress

#3416 downgrade log severity of the "faucet error" from `error` to `warning`
  golem/ethereum/transactionsystem.py
Labels: in progress

#3403 Use default virtual network switch
  golem/docker/hypervisor/hyperv.py
  scripts/create-vnet-switch.ps1
  scripts/get-default-vswitch.ps1
  scripts/get-ip-address.ps1
  scripts/pyinstaller/hooks/hook-golem.py
  tests/golem/docker/test_hyperv.py
Labels: clay, docker, in progress, windows

#3411 Remove old inno file
  Installer/Installer_Win/install_script.iss
Labels: in progress

#3420 Bump version in advanced installer
  Installer/Installer_Win/Golem.aip
Labels: in progress

#3409 Add firewall rule, moved inline script to script file.
  Installer/Installer_Win/Golem.aip
  scripts/prepare-docker-for-windows.ps1
Labels: in progress

#3417 fix `net.status` RPC call in the integration tests
  scripts/concent_integration_tests/nodes/provider/cannot_compute.py
  scripts/concent_integration_tests/nodes/provider/debug.py
  scripts/concent_integration_tests/nodes/provider/impatient_frct.py
  scripts/concent_integration_tests/nodes/provider/no_concent.py
  scripts/concent_integration_tests/nodes/provider/no_second_wtct.py
  scripts/concent_integration_tests/nodes/provider/regular.py
  scripts/concent_integration_tests/nodes/requestor/debug.py
  scripts/concent_integration_tests/nodes/requestor/fail_results.py
  scripts/concent_integration_tests/nodes/requestor/no_ack_rct.py
  scripts/concent_integration_tests/nodes/requestor/no_concent.py
  scripts/concent_integration_tests/nodes/requestor/no_sra.py
  scripts/concent_integration_tests/nodes/requestor/regular.py
  scripts/concent_integration_tests/nodes/requestor/reject_results.py
  scripts/concent_integration_tests/tests/playbooks/base.py
Labels: brass, in progress

#3404 calculate against subtask res
  apps/blender/blender_reference_generator.py
  tests/apps/blender/verification/test_blender_reference_generator.py
Labels: needs review

#3407 Don't create awaiting payments too early
  golem/ethereum/incomeskeeper.py
  golem/ethereum/transactionsystem.py
  golem/network/concent/received_handler.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  tests/golem/ethereum/test_incomeskeeper.py
  tests/golem/network/concent/test_concent_client.py
  tests/golem/network/concent/test_received_handler.py
  tests/golem/task/test_taskserver.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#3406 Migrate task definition pickles from 0.17.1
  apps/core/task/coretaskstate.py
  tests/apps/core/task/test_coretaskstate.py
Labels: in progress

#3427 b0.18.0 to develop
  Installer/Installer_Win/Golem.aip
  apps/blender/blender_reference_generator.py
  apps/core/task/coretaskstate.py
  golem/ethereum/incomeskeeper.py
  golem/ethereum/transactionsystem.py
  golem/network/concent/received_handler.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  scripts/concent_integration_tests/nodes/provider/cannot_compute.py
  scripts/concent_integration_tests/nodes/provider/debug.py
  scripts/concent_integration_tests/nodes/provider/impatient_frct.py
  scripts/concent_integration_tests/nodes/provider/no_concent.py
  scripts/concent_integration_tests/nodes/provider/no_second_wtct.py
  scripts/concent_integration_tests/nodes/provider/regular.py
  scripts/concent_integration_tests/nodes/requestor/debug.py
  scripts/concent_integration_tests/nodes/requestor/fail_results.py
  scripts/concent_integration_tests/nodes/requestor/no_ack_rct.py
  scripts/concent_integration_tests/nodes/requestor/no_concent.py
  scripts/concent_integration_tests/nodes/requestor/no_sra.py
  scripts/concent_integration_tests/nodes/requestor/regular.py
  scripts/concent_integration_tests/nodes/requestor/reject_results.py
  scripts/concent_integration_tests/tests/playbooks/base.py
  tests/apps/blender/verification/test_blender_reference_generator.py
  tests/apps/core/task/test_coretaskstate.py
  tests/golem/ethereum/test_incomeskeeper.py
  tests/golem/network/concent/test_concent_client.py
  tests/golem/network/concent/test_received_handler.py
  tests/golem/task/test_taskserver.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#3429 Stop race-condition in CLI
  golem/interface/websockets.py
Labels: in progress

#3424 Remove unnecessary short_desc
  golem/docker/task_thread.py
  golem/task/localcomputer.py
  golem/task/taskcomputer.py
  golem/task/taskthread.py
  tests/golem/docker/test_docker_task_thread.py
  tests/golem/task/test_taskcomputer.py
Labels: in progress

#3384 Marketplace: requestor tracks providers' computation time
  golem/task/taskmanager.py
  golem/task/timer.py
  tests/golem/task/test_timer.py
Labels: in progress

#3431 fix `get_ttc_kwargs` in the base concent acceptance test
  scripts/concent_acceptance_tests/base.py
Labels: brass, concent, in progress

#3428 Accept SRA without `comp_task_keeper` record
  golem/ethereum/incomeskeeper.py
  golem/ethereum/transactionsystem.py
  golem/task/tasksession.py
  tests/golem/ethereum/test_incomeskeeper.py
  tests/golem/task/test_concent_logic.py
  tests/golem/task/test_tasksession.py
Labels: _current, brass, in progress

#3426 Refactor assigned_subtasks
  golem/monitor/model/taskcomputersnapshotmodel.py
  golem/node.py
  golem/task/taskcomputer.py
  tests/golem/monitor/model/test_taskcomputersnapshotmodel.py
  tests/golem/task/test_taskcomputer.py
  tests/golem/test_opt_node.py
Labels: in progress

#3434 Remove broken check from react to sra
  golem/task/tasksession.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#3436 B0.18.0
  golem/ethereum/incomeskeeper.py
  golem/ethereum/transactionsystem.py
  golem/task/tasksession.py
  scripts/concent_acceptance_tests/base.py
  tests/golem/ethereum/test_incomeskeeper.py
  tests/golem/task/test_concent_logic.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#3372 Marketplace: track provider idle time
  golem/task/taskcomputer.py
  golem/task/taskmanager.py
  golem/task/timer.py
  tests/golem/task/test_timer.py
Labels: clay, in progress, needs review

#3432 fix the contract addresses in the Concent Acceptance tests
  golem/config/environments/testnet.py
  golem/core/variables.py
  scripts/concent_acceptance_tests/base.py
Labels: in progress

#3440 sign the TTC when sending SubtaskResultsAccepted
  golem/task/tasksession.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#3441 fix the SRA check
  golem/task/tasksession.py
Labels: in progress

#3442 B0.18.0
  golem/config/environments/testnet.py
  golem/core/variables.py
  golem/task/tasksession.py
  scripts/concent_acceptance_tests/base.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#3443 Use decorator for post initialization checks in TransactionSystem
  golem/ethereum/transactionsystem.py
Labels: in progress

#3202 Marketplace implementation stub in Rust
  .gitignore
  README.md
  golem/marketplace/__init__.py
  requirements.txt
  requirements_to-freeze.txt
  rust/golem/Cargo.lock
  rust/golem/Cargo.toml
  rust/golem/src/lib.rs
  rust/golem/src/marketplace.rs
  setup.py
  tests/golem/marketplace/test_marketplace.py
Labels: in progress

#3448 change the Concent Integration test datadir report so that it can be …
  scripts/concent_integration_tests/params.py
Labels: in progress

#1888 Generic binaries for running golem from source
  scripts/test_bin/README.md
  scripts/test_bin/posix/.bin_config.sh
  scripts/test_bin/posix/_load_config.sh
  scripts/test_bin/posix/golem_source__prep.sh
  scripts/test_bin/posix/golem_source_init.sh
  scripts/test_bin/posix/golem_source_run.sh
  scripts/test_bin/posix/golem_source_run_debug.sh
  scripts/test_bin/posix/golem_source_run_private.sh
  scripts/test_bin/posix/golem_source_update.sh
  scripts/test_bin/windows/golem_source__prep.bat
  scripts/test_bin/windows/golem_source_init.bat
  scripts/test_bin/windows/golem_source_run.bat
  scripts/test_bin/windows/golem_source_run_debug.bat
  scripts/test_bin/windows/golem_source_run_private.bat
  scripts/test_bin/windows/golem_source_update.bat
Labels: in progress

#3418 Change the way concent withdrawal is requested
  golem/core/deferred.py
  golem/ethereum/transactionsystem.py
  tests/golem/ethereum/test_transactionsystem.py
Labels: in progress

#3449 Shorten id on taskserver requestor rejection
  golem/task/taskserver.py
Labels: in progress

#3454 Fix fundslocker to use Task API properly
  golem/ethereum/fundslocker.py
  tests/golem/ethereum/test_fundslocker.py
  tests/golem/test_client.py
Labels: in progress

#3455 Fix expected income
  golem/ethereum/incomeskeeper.py
  tests/golem/ethereum/test_incomeskeeper.py
Labels: in progress

#3456 Core verifier doesnt hold deferred
  requirements.txt
  requirements_to-freeze.txt
Labels: needs review

#3433 Move enqueue_new_task & friends to separate module
  golem/client.py
  golem/interface/client/tasks.py
  golem/interface/client/test_task.py
  golem/interface/command.py
  golem/node.py
  golem/task/rpc.py
  golem/task/taskbase.py
  golem/task/taskmanager.py
  tests/golem/interface/test_client_commands.py
  tests/golem/task/dummy/runner.py
  tests/golem/task/dummy/test_runner_script.py
  tests/golem/task/test_rpc.py
  tests/golem/test_client.py
Labels: in progress

#3458 Fix TaskManager dependency on derived class
  golem/task/rpc.py
  golem/task/taskbase.py
  tests/apps/core/benchmark/test_benchmarkrunner.py
Labels: in progress

#3445 Improved test_react_to_subtask_result_accepted
  golem/core/common.py
  golem/task/taskkeeper.py
  golem/task/tasksession.py
  tests/golem/task/test_tasksession.py
Labels: _current, brass, in progress

#3461 0.18.0 fix unsupported output format
  apps/blender/task/blenderrendertask.py
  scripts/concent_integration_tests/tasks/__init__.py
  scripts/concent_integration_tests/tests/playbooks/base.py
  scripts/concent_integration_tests/tests/playbooks/regular_run_exr.py
  scripts/concent_integration_tests/tests/playbooks/regular_run_jpeg.py
  scripts/concent_integration_tests/tests/playbooks/regular_run_jpg.py
  scripts/concent_integration_tests/tests/test_exr.py
  scripts/concent_integration_tests/tests/test_jpeg.py
  scripts/concent_integration_tests/tests/test_jpg.py
  tests/apps/blender/task/test_blenderrendertask.py
Labels: brass, important, in progress

#3465 detect `docker` vs `docker-py` package conflict and issue a warning +…
  setup.py
Labels: brass, in progress

#3446 Estimate gas price/deposit time
  golem/ethereum/exceptions.py
  golem/ethereum/transactionsystem.py
  golem/interface/client/tasks.py
  golem/task/rpc.py
  tests/golem/ethereum/test_transactionsystem.py
  tests/golem/interface/test_client_commands.py
  tests/golem/task/test_rpc.py
Labels: in progress

#3469 Fix missing freeze requirements
  requirements_to-freeze.txt
Labels: in progress

#3466 Fix log message
  golem/ethereum/fundslocker.py
Labels: in progress

#3468 Rename async to golem_async
  golem/core/golem_async.py
  golem/core/service.py
  golem/ethereum/node.py
  golem/network/hyperdrive/client.py
  golem/node.py
  golem/resource/base/resourceserver.py
  golem/task/result/resultmanager.py
  golem/task/rpc.py
  golem/task/taskarchiver.py
  golem/task/taskkeeper.py
  golem/testutils.py
  tests/golem/ethereum/test_ethereum_node.py
  tests/golem/network/hyperdrive/test_hyperdrive_client.py
  tests/golem/resource/base/test_base_resourceserver.py
  tests/golem/resource/test_resourceclient.py
  tests/golem/task/test_taskkeeper.py
  tests/golem/test_opt_node.py
Labels: in progress

#3470 add a provider income check to the integration test
  scripts/concent_integration_tests/tests/playbooks/base.py
Labels: brass, ci & tests, in progress

#3471 Always set default 'concent_enabled' before _validate_task_dict
  golem/task/rpc.py
  tests/golem/task/test_rpc.py
Labels: in progress

#3472 B0.18.0
  scripts/concent_integration_tests/tests/playbooks/base.py
Labels: in progress

#3463 Names refactor
  apps/blender/task/blenderrendertask.py
  apps/core/task/coretask.py
  apps/core/task/coretaskstate.py
  apps/dummy/task/dummytaskstate.py
  apps/rendering/benchmark/renderingbenchmark.py
  apps/rendering/task/framerenderingtask.py
  apps/rendering/task/renderingtask.py
  apps/rendering/task/renderingtaskstate.py
  golem/core/variables.py
  golem/interface/client/tasks.py
  golem/task/rpc.py
  golem/task/taskmanager.py
  golem/task/taskstate.py
  scripts/concent_integration_tests/tasks/__init__.py
  tests/apps/blender/task/test_blenderrendertask.py
  tests/apps/core/task/test_coretask.py
  tests/apps/core/task/test_coretaskstate.py
  tests/apps/dummy/task/test_dummytask.py
  tests/apps/dummy/task/test_dummytaskstate.py
  tests/apps/rendering/task/test_framerenderingtask.py
  tests/apps/rendering/task/test_renderingtask.py
  tests/apps/rendering/task/test_renderingtaskstate.py
  tests/golem/docker/docker-blender-cycles-task.json
  tests/golem/docker/docker-blender-render-task.json
  tests/golem/docker/docker-dummy-test-task.json
  tests/golem/docker/test_docker_blender_task.py
  tests/golem/interface/test_client_commands.py
  tests/golem/resource/test_resource.py
  tests/golem/task/dummy/task.py
  tests/golem/task/test_rpc.py
  tests/golem/task/test_taskmanager.py
  tests/golem/task/test_tasktester.py
Labels: in progress

#3473 Move clean-docker-vm to `scripts/`
  Installer/Installer_Win/Golem.aip
  scripts/clean-docker-vm.ps1
Labels: in progress

#3453 Implement provider ordering algorithm
  golem/marketplace/__init__.py
  rust/golem/src/lib.rs
  rust/golem/src/marketplace.rs
  tests/golem/marketplace/test_marketplace.py
Labels: in progress

#3479 Make marketplace use the provider selection algorithm
  golem/marketplace/__init__.py
  golem/marketplace/offerpool.py
  golem/ranking/manager/database_manager.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  tests/golem/marketplace/test_marketplace.py
  tests/golem/marketplace/test_offerpool.py
  tests/golem/task/test_concent_logic.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#3430 Send more detailed OS information to monitor
  golem/client.py
  golem/monitor/model/nodemetadatamodel.py
  golem/monitor/test_helper.py
  golem/tools/os_info.py
  requirements.txt
  requirements_to-freeze.txt
  tests/golem/monitor/test_monitor.py
  tests/golem/task/test_taskcomputer.py
  tests/golem/tools/test_os_info.py
Labels: clay, enhancement, in progress, monitor

#3478 Comment-out all the virtualbox things!
  Installer/Installer_Win/Golem.aip
  golem/docker/manager.py
  golemapp.spec
  requirements-win.txt
  requirements-win_to-freeze.txt
  scripts/clean-docker-vm.ps1
Labels: in progress

#3475 Disable benchmark computation on each test
  tests/golem/docker/test_docker_task_thread.py
Labels: in progress

#3484 Reorganize modules
  rust/golem/src/bindings/marketplace.rs
  rust/golem/src/bindings/mod.rs
  rust/golem/src/lib.rs
Labels: in progress

#3487 Put offer_pooling_intervall in config
  golem/appconfig.py
  golem/clientconfigdescriptor.py
  golem/marketplace/__init__.py
  golem/marketplace/offerpool.py
  golem/marketplace/rust.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  tests/golem/marketplace/test_offerpool.py
  tests/golem/marketplace/test_rust.py
Labels: in progress

#3491 0.18.0 fix golemcli account info
  golem/client.py
  golem/interface/client/account.py
  scripts/concent_integration_tests/nodes/provider/mainnet.py
  scripts/concent_integration_tests/nodes/requestor/mainnet.py
  scripts/concent_integration_tests/params.py
  scripts/concent_integration_tests/tests/playbooks/rpc_test.py
  scripts/concent_integration_tests/tests/test_rpc.py
  scripts/concent_integration_tests/tests/test_rpc_mainnet.py
  scripts/concent_integration_tests/tests/test_rpc_no_concent.py
  tests/golem/test_client.py
Labels: brass, in progress

#3492 Append missing 0x to Ethereum addresses in DB
  golem/database/database.py
  golem/database/schemas/022_schema.py
Labels: in progress

#3483 Expose performance.multiplier.* remote procedures
  golem/client.py
  golem/interface/client/environments.py
  golem/node.py
  golem/rpc/mapping/gui.py
  golem/rpc/mapping/rpceventnames.py
  tests/golem/interface/test_client_commands.py
Labels: in progress

#3493 Kill containers on stop
  apps/blender/verification_queue.py
  requirements.txt
  requirements_to-freeze.txt
Labels: in progress

#3452 Fix order of help entries in golemcli
  golem/interface/cli.py
Labels: in progress

#3495 Send golem version in task session's Hello
  golem/task/tasksession.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#3498 Update version to 0.18.1
  Installer/Installer_Win/Golem.aip
Labels: in progress

#3494 Remove persistance from FundsLocker
  golem/client.py
  golem/ethereum/fundslocker.py
  golem/task/rpc.py
  golem/task/taskstate.py
  tests/golem/ethereum/test_fundslocker.py
  tests/golem/test_client.py
Labels: in progress

#3488 Fix create_task_error Exception override
  golem/task/rpc.py
  tests/golem/task/test_rpc.py
Labels: in progress

#3501 B0.18.0 develop
  Installer/Installer_Win/Golem.aip
  apps/blender/verification_queue.py
  golem/client.py
  golem/database/database.py
  golem/database/schemas/022_schema.py
  golem/interface/client/account.py
  golem/task/tasksession.py
  requirements.txt
  requirements_to-freeze.txt
  scripts/concent_integration_tests/nodes/provider/mainnet.py
  scripts/concent_integration_tests/nodes/requestor/mainnet.py
  scripts/concent_integration_tests/params.py
  scripts/concent_integration_tests/tests/playbooks/rpc_test.py
  scripts/concent_integration_tests/tests/test_rpc.py
  scripts/concent_integration_tests/tests/test_rpc_mainnet.py
  scripts/concent_integration_tests/tests/test_rpc_no_concent.py
  tests/golem/task/test_tasksession.py
  tests/golem/test_client.py
Labels: in progress

#3500 Fix dependencies
  apps/core/task/coretask.py
  golem/task/taskbase.py
  golem/task/taskmanager.py
  golem/task/taskserver.py
  tests/apps/blender/task/test_blenderrendertask.py
  tests/apps/core/benchmark/test_benchmarkrunner.py
  tests/golem/task/dummy/task.py
  tests/golem/task/test_taskmanager.py
  tests/golem/task/test_taskserver.py
Labels: in progress

#3502 Remove unnecessary dependency on CompTaskKeeper
  golem/ethereum/incomeskeeper.py
  golem/task/taskserver.py
  tests/golem/task/test_taskserver.py
Labels: in progress

#3503 Don't modify loglevel in special loggers
  golem/core/common.py
Labels: in progress

#3505 B0.18.0
  golem/core/common.py
Labels: in progress

#3506 Download and register new image metrics image
  apps/images.ini
Labels: needs review

#3509 Reference generator refactor
  apps/blender/blender_reference_generator.py
  requirements.txt
  requirements_to-freeze.txt
  tests/apps/blender/verification/test_blender_reference_generator.py
Labels: needs review

#3444 Handle 16 bits images
  .pylintrc
  apps/blender/task/blenderrendertask.py
  apps/rendering/resources/imgrepr.py
  apps/rendering/resources/renderingtaskcollector.py
  apps/rendering/task/framerenderingtask.py
  requirements.txt
  tests/apps/rendering/resources/test_imgrepr.py
  tests/apps/rendering/resources/test_renderingtaskcollector.py
Labels: in progress, needs review
