Repository golemfactory/golem, pull requests merged in 2018-07, with the labels that each got.

#2926 Verificator refactor
  apps/blender/blender_reference_generator.py
  apps/blender/verification_queue.py
  apps/core/benchmark/benchmarkrunner.py
  apps/core/task/coretask.py
  apps/dummy/benchmark/benchmark.py
  apps/dummy/task/verifier.py
  apps/images.ini
  requirements.txt
  requirements_to-freeze.txt
  tests/apps/blender/task/test_blenderrendertask.py
  tests/apps/blender/test_blender_reference_generator.py
  tests/apps/blender/test_data/GolemTask_10001.png
  tests/apps/blender/test_data/GolemTask_10002.png
  tests/apps/blender/test_data/almost_good_image.png
  tests/apps/blender/test_data/bmw.blend
  tests/apps/blender/test_data/very_bad_image.png
  tests/golem/docker/test_docker_luxrender_task.py
Labels: needs review

#2937 hardware config change detection fix
  golem/core/hardware.py
  tests/golem/core/test_hardware_presets.py
Labels: needs review

#2928 Uc5 force payment acceptance tests
  golem/network/concent/client.py
  scripts/concent_integration_tests/base.py
  scripts/concent_integration_tests/force_accept/test_requestor_doesnt_send.py
  scripts/concent_integration_tests/force_payment/__init__.py
  scripts/concent_integration_tests/force_payment/test_payment.py
  tests/golem/network/concent/test_concent_client.py
Labels: needs review

#2958 update cli 'account withdraw' interface
  golem/interface/client/account.py
Labels: needs review

#2960 Cli 'account unlock' can be called only if account is locked
  golem/interface/client/account.py
  golem/node.py
  golem/rpc/mapping/rpcmethodnames.py
  tests/golem/interface/test_client_commands.py
Labels: needs review

#2971 Fix loading payments from DB
  golem/ethereum/paymentprocessor.py
  tests/golem/transactions/ethereum/test_paymentprocessor.py
Labels: needs review

#2949 Added total task cost (GNT) and fee (ETH) to comp.tasks
  golem/client.py
  golem/task/taskstate.py
  golem/transactions/paymentskeeper.py
  golem/transactions/transactionsystem.py
  tests/factories/model.py
  tests/golem/task/test_taskstate.py
  tests/golem/transactions/test_paymentskeeper.py
Labels: enhancement, needs review

#2783 Provide eth fee estimation during task creation
  golem/client.py
  golem/transactions/ethereum/ethereumtransactionsystem.py
  tests/golem/test_client.py
  tests/golem/transactions/ethereum/test_ethereumtransactionsystem.py
Labels: needs review

#3032 Modified task cost & fee information
  apps/core/task/coretask.py
  golem/client.py
  golem/task/taskbase.py
  golem/task/taskmanager.py
  golem/task/taskstate.py
  golem/transactions/paymentskeeper.py
  golem/transactions/transactionsystem.py
  tests/golem/task/test_taskmanager.py
  tests/golem/transactions/test_paymentskeeper.py
Labels: enhancement, payments

#3041 Removing resources methods from Options
  apps/core/task/coretaskstate.py
  tests/apps/core/task/test_coretaskstate.py
Labels: needs review

#3063 2993 concent uc4 acceptance tests 2
  golem/transactions/ethereum/ethereumtransactionsystem.py
  golem/utils.py
  requirements.txt
  requirements_to-freeze.txt
  scripts/concent_acceptance_tests/additional_verification/base.py
  scripts/concent_acceptance_tests/additional_verification/test_verification.py
  scripts/concent_acceptance_tests/base.py
  scripts/concent_acceptance_tests/basic/test_basic.py
  scripts/concent_acceptance_tests/force_accept/test_requestor_doesnt_send.py
  scripts/concent_acceptance_tests/force_payment/test_payment.py
  tests/test_utils.py
Labels: _current, concent

#3071 monitor messages debug added
  golem/monitor/transport/httptransport.py
  tests/golem/core/test_hardware_presets.py
Labels: brass, needs review

#3048 Introduced random disconnects to avoid network partitioning
  golem/network/p2p/p2pservice.py
  tests/golem/network/p2p/test_p2pservice.py
Labels: enhancement, network, optimization

#3058 Adjust mask size by performance rank
  golem/client.py
  golem/network/p2p/p2pservice.py
  golem/network/p2p/performance_stats.py
  golem/task/masking.py
  golem/task/taskserver.py
  tests/golem/network/p2p/test_p2pservice.py
  tests/golem/test_client.py
Labels: enhancement, needs review, network, optimization

#3064 Upgrade to tree clasifier
  apps/images.ini
  requirements.txt
  requirements_to-freeze.txt
  tests/apps/blender/test_blender_reference_generator.py
Labels: needs review

#3088 Don't lock funds when task creation fails
  golem/client.py
Labels: in progress

#3043 Remove TaskComputer dependency from TaskThread classes
  golem/docker/task_thread.py
  golem/task/localcomputer.py
  golem/task/taskcomputer.py
  golem/task/taskthread.py
  tests/golem/docker/test_docker_task_thread.py
  tests/golem/task/test_taskcomputer.py
Labels: needs review

#3089 Change withdraw return type
  golem/client.py
  golem/transactions/ethereum/ethereumtransactionsystem.py
  tests/golem/transactions/ethereum/test_ethereumtransactionsystem.py
Labels: in progress

#3090 Replace callback with deferred
  golem/task/tasksession.py
  golem/transactions/ethereum/ethereumtransactionsystem.py
  tests/golem/task/test_tasksession.py
  tests/golem/transactions/ethereum/test_ethereumtransactionsystem.py
Labels: in progress

#3091 Fix adding payments
  golem/transactions/ethereum/ethereumtransactionsystem.py
  tests/golem/transactions/ethereum/test_ethereumtransactionsystem.py
Labels: in progress

#3100 Different retry logic for Geth requests
  golem/ethereum/node.py
  golem/ethereum/web3/middleware.py
  tests/golem/ethereum/test_ethereum_node.py
  tests/golem/ethereum/web3/test_middleware.py
Labels: in progress

#3092 'last_update_time' won't be updated on restart case
  golem/task/taskstate.py
  tests/golem/task/test_taskstate.py
Labels: _current, brass, in progress, needs review, to be merged

#3078 Use key_id in P2P compare_version
  golem/network/p2p/p2pservice.py
  tests/golem/network/p2p/test_p2pservice.py
  tests/golem/network/p2p/test_peersession.py
Labels: in progress
