Repository golemfactory/golem, pull requests merged in 2018-05, with the labels that each got.

#2733 use `golem-messages` validation for VerdictReportComputedTask inste…
  golem/network/concent/received_handler.py
  requirements.txt
  requirements_to-freeze.txt
  tests/golem/network/concent/test_received_handler.py
Labels: concent

#2755 send `SubtaskResultsVerify` to the Concent if concent is enabled and …
  golem/task/tasksession.py
  tests/golem/task/test_tasksession.py
Labels: concent

#2731 Make batch transfer compatible with sci 1.1.0
  golem/ethereum/paymentprocessor.py
  requirements.txt
  requirements_to-freeze.txt
  tests/golem/transactions/ethereum/test_paymentprocessor.py
Labels: needs review

#2745 Unlock funds for finished task. Remove task with timeouts
  golem/task/taskserver.py
  tests/golem/task/test_taskserver.py
Labels: needs review

#2795 Convert GNT to GNTB asap
  golem/client.py
  golem/ethereum/paymentprocessor.py
  golem/transactions/ethereum/ethereumtransactionsystem.py
  golem/transactions/transactionsystem.py
  tests/golem/task/dummy/runner.py
  tests/golem/test_client.py
  tests/golem/transactions/ethereum/test_ethereumtransactionsystem.py
  tests/golem/transactions/ethereum/test_paymentprocessor.py
Labels: needs review

#2790 Fill WantToComputeTask.concent_enabled
  golem/resource/resourcehandshake.py
  golem/task/tasksession.py
  requirements.txt
  requirements_to-freeze.txt
  tests/golem/task/test_concent_logic.py
  tests/golem/task/test_tasksession.py
Labels: to be merged

#2800 Raise thresholds
  requirements.txt
  requirements_to-freeze.txt
Labels: needs review, to be merged

#2774 Automatic requestor deposit
  apps/core/task/coretask.py
  golem/client.py
  golem/task/taskbase.py
  golem/transactions/ethereum/ethereumtransactionsystem.py
  golem/transactions/ethereum/fundslocker.py
  tests/golem/task/dummy/task.py
  tests/golem/test_client.py
  tests/golem/transactions/ethereum/test_ethereumtransactionsystem.py
  tests/golem/transactions/ethereum/test_fundslocker.py
Labels: needs review

#2807 Pull messages from concent less often
  golem/core/variables.py
  golem/network/concent/client.py
Labels: needs review

#2798 Activate preset async
  golem/client.py
  golem/docker/manager.py
  golem/task/benchmarkmanager.py
  golem/task/taskcomputer.py
  golem/task/taskserver.py
  tests/golem/docker/test_docker_manager.py
  tests/golem/task/test_taskcomputer.py
Labels: needs review, to be merged

#2659 Runtime environment configurations (base)
  golem/config/active.py
  golem/config/environments/__init__.py
  golem/config/environments/mainnet.py
  golem/config/environments/testnet.py
  golem/core/variables.py
  golemapp.py
  tests/golem/config/utils.py
  tests/golem/test_opt_node.py
  tests/test_golemapp.py
Labels: needs review

#2743 Return locks in fundslocker
  golem/client.py
  golem/interface/client/account.py
  tests/golem/interface/test_client_commands.py
  tests/golem/test_client.py
Labels: feedback_needed

#2793 Samplespp
  apps/blender/resources/blenderloganalyser.py
  apps/blender/resources/scenefileeditor.py
  apps/blender/resources/scripts/blendercrop.py.template
  apps/blender/task/blenderrendertask.py
  tests/apps/blender/resources/test_scenefileditor.py
  tests/golem/docker/docker-blender-cycles-task.json
  tests/golem/docker/docker-blender-render-task.json
  tests/golem/docker/test_blender_job.py
Labels: needs review

#2763 React to `AckSubtaskResultsVerify` and upload resources + results
  golem/network/concent/filetransfers.py
  golem/network/concent/helpers.py
  golem/network/concent/received_handler.py
  golem/resource/base/resourceserver.py
  golem/task/taskkeeper.py
  golem/task/tasksession.py
  golem/testutils.py
  scripts/concent_integration_tests/force_accept/test_requestor_doesnt_send.py
  tests/golem/network/concent/test_filetransfers.py
  tests/golem/network/concent/test_helpers.py
  tests/golem/network/concent/test_received_handler.py
  tests/golem/resource/base/test_base_resourceserver.py
  tests/golem/task/test_taskkeeper.py
Labels: concent, needs review

#2804 Get subtasks none - no tuples
  golem/client.py
  golem/interface/client/tasks.py
  golem/task/taskmanager.py
  tests/golem/interface/test_client_commands.py
Labels: needs review

#2812 Runtime environment configurations (continued)
  apps/appsmanager.py
  golem/appconfig.py
  golem/client.py
  golem/config/environments/mainnet.py
  golem/config/environments/testnet.py
  golem/core/simpleenv.py
  golem/ethereum/node.py
  golem/monitor/model/nodemetadatamodel.py
  golem/monitor/monitor.py
  golem/network/p2p/p2pservice.py
  golem/node.py
  golem/task/taskmanager.py
  golem/task/taskserver.py
  golem/transactions/ethereum/ethereumtransactionsystem.py
  golemapp.py
  tests/apps/test_appsmanager.py
  tests/golem/ethereum/test_ethereum_node.py
  tests/golem/monitor/test_monitor.py
  tests/golem/task/test_benchmarkmanager.py
  tests/golem/task/test_taskcomputer.py
  tests/golem/task/test_taskmanager.py
  tests/golem/test_client.py
  tests/golem/test_opt_node.py
  tests/golem/transactions/ethereum/test_ethereumtransactionsystem.py
  tests/test_golemapp.py
Labels: needs review

#2818 Concent integration deposit
  golem/task/tasksession.py
  requirements.txt
  requirements_to-freeze.txt
  scripts/concent_integration_tests/base.py
  scripts/concent_integration_tests/force_accept/test_requestor_doesnt_send.py
  tests/golem/network/concent/test_received_handler.py
Labels: in progress

#2822 2193 react to subtask results settled
  golem/database/database.py
  golem/database/schemas/016_schema.py
  golem/model.py
  golem/network/concent/received_handler.py
  golem/task/taskserver.py
  golem/transactions/incomeskeeper.py
  tests/golem/network/concent/test_received_handler.py
  tests/golem/test_model.py
Labels: concent

#2827 accept_terms: enable_monitor and enable_talkback args
  golem/appconfig.py
  golem/clientconfigdescriptor.py
  golem/interface/client/terms.py
  golem/node.py
  golemapp.py
  tests/golem/interface/test_client_commands.py
  tests/golem/test_opt_node.py
Labels: needs review, to be merged

#2826 Terms updated
  golem/TERMS.html
  golem/terms.py
Labels: to be merged

#2831 Disable sentry logger early (b0.16.0)
  golem/core/common.py
Labels: needs review
