Repository golemfactory/golem, pull requests merged in 2018-03, with the labels that each got.

#2261 React to VerdictReportComputedTask
  golem/network/concent/received_handler.py
  golem/task/taskserver.py
  tests/factories/messages.py
  tests/golem/network/concent/test_received_handler.py
Labels: in progress

#2197 Upgrade web3 and eth libs
  requirements.txt
Labels: needs review

#2273 Merge b0.12.0 to develop
  Installer/Installer_Win/Golem.aip
  apps/blender/task/blendercropper.py
  apps/blender/task/blenderrendertask.py
  apps/blender/task/verifier.py
  apps/core/task/coretask.py
  apps/core/task/verifier.py
  apps/lux/task/luxrendertask.py
  apps/rendering/benchmark/renderingbenchmark.py
  apps/rendering/resources/imgrepr.py
  apps/rendering/resources/renderingtaskcollector.py
  apps/rendering/resources/utils.py
  apps/rendering/task/framerenderingtask.py
  apps/rendering/task/renderingtask.py
  golem/appconfig.py
  golem/client.py
  golem/clientconfigdescriptor.py
  golem/core/async.py
  golem/core/deferred.py
  golem/core/variables.py
  golem/docker/manager.py
  golem/ethereum/paymentprocessor.py
  golem/interface/client/account.py
  golem/interface/client/tasks.py
  golem/network/hyperdrive/client.py
  golem/node.py
  golem/resource/base/resourceserver.py
  golem/rpc/router.py
  golem/task/taskkeeper.py
  golem/task/taskserver.py
  golemapp.py
  golemcli.py
  scripts/pyinstaller/hooks/hook-golem.py
  scripts/pyinstaller/hooks/hook-peewee_migrate.py
  tests/apps/blender/task/test_blendercropper.py
  tests/apps/blender/task/test_blenderrendertask.py
  tests/apps/core/benchmark/test_benchmark.py
  tests/apps/rendering/resources/test_utils.py
  tests/apps/rendering/task/test_renderingtask.py
  tests/golem/core/test_deferred.py
  tests/golem/docker/test_docker_blender_task.py
  tests/golem/docker/test_docker_dummy_task.py
  tests/golem/docker/test_docker_luxrender_task.py
  tests/golem/network/hyperdrive/test_hyperdrive_client.py
  tests/golem/task/test_taskkeeper.py
  tests/golem/task/test_tasksession.py
  tests/golem/test_opt_node.py
  tests/test_clientconfigdescriptor.py
Labels: needs review

#2276 Change super node info to dict
  golem/network/p2p/peersession.py
  tests/golem/network/p2p/test_peersession.py
Labels: needs review

#2282 Small clean up in Eth transaction system
  golem/transactions/ethereum/ethereumtransactionsystem.py
  tests/golem/transactions/ethereum/test_ethereumtransactionsystem.py
Labels: in progress

#2163 Limit the rate of new connections
  golem/network/p2p/p2pservice.py
  golem/network/transport/limiter.py
  golem/network/transport/tcpnetwork.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  requirements.txt
  tests/golem/network/transport/test_limiter.py
  tests/golem/network/transport/test_tcpnetwork.py
Labels: needs review

#2241 Handle Challenge or RandVal messages after disconnecting in Hello
  golem/network/p2p/peersession.py
  golem/network/transport/session.py
  golem/resource/resourcehandshake.py
  golem/task/tasksession.py
  tests/golem/network/p2p/test_peersession.py
Labels: needs review

#2207 Check signature in RemoveTask - nested messages
  golem/network/p2p/p2pservice.py
  golem/network/p2p/peersession.py
  golem/task/taskkeeper.py
  requirements.txt
  tests/golem/network/p2p/test_peersession.py
  tests/golem/task/test_taskkeeper.py
  tests/golem/test_client.py
Labels: needs review

#2212 Update to Blender version 2.79
  apps/blender/blenderenvironment.py
  apps/blender/resources/images/Dockerfile
  apps/images.ini
  tests/apps/blender/resources/stdout.log_for_test
  tests/apps/blender/task/test_blender_verification.py
  tests/golem/docker/docker-blender-cycles-task.json
  tests/golem/docker/docker-blender-render-task.json
  tests/golem/docker/test_blender_job.py
  tests/golem/docker/test_docker_blender_task.py
  tests/golem/docker/test_docker_environment.py
  tests/imunes/Dockerfile.blender
Labels: needs review

#2288 Support multiple databases
  golem/client.py
  golem/database/database.py
  golem/database/migration/__init__.py
  golem/database/migration/create.py
  golem/database/migration/migrate.py
  golem/model.py
  golem/testutils.py
  tests/golem/database/test_database.py
  tests/golem/database/test_migration.py
Labels: needs review

#2275 React to force report computed task
  golem/network/concent/exceptions.py
  golem/network/concent/helpers.py
  golem/network/concent/received_handler.py
  golem/task/taskkeeper.py
  golem/task/tasksession.py
  tests/golem/docker/test_docker_blender_task.py
  tests/golem/docker/test_docker_dummy_task.py
  tests/golem/docker/test_docker_luxrender_task.py
  tests/golem/network/concent/test_received_handler.py
  tests/golem/network/p2p/test_peersession.py
  tests/golem/resource/base/common.py
  tests/golem/resource/test_resourcehandshake.py
  tests/golem/task/test_concent_logic.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#2260 Don't duplicate in ComputeTaskDef parameters from TaskHeader
  apps/core/task/coretask.py
  golem/task/taskbase.py
  golem/task/taskcomputer.py
  golem/task/taskkeeper.py
  golem/task/taskmanager.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  requirements.txt
  tests/apps/blender/task/test_blender_verification.py
  tests/apps/core/task/test_coretask.py
  tests/factories/messages.py
  tests/golem/docker/test_docker_blender_task.py
  tests/golem/docker/test_docker_dummy_task.py
  tests/golem/docker/test_docker_luxrender_task.py
  tests/golem/task/dummy/task.py
  tests/golem/task/test_taskbase.py
  tests/golem/task/test_taskcomputer.py
  tests/golem/task/test_taskkeeper.py
  tests/golem/task/test_taskmanager.py
  tests/golem/task/test_taskserver.py
  tests/golem/task/test_tasksession.py
Labels: in progress, needs review

#2284 Add subtask status verifying
  apps/core/task/coretask.py
  apps/rendering/task/framerenderingtask.py
  apps/rendering/task/renderingtask.py
  golem/task/taskmanager.py
  golem/task/taskstate.py
Labels: needs review

#2309 Remove broken pickled tasks in case of KeyError
  golem/task/taskkeeper.py
  golem/task/taskmanager.py
Labels: needs review

#2302 Replace GNTW with GNTB
  golem/core/variables.py
  golem/ethereum/gntconverter.py
  golem/ethereum/paymentprocessor.py
  golem/monitor/model/balancemodel.py
  golem/monitor/monitor.py
  requirements.txt
  tests/golem/ethereum/test_gntconverter.py
  tests/golem/monitor/model/test_balancemodel.py
  tests/golem/transactions/ethereum/test_paymentprocessor.py
Labels: to be merged

#2281 do not regenerate keys + support for ^C (SIGINT) @ key generation + en-/decrypt clean-up
  golem/core/keysauth.py
  golem/core/processmonitor.py
  golem/network/transport/tcpnetwork.py
  golem/node.py
  golem/resource/base/resourceserver.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  golem/testutils.py
  tests/golem/core/test_keysauth.py
  tests/golem/core/test_processmonitor.py
  tests/golem/network/transport/test_tcpnetwork.py
  tests/golem/resource/base/test_base_resourceserver.py
  tests/golem/task/dummy/runner.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#2313 Fixed version of pycryptodome (3.4.11)
  requirements.txt
Labels: needs review

#2321 Updated version and ProductCode for 0.13.0
  Installer/Installer_Win/Golem.aip
Labels: to be merged

#2257 Add some time tolerance for checking deadline.
  golem/task/taskkeeper.py
Labels: needs review

#2328 AppConfig.change_config() in Client.change_config()
  golem/client.py
  golem/node.py
  golemapp.py
  tests/golem/docker/test_docker_blender_task.py
  tests/golem/docker/test_docker_dummy_task.py
  tests/golem/docker/test_docker_luxrender_task.py
  tests/golem/resource/base/common.py
  tests/golem/task/dummy/runner.py
  tests/golem/test_client.py
  tests/golem/test_opt_node.py
Labels: bug, needs review

#2335 Refactor SocketAddress list generation
  golem/appconfig.py
  golem/clientconfigdescriptor.py
  golem/core/variables.py
  golem/environments/environment.py
  golem/network/p2p/p2pservice.py
  golem/network/transport/limiter.py
  golem/network/transport/tcpserver.py
  golem/task/taskserver.py
  tests/golem/network/p2p/test_p2pservice.py
  tests/golem/network/transport/test_tcpserver.py
  tests/golem/task/dummy/runner.py
  tests/golem/task/test_taskserver.py
Labels: needs review

#2305 react to `ForceReportComputedTaskResponse`
  .pylintrc
  golem/network/concent/handlers_library.py
  golem/network/concent/received_handler.py
  golem/network/history.py
  golem/task/tasksession.py
  requirements.txt
  tests/factories/messages.py
  tests/golem/network/concent/test_received_handler.py
  tests/golem/network/test_history.py
  tests/golem/task/test_tasksession.py
Labels: needs review

#2340 Quickfix for sorting "port_statuses" in TaskHeader.task_owner
  golem/core/variables.py
  golem/task/taskbase.py
Labels: needs review

#2331 network/transport: Make it harder to use incorrectly
  golem/core/types.py
  golem/network/p2p/p2pservice.py
  golem/network/transport/network.py
  golem/network/transport/tcpnetwork.py
  golem/network/transport/tcpnetwork_helpers.py
  golem/network/transport/tcpserver.py
  tests/golem/network/p2p/test_p2pservice.py
  tests/golem/network/transport/test_network.py
  tests/golem/network/transport/test_tcpnetwork.py
  tests/golem/network/transport/test_tcpserver.py
Labels: needs review

#2311 Keep information in CompTaskKeeper longer
  golem/core/variables.py
  golem/task/taskkeeper.py
  tests/golem/task/test_taskkeeper.py
Labels: needs review

#2357 Merge b0.13.0 to develop
  Installer/Installer_Win/Golem.aip
  apps/core/task/coretask.py
  apps/core/task/verifier.py
  golem/client.py
  golem/core/keysauth.py
  golem/core/variables.py
  golem/environments/environment.py
  golem/network/p2p/p2pservice.py
  golem/network/transport/limiter.py
  golem/network/transport/tcpserver.py
  golem/node.py
  golem/task/taskbase.py
  golem/task/taskserver.py
  golem/verification/verifier.py
  golemapp.py
  tests/apps/blender/task/test_blenderrendertask.py
  tests/golem/docker/test_docker_blender_task.py
  tests/golem/docker/test_docker_dummy_task.py
  tests/golem/docker/test_docker_luxrender_task.py
  tests/golem/network/p2p/test_p2pservice.py
  tests/golem/network/transport/test_tcpserver.py
  tests/golem/resource/base/common.py
  tests/golem/task/dummy/runner.py
  tests/golem/task/test_taskserver.py
  tests/golem/test_client.py
  tests/golem/test_opt_node.py
  tests/golem/verification/test_verifier.py
Labels: needs review

#2308 Added more logs in client.py
  golem/client.py
  tests/golem/test_client.py
Labels: needs review

#2369 Optional task_id and subtask_id in message_to_model
  golem/network/history.py
Labels: needs review

#2371 Introduce --concent/--noconcent flag.
  golem/client.py
  golem/network/concent/client.py
  golem/node.py
  golem/task/tasksession.py
  golemapp.py
  tests/golem/task/test_tasksession.py
  tests/golem/test_opt_node.py
Labels: needs review

#2342 ForceSubtaskResults
  golem/network/concent/client.py
  golem/task/tasksession.py
  requirements.txt
  tests/golem/network/concent/test_concent_client.py
  tests/golem/task/test_tasksession.py
Labels: needs review

#2355 RPC call to check if golem is on mainnet
  golem/client.py
  golem/rpc/mapping/rpcmethodnames.py
  tests/golem/test_client.py
Labels: needs review

#2370 remove imunes tests
  tests/imunes/Dockerfile.blender
  tests/imunes/Dockerfile.core
  tests/imunes/__init__.py
  tests/imunes/build-images.sh
  tests/imunes/imunes.py
  tests/imunes/local.imn
  tests/imunes/nat1.imn
  tests/imunes/nat12.imn
  tests/imunes/node.py
  tests/imunes/test_imunes_node.py
Labels: needs review

#2372 Query subtask by (sender_id, subtask_id)
  golem/task/taskserver.py
  golem/task/tasksession.py
  golem/transactions/incomeskeeper.py
  tests/golem/task/test_tasksession.py
  tests/golem/transactions/test_incomeskeeper.py
Labels: needs review

#2383 React to ForceSubtaskResultsResponse as Provider
  golem/network/concent/received_handler.py
  tests/factories/messages.py
  tests/golem/network/concent/test_received_handler.py
Labels: in progress

#2401 golem_sci hook for pyinstaller
  scripts/pyinstaller/hooks/hook-golem_sci.py
Labels: needs review

#2336 Reconnect to remote geth RPC nodes
  golem/ethereum/node.py
  golem/ethereum/web3/__init__.py
  golem/ethereum/web3/middleware.py
  golem/ethereum/web3/providers.py
  tests/golem/ethereum/test_ethereum_node.py
  tests/golem/ethereum/web3/__init__.py
  tests/golem/ethereum/web3/test_middleware.py
Labels: needs review

#2416 Block multiple restart of a task
  golem/client.py
  golem/task/taskmanager.py
  tests/golem/task/test_taskmanager.py
Labels: needs review

#2429 Fix: install reactor before raven does
  golemapp.py
  golemcli.py
Labels: bug, important, needs review

#2337 Lock funds
  golem/client.py
  golem/task/taskserver.py
  golem/transactions/ethereum/fundslocker.py
  tests/golem/task/dummy/runner.py
  tests/golem/test_client.py
  tests/golem/transactions/ethereum/test_fundslocker.py
Labels: needs review

#2293 Check gnt
  golem/client.py
  golem/task/taskserver.py
  golem/transactions/ethereum/ethereumtransactionsystem.py
  golem/transactions/ethereum/exceptions.py
  golem/transactions/ethereum/fundslocker.py
  tests/golem/task/dummy/runner.py
  tests/golem/task/dummy/task.py
  tests/golem/test_client.py
  tests/golem/transactions/ethereum/test_exceptions.py
  tests/golem/transactions/ethereum/test_fundslocker.py
  tests/golem/transactions/ethereum/test_paymentprocessor.py
Labels: needs review

#2418 Retry sql operation with a timeout
  golem/database/database.py
Labels: needs review

#2391 Disabled sending payments and balance to monitor
  golem/client.py
  golem/monitor/monitor.py
  tests/golem/monitor/model/test_balancemodel.py
  tests/golem/monitor/model/test_paymentmodel.py
Labels: monitor, needs review

#2435 is_mainnet RPC call v2
  golem/client.py
  golem/node.py
  golem/rpc/mapping/rpcmethodnames.py
  tests/golem/test_client.py
  tests/golem/test_opt_node.py
Labels: needs review

#2373 Golem terms of use
  apps/rendering/resources/renderingtaskcollector.py
  golem/TERMS.html
  golem/client.py
  golem/database/database.py
  golem/ethereum/paymentprocessor.py
  golem/interface/client/terms.py
  golem/node.py
  golem/rpc/mapping/rpcmethodnames.py
  golemcli.py
  requirements.txt
  scripts/pyinstaller/hooks/hook-golem.py
  setup.py
  tests/golem/interface/test_client_commands.py
  tests/golem/resource/base/common.py
  tests/golem/task/dummy/runner.py
  tests/golem/test_client.py
  tests/golem/test_opt_node.py
Labels: needs review

#2390 WebSocket certificate generation with "golemapp --generate-rpc-cert"
  golemapp.py
  tests/test_golemapp.py
Labels: needs review

#2386 WebSocket encryption
  golem/interface/websockets.py
  golem/node.py
  golem/rpc/cert.py
  golem/rpc/common.py
  golem/rpc/router.py
  golem/rpc/session.py
  golemapp.py
  golemcli.py
  loggingconfig.py
  tests/golem/rpc/test_cert.py
  tests/golem/rpc/test_router.py
  tests/golem/rpc/test_session.py
  tests/golem/test_opt_node.py
  tests/test_golemapp.py
Labels: needs review

#2334 (sub)task_id uniqueness
  apps/blender/benchmark/benchmark.py
  apps/blender/task/blenderrendertask.py
  apps/core/task/coretask.py
  apps/dummy/benchmark/benchmark.py
  apps/dummy/task/dummytask.py
  apps/lux/benchmark/benchmark.py
  apps/lux/task/luxrendertask.py
  apps/rendering/benchmark/renderingbenchmark.py
  golem/interface/client/tasks.py
  golem/task/taskbase.py
  golem/task/taskmanager.py
  tests/apps/blender/task/test_blenderrendertask.py
  tests/apps/core/task/test_coretask.py
  tests/apps/dummy/benchmark/test_dummybenchmark.py
  tests/apps/dummy/task/test_dummytask.py
  tests/apps/dummy/task/test_dummyverifier.py
  tests/apps/lux/benchmark/test_luxbenchmark.py
  tests/apps/lux/task/test_luxrendertask.py
  tests/apps/rendering/task/test_renderingtask.py
  tests/golem/interface/test_client_commands.py
  tests/golem/test_client.py
Labels: needs review

#2396 Compositing always disabled
  apps/blender/task/blenderrendertask.py
  golem/docker/task_thread.py
  tests/apps/blender/task/test_blenderrendertask.py
Labels: needs review

#2463 CLI account command fix
  golem/interface/client/account.py
Labels: needs review

#2473 Fix startup issues
  golem/node.py
  golem/report.py
  golem/rpc/session.py
Labels: needs review, to be merged

#2452 Use proper addresses in HyperdriveResourceOptions
  golem/client.py
  golem/network/hyperdrive/client.py
  golem/network/p2p/peersession.py
  golem/resource/client.py
  golem/resource/hyperdrive/peermanager.py
  golem/resource/hyperdrive/resourcesmanager.py
  golem/resource/resourcehandshake.py
  golem/task/server/resources.py
  golem/task/tasksession.py
  tests/golem/network/hyperdrive/test_hyperdrive_client.py
  tests/golem/network/p2p/test_peersession.py
  tests/golem/resource/base/common.py
  tests/golem/resource/hyperdrive/test_hyperdrive_peermanager.py
  tests/golem/resource/test_resourcehandshake.py
  tests/golem/task/test_taskserver.py
Labels: needs review

#2469 Remove process service
  golem/core/prochelper.py
  golem/core/simpleenv.py
  tests/golem/core/test_simpleenv.py
Labels: needs review

#2474 Generate lower bit DHKE params on Windows if forward_secrecy was not requested
  golem/rpc/cert.py
  tests/golem/rpc/test_cert.py
Labels: needs review, to be merged

#2434 Todo comments
  apps/core/task/coretask.py
  apps/dummy/benchmark/benchmark.py
  apps/dummy/resources/scripts/docker_dummytask.py
  apps/dummy/task/dummytask.py
  apps/dummy/task/dummytaskstate.py
  apps/lux/task/luxrendertask.py
  golem/client.py
  golem/docker/task_thread.py
  golem/ethereum/paymentprocessor.py
  golem/model.py
  golem/monitor/model/modelbase.py
  golem/network/p2p/p2pservice.py
  golem/network/transport/session.py
  golem/network/transport/tcpserver.py
  golem/task/taskbase.py
  golem/task/taskkeeper.py
  golem/task/taskmanager.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  golem/task/tasktester.py
  golem/transactions/incomeskeeper.py
  setup_util/setup_commons.py
  setup_util/taskcollector_builder.py
  tests/apps/dummy/task/test_dummytask.py
  tests/golem/docker/test_docker_dummy_task.py
  tests/golem/docker/test_docker_luxrender_task.py
  tests/golem/network/transport/test_address_parsing.py
  tests/golem/test_client.py
  tests/golem/test_opt_node.py
Labels: cleanup, needs review

#2458 Alternative response for create task
  golem/client.py
  tests/golem/test_client.py
Labels: needs review, to be merged

#2490 Refresh geth addresses on failure
  golem/ethereum/node.py
  tests/golem/ethereum/test_ethereum_node.py
Labels: needs review

#2492 Fix a key error in TaskManager.get_task_dict
  golem/task/taskmanager.py
Labels: needs review

#2417 Connect to mainnet seeds and geths
  golem/client.py
  golem/ethereum/node.py
  golem/network/p2p/p2pservice.py
  tests/golem/ethereum/test_ethereum_node.py
Labels: in progress

#2487 Unlock funds after task is deleted
  apps/blender/task/blendercropper.py
  apps/blender/task/verifier.py
  golem/client.py
  golem/ethereum/node.py
  golem/task/taskmanager.py
  golem/transactions/ethereum/fundslocker.py
  requirements.txt
  tests/golem/ethereum/test_ethereum_node.py
  tests/golem/test_client.py
  tests/golem/transactions/ethereum/test_fundslocker.py
Labels: needs review

#2507 Merge b0.14.0 to develop
  Installer/Installer_Win/Golem.aip
Labels: needs review

#2502 Support timeouts in _DenyAcl
  golem/resource/resourcehandshake.py
  golem/task/acl.py
  tests/golem/task/test_acl.py
Labels: needs review

#2498 Removed `legacy` flag (#2450)
  apps/core/task/coretask.py
  apps/core/task/coretaskstate.py
  apps/rendering/task/renderingtask.py
  tests/apps/core/task/test_coretask.py
  tests/apps/rendering/task/test_renderingtask.py
Labels: cleanup, needs review

#2509 docker logs level WARN -> INFO
  loggingconfig.py
Labels: to be merged

#2512 Pause verification queue
  apps/core/task/verifier.py
  golem/client.py
  golem/task/taskcomputer.py
  golem/task/taskserver.py
  loggingconfig.py
  tests/golem/task/test_taskserver.py
  tests/golem/test_client.py
Labels: needs review

#2516 Trigger GNT-GNTB conversion
  golem/ethereum/paymentprocessor.py
Labels: to be merged

#2514 Dont change working dir when packing resources
  golem/resource/resource.py
  golem/task/localcomputer.py
Labels: to be merged

#2503 Return if nonce was shared after handshake failure (issue 2410)
  golem/resource/resourcehandshake.py
  tests/golem/resource/test_resourcehandshake.py
Labels: needs review

#2495 Remove PendingConnectionsServer._is_address_valid quickfix
  golem/core/hostaddress.py
  golem/network/transport/tcpnetwork_helpers.py
  golem/network/transport/tcpserver.py
  tests/golem/core/test_hostaddress.py
Labels: needs review

#2466 Monitor for testnet and mainnet (golem-monitor #35)
  golem/client.py
  golem/monitor/model/nodemetadatamodel.py
  golem/monitor/test_helper.py
  tests/golem/monitor/test_monitor.py
  tests/golem/task/test_taskcomputer.py
Labels: needs review

#2510 Include lock funds in withdraw function
  golem/client.py
  golem/transactions/ethereum/ethereumtransactionsystem.py
  tests/golem/test_client.py
  tests/golem/transactions/ethereum/test_ethereumtransactionsystem.py
Labels: needs review

#2530 Update SCI to include GNT conversion fix
  requirements.txt
  tests/golem/ethereum/test_paymentprocessor_eth.py
  tests/golem/transactions/ethereum/test_ethereumtransactionsystem.py
  tests/golem/transactions/ethereum/test_paymentprocessor.py
Labels: to be merged

#2534 Filter None in get_subtasks function
  apps/rendering/task/framerenderingtask.py
  tests/apps/rendering/task/test_framerenderingtask.py
Labels: needs review, to be merged

#2541 Add an RPC call for gas cost estimation for withdrawals
  golem/client.py
  golem/rpc/mapping/rpcmethodnames.py
  golem/transactions/ethereum/ethereumtransactionsystem.py
  requirements.txt
  tests/golem/test_client.py
  tests/golem/transactions/ethereum/test_ethereumtransactionsystem.py
Labels: to be merged

#2531 Develop concent update
  golem/client.py
  golem/monitor/model/nodemetadatamodel.py
  golem/monitor/test_helper.py
  golem/transactions/ethereum/ethereumtransactionsystem.py
  tests/golem/monitor/test_monitor.py
  tests/golem/task/test_taskcomputer.py
  tests/golem/test_client.py
  tests/golem/transactions/ethereum/test_ethereumtransactionsystem.py
Labels: to be merged
