Repository golemfactory/golem, pull requests merged in 2018-12, with the labels that each got.

#3619 Users without Hyper-V can install Golem
  Installer/Installer_Win/Golem.aip
  scripts/prepare-docker-for-windows.ps1
Labels: clay, docker, in progress, windows

#3622 Handle create / start / update config failure in docker
  golem/docker/hypervisor/__init__.py
  golem/docker/hypervisor/docker_machine.py
  golem/docker/hypervisor/hyperv.py
  golem/docker/manager.py
  golem/node.py
Labels: in progress

#3627 Revert "Users without Hyper-V can install Golem"
  Installer/Installer_Win/Golem.aip
  scripts/prepare-docker-for-windows.ps1
Labels: in progress

#3637 actually fix the deferred calls in the integration tests
  scripts/node_integration_tests/rpc/client.py
Labels: in progress

#3639 B0.18.0
  golem/task/taskmanager.py
  golem/task/taskserver.py
  scripts/node_integration_tests/rpc/client.py
Labels: in progress

#3636 Remove end_task param
  apps/blender/task/blenderrendertask.py
  apps/core/task/coretask.py
  apps/rendering/benchmark/renderingbenchmark.py
  apps/rendering/task/framerenderingtask.py
  apps/rendering/task/renderingtask.py
  golem/manager/nodestatesnapshot.py
  scripts/concent_acceptance_tests/additional_verification/base.py
  tests/apps/blender/task/test_blenderrendertask.py
  tests/apps/blender/verification/test_verificator_integration.py
  tests/apps/core/task/test_coretask.py
  tests/apps/rendering/task/test_framerenderingtask.py
  tests/apps/rendering/task/test_renderingtask.py
  tests/golem/docker/test_blender_job.py
  tests/golem/manager/test_nodestatesnapshot.py
  tests/golem/task/test_taskmanager.py
  tests/golem/test_client.py
Labels: in progress

#3638 Remove short description
  apps/core/task/coretask.py
  apps/dummy/task/dummytask.py
  apps/rendering/task/renderingtask.py
  golem/manager/nodestatesnapshot.py
  golem/task/taskbase.py
  golem/task/taskmanager.py
  golem/task/taskstate.py
  golem/task/tasktester.py
  tests/apps/blender/verification/test_verificator_integration.py
  tests/apps/core/benchmark/test_benchmarkrunner.py
  tests/apps/core/task/test_coretask.py
  tests/golem/manager/test_nodestatesnapshot.py
  tests/golem/resource/test_resource.py
  tests/golem/task/dummy/task.py
  tests/golem/task/test_taskcomputer.py
  tests/golem/task/test_taskmanager.py
  tests/golem/task/test_taskstate.py
Labels: in progress

#3642 Updated no-WTCT provider to check for TTC received
  scripts/node_integration_tests/nodes/provider/no_second_wtct.py
  scripts/node_integration_tests/nodes/provider/no_wtct_after_ttc.py
  scripts/node_integration_tests/playbooks/golem/task_timeout.py
Labels: in progress

#3635 Docker Toolbox
  Installer/Installer_Win/Golem.aip
  scripts/prepare-docker-for-windows.ps1
Labels: clay, docker, in progress, windows

#3613 Remove last_checking variable from TaskHeader
  golem/task/taskarchiver.py
  golem/task/taskbase.py
  golem/task/taskkeeper.py
  tests/golem/task/test_taskarchiver.py
  tests/golem/task/test_taskbase.py
  tests/golem/task/test_taskkeeper.py
Labels: in progress

#3644 Provider no wtct after ttc
  scripts/node_integration_tests/nodes/provider/no_second_wtct.py
  scripts/node_integration_tests/nodes/provider/no_wtct_after_ttc.py
  scripts/node_integration_tests/playbooks/golem/task_timeout.py
Labels: in progress

#3628 DockerForWindows - Mem check on start_vm
  golem/docker/hypervisor/hyperv.py
Labels: in progress

#3646 Initialize hardware presets in Node.start
  golem/client.py
  golem/node.py
  tests/golem/task/dummy/runner.py
  tests/golem/test_client.py
Labels: in progress

#3651 Update golem-hyperdrive ownership changes
  Installer/Installer_Linux/install.sh
  appveyor.yml
Labels: needs review

#3645 Check if SMB port (445) is not blocked by firewall
  golem/docker/commands/docker_machine.py
  golem/docker/hypervisor/hyperv.py
  tests/golem/docker/test_hyperv.py
Labels: clay, docker, enhancement, in progress, windows

#3647 Empty process' working sets to try and free some memory
  .gitignore
  golem/docker/hypervisor/hyperv.py
  golem/os/__init__.py
  rust/golem/Cargo.lock
  rust/golem/Cargo.toml
  rust/golem/src/lib.rs
  rust/golem/src/os/error.rs
  rust/golem/src/os/mod.rs
  rust/golem/src/os/windows.rs
  setup.py
Labels: clay, docker, enhancement, in progress, windows

#3649 Pause p2p and task sessions until node is ready (#3378)
  golem/client.py
Labels: in progress

#3654 0.18 to develop
  golem/client.py
Labels: in progress

#3652 Split golem.core.hardware
  golem/client.py
  golem/config/presets.py
  golem/docker/config.py
  golem/hardware/__init__.py
  golem/hardware/presets.py
  golem/node.py
  tests/golem/config/test_presets.py
  tests/golem/hardware/__init__.py
  tests/golem/hardware/test_presets.py
  tests/golem/task/dummy/runner.py
  tests/golem/test_client.py
Labels: docker, needs review

#3641 Created RPC endpoint for current gas price
  golem/client.py
  golem/ethereum/transactionsystem.py
  tests/golem/ethereum/test_transactionsystem.py
  tests/golem/test_client.py
Labels: in progress

#3657 Made it possible to run prepare-docker without Advanced installer
  scripts/prepare-docker-for-windows.ps1
Labels: clay, docker, in progress

#3631 Show wget progress bars in linux installer
  Installer/Installer_Linux/install.sh
Labels: in progress

#3658 Move hardware mixin to node
  golem/client.py
  golem/hardware/presets.py
  golem/node.py
  tests/golem/config/test_presets.py
  tests/golem/test_client.py
  tests/golem/test_opt_node.py
Labels: clay, docker, in progress

#3656 Memory padding
  golem/appconfig.py
  golem/docker/config.py
  golem/docker/hypervisor/hyperv.py
  golem/hardware/__init__.py
  golem/hardware/presets.py
  tests/golem/hardware/test_hardware.py
  tests/golem/hardware/test_presets.py
  tests/golem/test_client.py
Labels: clay, docker, in progress

#3662 Missing memory padding
  golem/docker/hypervisor/__init__.py
  golem/docker/hypervisor/hyperv.py
  golem/docker/manager.py
  golem/hardware/__init__.py
  golem/hardware/presets.py
  tests/golem/docker/test_docker_manager.py
  tests/golem/resource/base/common.py
Labels: clay, docker, in progress, needs review

#3666 Set max memory to 90% for hyperv
  golem/docker/hypervisor/hyperv.py
Labels: in progress

#3659 Fix #3592 (#3597)
  apps/blender/verification_task.py
  requirements.txt
  requirements_to-freeze.txt
Labels: in progress

#3668 Harden restore_tasks
  golem/task/taskmanager.py
Labels: in progress

#3669 Fixed linter and add missing mock
  golem/client.py
  golem/docker/hypervisor/hyperv.py
  tests/golem/docker/test_hyperv.py
Labels: in progress

#3640 Update concent acceptance test after sra update
  scripts/concent_acceptance_tests/force_accept/test_requestor_doesnt_send.py
  scripts/concent_acceptance_tests/force_payment/test_payment.py
Labels: in progress

#3670 0.18 to develop
  apps/core/verification_task.py
  golem/task/taskmanager.py
Labels: in progress

#3665 [Concent] Soft-enable/disable toggle through RPC
  golem/client.py
  golem/interface/client/concent.py
  golem/interface/command.py
  golem/network/concent/client.py
  golem/network/concent/soft_switch.py
  golem/task/rpc.py
  golem/task/tasksession.py
  requirements-lint.txt
  requirements-test.txt
  tests/golem/network/concent/test_concent_client.py
  tests/golem/network/concent/test_soft_switch.py
  tests/golem/task/test_rpc.py
  tests/golem/test_client.py
Labels: in progress

#3671 Update version to 0.18.3
  Installer/Installer_Win/Golem.aip
Labels: in progress

#3673 Removed union, it is no longer required for the linter.
  golem/docker/hypervisor/hyperv.py
  golem/docker/hypervisor/xhyve.py
Labels: in progress

#3672 Removed default of concent_variant from client init params
  golem/client.py
  tests/golem/resource/base/common.py
  tests/golem/task/dummy/runner.py
  tests/golem/test_client.py
Labels: in progress

#3675 Don't block node when Concent Term aren't accepted
  golem/node.py
  tests/golem/task/test_taskcomputer.py
Labels: in progress

#3677 Bump Golem Messages to 2.20
  requirements.txt
  requirements_to-freeze.txt
Labels: in progress

#3680 cleanup remaining fixed_header
  golem/task/taskcomputer.py
Labels: bug, in progress

#3686 B0.18.3
  Installer/Installer_Win/Golem.aip
  apps/blender/verification_task.py
  requirements.txt
  requirements_to-freeze.txt
Labels: in progress

#3648 Speed up Golem startup
  Installer/Installer_Win/Golem.aip
  golem/docker/hypervisor/__init__.py
  golem/docker/hypervisor/docker_machine.py
  golem/docker/hypervisor/hyperv.py
  golem/docker/smbshare.py
  scripts/docker/clean-docker-vm.ps1
  scripts/docker/create-share.ps1
  scripts/docker/get-default-vswitch.ps1
  scripts/docker/prepare-docker-for-windows.ps1
  scripts/docker/start-hyperv-docker-vm.ps1
  scripts/pyinstaller/hooks/hook-golem.py
  tests/golem/docker/test_hyperv.py
Labels: clay, docker, enhancement, windows

#3674 Fixed SMB port check to work with debug option
  golem/docker/hypervisor/hyperv.py
  tests/golem/docker/test_hyperv.py
Labels: clay, docker, in progress, windows

#3687 + reconnect nodes in case the initial connection attempt doesn't resu…
  scripts/node_integration_tests/playbooks/base.py
Labels: in progress

#3689 B0.18.0 develop
  Installer/Installer_Win/Golem.aip
  scripts/node_integration_tests/playbooks/base.py
Labels: in progress

#3676 DictSerializer aka DictCoder learns about p2p.Node
  golem/core/simpleserializer.py
  tests/golem/test_client.py
Labels: in progress

#3682 when creating task with concent enabled, make sure deposit is locked
  golem/ethereum/transactionsystem.py
  tests/golem/ethereum/test_transactionsystem.py
Labels: _current, brass, in progress

#3690 Fixed HyperVHypervisor.restore_vm()
  golem/docker/hypervisor/hyperv.py
  tests/golem/docker/test_hyperv.py
Labels: bug, clay, docker, in progress, needs review, windows

#3693 Prevent unnecessary Docker VM restarts during startup
  golem/docker/manager.py
  golem/node.py
Labels: in progress, needs review

#3482 Marketplace
  golem/appconfig.py
  golem/client.py
  golem/clientconfigdescriptor.py
  golem/core/statskeeper.py
  golem/database/database.py
  golem/database/schemas/023_schema.py
  golem/ethereum/incomeskeeper.py
  golem/ethereum/paymentprocessor.py
  golem/marketplace/__init__.py
  golem/marketplace/offerpool.py
  golem/marketplace/rust.py
  golem/model.py
  golem/monitor/model/statssnapshotmodel.py
  golem/monitor/model/taskcomputersnapshotmodel.py
  golem/monitor/monitor.py
  golem/ranking/__init__.py
  golem/ranking/manager/database_manager.py
  golem/resource/resourcehandshake.py
  golem/task/taskcomputer.py
  golem/task/taskkeeper.py
  golem/task/taskmanager.py
  golem/task/taskproviderstats.py
  golem/task/taskrequestorstats.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  golem/task/taskstate.py
  golem/task/timer.py
  luxrender-output.exr
  rust/golem/src/bindings/marketplace.rs
  rust/golem/src/bindings/mod.rs
  rust/golem/src/lib.rs
  rust/golem/src/marketplace.rs
  tests/golem/ethereum/test_paymentprocessor.py
  tests/golem/marketplace/test_marketplace.py
  tests/golem/marketplace/test_offerpool.py
  tests/golem/marketplace/test_rust.py
  tests/golem/monitor/model/test_statssnapshotmodel.py
  tests/golem/monitor/model/test_taskcomputersnapshotmodel.py
  tests/golem/resource/test_resourcehandshake.py
  tests/golem/task/test_concent_logic.py
  tests/golem/task/test_taskcomputer.py
  tests/golem/task/test_taskkeeper.py
  tests/golem/task/test_taskmanager.py
  tests/golem/task/test_taskproviderstats.py
  tests/golem/task/test_taskrequestorstats.py
  tests/golem/task/test_taskserver.py
  tests/golem/task/test_tasksession.py
  tests/golem/task/test_timer.py
  tests/golem/test_client.py
  tests/golem/test_model.py
Labels: in progress

#3694 B0.19
  golem/appconfig.py
  golem/client.py
  golem/clientconfigdescriptor.py
  golem/core/simpleconfig.py
  golem/network/p2p/p2pservice.py
  golem/network/p2p/peersession.py
  golem/network/transport/tcpnetwork.py
  golem/network/transport/tcpserver.py
  requirements.txt
  requirements_to-freeze.txt
  tests/golem/network/p2p/test_p2pservice.py
  tests/golem/network/p2p/test_peersession.py
  tests/golem/task/dummy/task.py
  tests/golem/test_appconfig.py
Labels: in progress

#3683 update urrlib3 and requests
  requirements-lint.txt
  requirements-test.txt
  requirements.txt
  requirements_to-freeze.txt
Labels: needs review
