Repository golemfactory/golem, pull requests merged in 2018-08, with the labels that each got.

#3113 Merge 0.17.0
  golem/client.py
  golem/ethereum/node.py
  golem/ethereum/web3/middleware.py
  golem/network/p2p/p2pservice.py
  golem/task/taskstate.py
  tests/golem/ethereum/test_ethereum_node.py
  tests/golem/ethereum/web3/test_middleware.py
  tests/golem/network/p2p/test_p2pservice.py
  tests/golem/network/p2p/test_peersession.py
  tests/golem/task/test_taskstate.py
Labels: in progress

#3114 Concent Integration tests wait for the faucet instead of failing right away
  scripts/concent_acceptance_tests/base.py
Labels: in progress

#3115 Concent integration tests retry until timeout
  scripts/concent_acceptance_tests/base.py
Labels: in progress

#3103 + additional log to verification queue
  apps/blender/verification_queue.py
Labels: in progress

#3098 Transaction System datadir
  golem/client.py
  golem/transactions/ethereum/ethereumtransactionsystem.py
  tests/golem/transactions/ethereum/test_ethereumtransactionsystem.py
Labels: in progress

#3131 Speed up tests
  requirements.txt
  requirements_to-freeze.txt
  tests/apps/blender/test_blender_reference_generator.py
Labels: in progress

#3044 golem-verificator without docker package dependency
  apps/blender/blender_reference_generator.py
  apps/blender/task/blenderrendertask.py
  apps/blender/verification_queue.py
  apps/lux/task/luxrendertask.py
  golem/docker/image.py
  golem/docker/task_thread.py
  golem/task/localcomputer.py
  golem/task/taskcomputer.py
  requirements.txt
  requirements_to-freeze.txt
  tests/apps/blender/test_blender_reference_generator.py
  tests/golem/docker/test_docker_task_thread.py
Labels: in progress, needs review

#3132 Use a different TimeoutError
  golem/task/taskcomputer.py
Labels: in progress

#3134 Use Ethereum address for incomes
  golem/database/database.py
  golem/database/schemas/018_schema.py
  golem/database/schemas/019_schema.py
  golem/model.py
  golem/task/taskserver.py
  golem/transactions/incomeskeeper.py
  tests/factories/model.py
  tests/golem/network/concent/test_concent_client.py
  tests/golem/network/concent/test_received_handler.py
  tests/golem/task/test_taskserver.py
  tests/golem/transactions/test_incomeskeeper.py
Labels: in progress

#3168 BlenderReferenceGenerator refactor
  apps/blender/blender_reference_generator.py
  requirements.txt
  requirements_to-freeze.txt
  tests/apps/blender/verification/__init__.py
  tests/apps/blender/verification/test_blender_reference_generator.py
  tests/apps/blender/verification/test_data/GolemTask_10001.png
  tests/apps/blender/verification/test_data/GolemTask_10002.png
  tests/apps/blender/verification/test_data/almost_good_image.png
  tests/apps/blender/verification/test_data/bmw.blend
  tests/apps/blender/verification/test_data/very_bad_image.png
  tests/apps/blender/verification/test_verificator_integration.py
Labels: in progress

#2967 [Concent] UC5 / Force Payment - react to ForcePaymentCommitted
  golem/database/database.py
  golem/database/schemas/018_schema.py
  golem/database/schemas/020_income_value_received.py
  golem/ethereum/incomeskeeper.py
  golem/ethereum/transactionsystem.py
  golem/model.py
  golem/network/concent/received_handler.py
  tests/golem/database/test_migration.py
  tests/golem/ethereum/test_incomeskeeper.py
  tests/golem/network/concent/test_received_handler.py
Labels: in progress

#3164 Better error handling
  apps/blender/verification_queue.py
  golem/core/common.py
  golem/task/taskmanager.py
  golem/task/taskthread.py
Labels: in progress

#3180 Change return value of add_payment_info
  golem/ethereum/paymentprocessor.py
  golem/ethereum/transactionsystem.py
  golem/task/taskserver.py
  golem/task/tasksession.py
Labels: in progress

#3179 Clean up IncomesKeeper usages
  golem/ethereum/incomeskeeper.py
  golem/ethereum/transactionsystem.py
  golem/task/taskserver.py
  tests/golem/ethereum/test_transactionsystem.py
  tests/golem/network/concent/test_received_handler.py
  tests/golem/task/test_taskserver.py
Labels: in progress

#3184 Remove second stage of verification
  apps/blender/blender_reference_generator.py
  requirements.txt
  requirements_to-freeze.txt
  tests/apps/blender/verification/test_verificator_integration.py
Labels: in progress

#3185 Replace specialized method with more generic one
  golem/client.py
  golem/ethereum/paymentskeeper.py
  golem/ethereum/transactionsystem.py
  tests/golem/ethereum/test_paymentskeeper.py
Labels: in progress

#3188 fix issue preventing upload of files to Concent when SSL is enabled
  golem/network/concent/client.py
  golem/network/concent/filetransfers.py
  golem/network/concent/helpers.py
Labels: in progress

#3192 Close logging thread
  golem/docker/job.py
Labels: in progress

#3178 3125 bump messages to 2.11.0 3
  golem/model.py
  golem/network/concent/client.py
  golem/network/concent/handlers_library.py
  golem/network/concent/received_handler.py
  golem/network/history.py
  golem/network/p2p/p2pservice.py
  golem/network/p2p/peersession.py
  golem/network/transport/session.py
  golem/network/transport/spamprotector.py
  golem/resource/resourcehandshake.py
  golem/task/taskkeeper.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  requirements.txt
  requirements_to-freeze.txt
  tests/golem/core/test_keysauth.py
  tests/golem/network/concent/test_concent_client.py
  tests/golem/network/p2p/test_peersession.py
  tests/golem/network/transport/test_network.py
  tests/golem/network/transport/test_tcpnetwork.py
  tests/golem/resource/base/common.py
  tests/golem/resource/test_resourcehandshake.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#3197 bump golem-messages to 2.12.0
  requirements.txt
  requirements_to-freeze.txt
Labels: in progress

#3193 Tree 35
  apps/images.ini
  requirements.txt
  requirements_to-freeze.txt
Labels: needs review

#3187 Crops size extended to 0.1 of width
  apps/blender/blender_reference_generator.py
  tests/apps/blender/verification/test_blender_reference_generator.py
Labels: needs review

#3200 Close logging thread (#3192)
  golem/docker/job.py
Labels: in progress

#3198 - "Circle CI" badge (unused)
  README.md
Labels: in progress

#3031 Client.{create,restart}_task: restore returning task id
  golem/client.py
  golem/interface/client/tasks.py
  tests/golem/interface/test_client_commands.py
  tests/golem/test_client.py
Labels: 1, _current, brass, in progress, needs review

#3128 Structured local test result
  apps/blender/resources/blenderloganalyser.py
  tests/apps/blender/resources/test_blenderloganalyser.py
  tests/apps/blender/task/test_blenderrendertask.py
Labels: _current, brass, to be merged

#3205 3067 fill ethsig
  golem/network/transport/tcpnetwork.py
  golem/task/tasksession.py
  requirements.txt
  requirements_to-freeze.txt
  tests/golem/task/test_concent_logic.py
  tests/golem/task/test_tasksession.py
Labels: _current, in progress

#3207 bump messages to 2.12.2 (fix ethereum address checksums on `TaskToCom…
  requirements.txt
  requirements_to-freeze.txt
Labels: _current, in progress

#3209 enable ssl for Concent's `staging` instance
  golem/core/variables.py
  golem/network/concent/resources/ssl/certs/staging.crt
Labels: in progress

#3208 Update Golem AIP to new version and dockertoolbox
  Installer/Installer_Win/Golem.aip
Labels: in progress

#3214 + add an even more baseline integration test with concent disabled for both nodes
  scripts/concent_integration_tests/nodes/provider/no_concent.py
  scripts/concent_integration_tests/nodes/requestor/no_concent.py
  scripts/concent_integration_tests/params.py
  scripts/concent_integration_tests/tests/test_concent_disabled.py
Labels: ci & tests, concent, in progress

#3217 Saving 2 minutes on this test
  tests/golem/task/test_taskpreset.py
Labels: in progress, needs review

#3222 Remove unnecessary CI configs
  .travis.yml
  circle.yml
  shippable.yml
Labels: in progress

#3189 Check next subtask in "react to wants to compute"
  apps/blender/task/blenderrendertask.py
  apps/core/task/coretask.py
  apps/dummy/task/dummytask.py
  apps/lux/task/luxrendertask.py
  apps/rendering/task/framerenderingtask.py
  golem/task/taskbase.py
  golem/task/taskmanager.py
  golem/task/tasksession.py
  tests/apps/blender/task/test_blenderrendertask.py
  tests/apps/core/benchmark/test_benchmarkrunner.py
  tests/apps/core/task/test_coretask.py
  tests/apps/lux/task/test_luxrendertask.py
  tests/apps/rendering/task/test_framerenderingtask.py
  tests/apps/rendering/task/test_renderingtask.py
  tests/golem/task/dummy/runner.py
  tests/golem/task/dummy/task.py
  tests/golem/task/test_concent_logic.py
  tests/golem/task/test_taskmanager.py
  tests/golem/task/test_taskserver.py
  tests/golem/task/test_tasksession.py
Labels: in progress, needs review

#3229 Fix minimum version for docker toolbox
  Installer/Installer_Win/Golem.aip
Labels: in progress

#3074 Moving ls_r function (analogue of `ls -r`) to dirmanager
  apps/dummy/task/dummytaskstate.py
  golem/resource/dirmanager.py
  tests/apps/dummy/task/test_dummytaskstate.py
  tests/golem/resource/test_dirmanager.py
Labels: in progress, needs review

#3235 Handle buckets with more peers than k
  golem/network/p2p/peerkeeper.py
  tests/golem/network/p2p/test_peerkeeper.py
Labels: in progress

#3182 Remove random test
  tests/golem/ethereum/test_ethereumabi.py
Labels: in progress

#3238 Bump pycryptodome version
  requirements.txt
Labels: needs review

#3239 Refactor reserved eth
  golem/ethereum/paymentprocessor.py
  golem/ethereum/transactionsystem.py
  tests/golem/ethereum/test_paymentprocessor.py
Labels: in progress

#3240 web3 provider proxy: return an error instead of None
  golem/ethereum/web3/providers.py
Labels: in progress, needs review

#3242 Fix problem with VirtualBox Driver install after upgrade of DockerToo…
  Installer/Installer_Win/Golem.aip
Labels: in progress

#3243 Do not change locked eth when gas price changes
  golem/ethereum/transactionsystem.py
  tests/golem/ethereum/test_transactionsystem.py
Labels: in progress

#3246 Add fixes for vboxdrv service not properly registered in registry aft…
  Installer/Installer_Win/Golem.aip
Labels: in progress

#3223 Refactor golem.docker.manager module (base: #3219)
  golem/core/common.py
  golem/docker/commands/__init__.py
  golem/docker/commands/docker.py
  golem/docker/commands/docker_for_mac.py
  golem/docker/commands/docker_machine.py
  golem/docker/config.py
  golem/docker/hypervisor/__init__.py
  golem/docker/hypervisor/docker_for_mac.py
  golem/docker/hypervisor/docker_machine.py
  golem/docker/hypervisor/virtualbox.py
  golem/docker/hypervisor/xhyve.py
  golem/docker/manager.py
  tests/golem/docker/test_docker_commands.py
  tests/golem/docker/test_docker_manager.py
  tests/golem/docker/test_hypervisor.py
Labels: clay, docker, in progress, needs review

#3219 Separate DockerManager and Hypervisor classes (base: #3203)
  golem/core/common.py
  golem/docker/commands/__init__.py
  golem/docker/commands/docker.py
  golem/docker/commands/docker_for_mac.py
  golem/docker/commands/docker_machine.py
  golem/docker/config.py
  golem/docker/hypervisor/__init__.py
  golem/docker/hypervisor/docker_for_mac.py
  golem/docker/hypervisor/docker_machine.py
  golem/docker/hypervisor/virtualbox.py
  golem/docker/hypervisor/xhyve.py
  golem/docker/manager.py
  tests/golem/docker/test_docker_commands.py
  tests/golem/docker/test_docker_manager.py
  tests/golem/docker/test_hypervisor.py
Labels: clay, docker, in progress, needs review

#3216 remove working dir
  apps/blender/task/blenderrendertask.py
  apps/core/task/coretask.py
  apps/lux/task/luxrendertask.py
  apps/rendering/task/renderingtask.py
  golem/docker/task_thread.py
  golem/task/localcomputer.py
  golem/task/taskcomputer.py
  golem/task/tasktester.py
  golem/task/taskthread.py
  requirements.txt
  requirements_to-freeze.txt
  tests/apps/blender/verification/test_verificator_integration.py
  tests/apps/core/task/test_coretask.py
  tests/apps/rendering/task/test_renderingtask.py
  tests/golem/docker/test_docker_task_thread.py
  tests/golem/task/test_taskcomputer.py
  tests/golem/task/test_taskmanager.py
Labels: in progress

#3227 add concent_enabled flag to task definition
  apps/core/task/coretask.py
  apps/core/task/coretaskstate.py
  golem/client.py
  golem/task/taskbase.py
  tests/golem/docker/docker-blender-cycles-task.json
  tests/golem/docker/docker-blender-render-task.json
  tests/golem/docker/docker-dummy-test-task.json
  tests/golem/docker/docker-luxrender-test-task.json
  tests/golem/test_client.py
Labels: _current, in progress

#3231 Replace DockerToolbox with DockerForWindows
  Installer/Installer_Win/Golem.aip
Labels: in progress, needs review

#3251 Pickle backwards compatibility for FundsLocker
  golem/ethereum/fundslocker.py
Labels: in progress

#3249 Use simple header unpacker in SpamProtector
  golem/core/variables.py
  golem/network/transport/spamprotector.py
  golem/network/transport/tcpnetwork.py
  requirements.txt
  requirements_to-freeze.txt
Labels: in progress

#3253 taskkeeper: delete pickle if it's broken
  golem/task/taskkeeper.py
Labels: brass, in progress

#3255 more sensible way to specify the golem node parameters
  scripts/concent_integration_tests/params.py
Labels: in progress

#3256 Don't locks funds on unsuccessful attempt
  golem/ethereum/fundslocker.py
  tests/golem/ethereum/test_fundslocker.py
Labels: in progress

#3095 Minor refactor
  apps/core/task/coretask.py
  apps/dummy/task/dummytaskstate.py
  apps/lux/task/luxrendertask.py
  apps/rendering/task/framerenderingtask.py
  golem/docker/job.py
  golem/docker/task_thread.py
  golem/task/taskbase.py
  golem/task/taskmanager.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  golem/task/taskthread.py
  tests/apps/core/benchmark/test_benchmarkrunner.py
  tests/apps/core/task/test_coretask.py
  tests/golem/docker/test_docker_dummy_task.py
  tests/golem/docker/test_docker_luxrender_task.py
  tests/golem/task/dummy/task.py
  tests/golem/task/test_taskmanager.py
Labels: in progress, needs review

#3258 crop rounding bias
  apps/blender/blender_reference_generator.py
Labels: in progress, needs review, to be merged

#3262 ignore patch number while determining the version compatibility of go…
  golem/task/taskkeeper.py
  tests/golem/task/test_taskkeeper.py
Labels: brass, bug, important, in progress
