Repository golemfactory/golem, pull requests merged in 2019-08, with the labels that each got.

#4566 Fixed TaskComputerSnapshotModel
  golem/monitor/model/taskcomputersnapshotmodel.py
  tests/golem/monitor/model/test_taskcomputersnapshotmodel.py
Labels: bug

#4590 Separate base from interface
  golem/envs/__init__.py
  golem/envs/docker/cpu.py
  tests/golem/envs/test_env.py
  tests/golem/envs/test_runtime.py
Labels: clay

#4606 Fix: default ProviderEfficacy value
  golem/model.py
Labels: bug

#4601 Reproduction of bug in reputation system - database LocalRank creation
  golem/model.py
  tests/golem/test_model.py
Labels: reputation

#4614 Moved task status lists from taskmanager to taskstate
  golem/task/taskmanager.py
  golem/task/taskstate.py
  tests/golem/task/test_taskmanager.py
Labels: cleanup

#4579 [CLAY-399] Resource manager: verify cached entry timeouts in hyperg [3/3]
  golem/resource/resourcemanager.py
  tests/golem/resource/test_resourcemanager.py
Labels: clay

#4625 bump messages to 3.11 (always require contract address in the sig has…
  golem/task/tasksession.py
  requirements.txt
  requirements_to-freeze.txt
  scripts/concent_acceptance_tests/base.py
  tests/golem/task/test_concent_logic.py
  tests/golem/task/test_tasksession.py
Labels: concent

#3788 Aio monitor
  golem/client.py
  golem/core/golem_async.py
  golem/monitor/model/nodemetadatamodel.py
  golem/monitor/monitor.py
  golem/monitor/serialization/__init__.py
  golem/monitor/serialization/defaultserializer.py
  golem/monitor/test_helper.py
  golem/monitor/transport/__init__.py
  golem/monitor/transport/httptransport.py
  golem/monitor/transport/proto.py
  golem/monitor/transport/sender.py
  golem/monitorconfig.py
  tests/golem/docker/test_docker_task.py
  tests/golem/monitor/model/test_statssnapshotmodel.py
  tests/golem/monitor/model/test_taskcomputersnapshotmodel.py
  tests/golem/monitor/test_monitor.py
  tests/golem/monitor/test_serializer.py
  tests/golem/task/test_newtaskcomputer.py
  tests/golem/task/test_taskcomputer.py
  tests/golem/test_opt_node.py
  tests/test_golemapp.py
Labels: in progress

#4578 [CLAY-399] hyperg: obligatory share timeouts [2/3]
  golem/network/hyperdrive/client.py
  golem/resource/resourcemanager.py
  golem/task/result/resultmanager.py
  golem/task/rpc.py
  golem/task/server/helpers.py
  golem/task/server/resources.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  tests/golem/resource/base/common.py
  tests/golem/resource/test_resourcemanager.py
  tests/golem/task/result/test_resultmanager.py
  tests/golem/task/test_taskserver.py
  tests/golem/task/test_tasksession.py
Labels: clay

#4577 [CLAY-399] hyperg: unify shared resource lifetimes
  golem/network/hyperdrive/client.py
  golem/network/hyperdrive/daemon_manager.py
  golem/resource/resourcemanager.py
  golem/task/result/resultmanager.py
  golem/task/rpc.py
  golem/task/server/helpers.py
  golem/task/server/resources.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  tests/golem/network/hyperdrive/test_hyperdrive_client.py
  tests/golem/resource/base/common.py
  tests/golem/resource/test_resourcemanager.py
  tests/golem/task/result/test_resultmanager.py
  tests/golem/task/test_taskserver.py
  tests/golem/task/test_tasksession.py
Labels: clay

#4626 remove Python CLI
  Installer/Installer_Linux/install.sh
  golem/interface/__init__.py
  golem/interface/cli.py
  golem/interface/client/__init__.py
  golem/interface/client/account.py
  golem/interface/client/concent.py
  golem/interface/client/debug.py
  golem/interface/client/environments.py
  golem/interface/client/network.py
  golem/interface/client/payments.py
  golem/interface/client/resources.py
  golem/interface/client/settings.py
  golem/interface/client/tasks.py
  golem/interface/client/terms.py
  golem/interface/client/test_task.py
  golem/interface/command.py
  golem/interface/exceptions.py
  golem/interface/formatters.py
  golem/interface/websockets.py
  golem/rpc/mapping/rpcmethodnames.py
  golemcli.py
  golemcli.spec
  setup.py
  setup_util/setup_commons.py
  tests/golem/interface/__init__.py
  tests/golem/interface/client/test_concent.py
  tests/golem/interface/test_cli.py
  tests/golem/interface/test_client_commands.py
  tests/golem/interface/test_command.py
  tests/golem/interface/test_formatters.py
  tests/golem/interface/test_golemcli.py
  tests/golem/interface/test_websocket_cli.py
Labels: 0.20.1 release

#4617 Cleanup subtasks count
  apps/appsmanager.py
  apps/blender/task/blenderrendertask.py
  apps/core/task/coretask.py
  apps/dummy/task/dummytask.py
  apps/glambda/task/glambdatask.py
  apps/rendering/benchmark/renderingbenchmark.py
  apps/rendering/task/framerenderingtask.py
  apps/rendering/task/renderingtask.py
  apps/wasm/task.py
  golem/environments/environment.py
  golem/task/benchmarkmanager.py
  golem/task/rpc.py
  golem/task/taskbase.py
  golem/task/taskmanager.py
  tests/apps/blender/task/test_blenderrendertask.py
  tests/apps/core/task/test_coretask.py
  tests/apps/dummy/task/test_dummytask.py
  tests/apps/glambda/test_task.py
  tests/apps/rendering/task/test_framerenderingtask.py
  tests/apps/rendering/task/test_renderingtask.py
  tests/apps/wasm/test_task.py
  tests/golem/docker/test_docker_blender_task.py
  tests/golem/resource/test_resource.py
  tests/golem/task/dummy/task.py
  tests/golem/task/test_rpc.py
  tests/golem/task/test_taskmanager.py
Labels: 0.20.1 release, _current, brass

#4621 node_integration_tests: lowered the comp.tasks timeout from 60 to 2 minutes
  scripts/node_integration_tests/playbooks/base.py
Labels: ci & tests, cleanup

#4592 Auto-setup wrapper for environments
  golem/envs/__init__.py
  golem/envs/auto_setup.py
  golem/envs/docker/cpu.py
  tests/golem/envs/test_auto_setup.py
Labels: clay

#4642 Skip test_localhost_env (until fixed)
  tests/golem/envs/test_localhost_env.py
Labels: ci & tests

#4634 Various fixes for NewTaskComputer
  golem/task/taskcomputer.py
  golem/task/taskserver.py
  tests/golem/task/test_newtaskcomputer.py
  tests/golem/task/test_taskcomputeradapter.py
Labels: clay

#4657 Manager class for applications using Task API
  golem/app_manager.py
  requirements.txt
  requirements_to-freeze.txt
  tests/golem/test_app_manager.py
Labels: clay

#4618 Docker GPU environment
  golem/envs/docker/gpu.py
  golem/envs/docker/non_hypervised.py
  golem/envs/docker/vendor/__init__.py
  golem/envs/docker/vendor/nvidia.py
  golem/task/taskcomputer.py
  golem/task/taskserver.py
  tests/golem/envs/docker/gpu/__init__.py
  tests/golem/envs/docker/gpu/test_config.py
  tests/golem/envs/docker/gpu/test_env.py
  tests/golem/envs/docker/gpu/test_runtime.py
  tests/golem/envs/docker/vendor/__init__.py
  tests/golem/envs/docker/vendor/test_nvidia.py
  tests/golem/task/test_newtaskcomputer.py
Labels: clay

#4623 Docker GPU benchmark image
  codecov.yml
  golem/environments/environment.py
  golem/envs/docker/benchmark/cpu/Dockerfile
  golem/envs/docker/benchmark/cpu/entrypoint.py
  golem/envs/docker/benchmark/cpu/minilight/__init__.py
  golem/envs/docker/benchmark/cpu/minilight/cornellbox.ml.txt
  golem/envs/docker/benchmark/cpu/minilight/src/__init__.py
  golem/envs/docker/benchmark/cpu/minilight/src/camera.py
  golem/envs/docker/benchmark/cpu/minilight/src/image.py
  golem/envs/docker/benchmark/cpu/minilight/src/img.py
  golem/envs/docker/benchmark/cpu/minilight/src/maxilight.py
  golem/envs/docker/benchmark/cpu/minilight/src/minilight.py
  golem/envs/docker/benchmark/cpu/minilight/src/randommini.py
  golem/envs/docker/benchmark/cpu/minilight/src/raytracer.py
  golem/envs/docker/benchmark/cpu/minilight/src/rendertask.py
  golem/envs/docker/benchmark/cpu/minilight/src/rendertaskcreator.py
  golem/envs/docker/benchmark/cpu/minilight/src/renderworker.py
  golem/envs/docker/benchmark/cpu/minilight/src/scene.py
  golem/envs/docker/benchmark/cpu/minilight/src/spatialindex.py
  golem/envs/docker/benchmark/cpu/minilight/src/surfacepoint.py
  golem/envs/docker/benchmark/cpu/minilight/src/task_data_0.py
  golem/envs/docker/benchmark/cpu/minilight/src/taskablelight.py
  golem/envs/docker/benchmark/cpu/minilight/src/taskablerenderer.py
  golem/envs/docker/benchmark/cpu/minilight/src/triangle.py
  golem/envs/docker/benchmark/cpu/minilight/src/vector3f.py
  golem/envs/docker/benchmark/gpu/Dockerfile
  golem/envs/docker/benchmark/gpu/benchmark.sh
  scripts/pyinstaller/hooks/hook-golem.py
  setup.py
Labels: clay
