Repository golemfactory/golem, pull requests merged in 2019-09, with the labels that each got.

#4667 Use multiprocessing in LocalhostEnvironment
  requirements-lint.txt
  requirements-test.txt
  requirements-test_to-freeze.txt
  tests/golem/envs/localhost.py
  tests/golem/envs/test_localhost_env.py
Labels: clay

#4633 Improvements in Localhost environment
  requirements-lint.txt
  requirements-test.txt
  requirements-test_to-freeze.txt
  requirements.txt
  requirements_to-freeze.txt
  tests/golem/envs/localhost.py
  tests/golem/envs/test_localhost_env.py
Labels: clay

#4670 Upgrade to Task API v 0.13.0
  golem/task/taskcomputer.py
  golem/task/taskserver.py
  tests/golem/task/test_newtaskcomputer.py
  tests/golem/task/test_taskcomputeradapter.py
  tests/golem/task/test_taskserver.py
Labels: clay

#4674 fix concent filetransfers headers ...
  golem/network/concent/filetransfers.py
  tests/golem/network/concent/test_filetransfers.py
Labels: concent

#4676 Upgrade to Task API v 0.14.0
  golem/task/task_api/__init__.py
  requirements.txt
  requirements_to-freeze.txt
  tests/golem/task/task_api/test_task_api_service.py
Labels: clay

#4635 Tests for integration between TaskServer and NewTaskComputer
  tests/golem/task/test_taskserver.py
Labels: clay

#4683 A quick fix for tests referring removed ENV_ID
  tests/golem/task/test_taskserver.py
Labels: bug, clay

#4692 Modify a copy of config dict in DockerCPUConfig.from_dict
  golem/envs/docker/cpu.py
Labels: bug

#4691 Fix WASM abort
  apps/wasm/task.py
Labels: 0.21 release, bug

#4688 Fix WASM abort
  apps/wasm/task.py
Labels: 0.20 release, bug

#4689 Async test utils
  tests/golem/envs/docker/cpu/test_runtime.py
  tests/golem/envs/test_localhost_env.py
  tests/golem/task/test_newtaskcomputer.py
  tests/golem/task/test_requestedtaskmanager.py
  tests/golem/task/test_taskserver.py
  tests/utils/__init__.py
  tests/utils/asyncio.py
Labels: cleanup

#4687 Add result arbitration to WASM task
  apps/wasm/task.py
Labels: 0.21 release, enhancement

#4725 Fix VbR BucketVerifier and add tests
  apps/wasm/vbr.py
  tests/apps/wasm/test_vbr.py
Labels: P0, bug

#4701 ACL Database
  golem/client.py
  golem/database/database.py
  golem/database/schemas/036_create_acl.py
  golem/model.py
  golem/task/acl.py
  golem/task/taskserver.py
  tests/golem/resource/test_resourcehandshake.py
  tests/golem/task/test_acl.py
  tests/golem/test_client.py
Labels: _current, to be merged

#4743 fix task loading when resources have negative timeouts (historic tasks)
  golem/task/server/resources.py
Labels: 0.21 release

#4722 Introduced app IDs and added app loading
  golem/app_manager.py
  golem/task/taskserver.py
  tests/golem/http/__init__.py
  tests/golem/test_app_manager.py
Labels: clay

#4746 Upgrade to Task API v0.18.3 and some fixes
  golem/task/requestedtaskmanager.py
  golem/task/tasksession.py
  requirements.txt
  requirements_to-freeze.txt
  tests/golem/envs/localhost.py
  tests/golem/envs/test_localhost_env.py
  tests/golem/task/test_requestedtaskmanager.py
  tests/golem/task/test_tasksession_task_api.py
Labels: clay

#4752 When ACL in restricted mode, do not temporarly block whitelisted nodes
  apps/core/benchmark/benchmarkrunner.py
  golem/network/hyperdrive/client.py
  golem/task/acl.py
  tests/golem/task/test_rpc.py
Labels: _current

#4770 Upgrade to Task API v0.20.0
  golem/task/requestedtaskmanager.py
  golem/task/server/helpers.py
  requirements.txt
  requirements_to-freeze.txt
  scripts/task_api_tests/basic_integration.py
  tests/golem/envs/localhost.py
  tests/golem/envs/test_localhost_env.py
  tests/golem/task/server/test_helpers.py
  tests/golem/task/test_requestedtaskmanager.py
Labels: clay

#4774 fix enable_{talkback,monitor} typing
  golem/client.py
  golem/node.py
  golem/tools/talkback.py
  golemapp.py
Labels: 0.21 release, brass
