Repository golemfactory/golem, pull requests merged in 2019-12, with the labels that each got.

#4901 Runtime usage counters
  golem/envs/__init__.py
  golem/envs/docker/cpu.py
  golem/envs/docker/gpu.py
  golem/envs/wrappers/__init__.py
  tests/golem/envs/docker/cpu/test_integration.py
  tests/golem/envs/docker/cpu/test_runtime.py
  tests/golem/envs/docker/gpu/test_runtime.py
  tests/golem/envs/localhost.py
  tests/golem/envs/test_auto_setup.py
Labels: clay

#4925 [P5b] Transcoding: Default audio codec detection and validation
  apps/images.ini
  apps/transcoding/ffmpeg/environment.py
  apps/transcoding/ffmpeg/ffmpeg_docker_api.py
  apps/transcoding/ffmpeg/resources/ffmpeg-scripts/ffmpeg_task.py
  apps/transcoding/ffmpeg/resources/ffmpeg-scripts/requirements.txt
  apps/transcoding/ffmpeg/task.py
  apps/transcoding/ffmpeg/utils.py
  apps/transcoding/task.py
  requirements.txt
  tests/apps/ffmpeg/task/test_ffmpegintegration.py
  tests/apps/ffmpeg/task/test_ffmpegintegration_all_bundle_files.py
  tests/apps/ffmpeg/task/test_ffmpegtask.py
  tests/apps/ffmpeg/task/test_ffmpegtranscoding.py
Labels: cgi, transcoding

#4974 Strip newline from docker-machine ip output
  golem/docker/hypervisor/docker_machine.py
  golem/docker/hypervisor/dummy.py
  golem/task/task_api/__init__.py
  tests/golem/docker/test_hypervisor.py
Labels: 0.22 release, bug, clay, important

#4976 Extended update-config to allow for only saving without updating config
  golem/client.py
  golem/task/rpc.py
  golem/task/taskcomputer.py
  golem/task/taskserver.py
  tests/golem/task/test_rpc_task_api.py
  tests/golem/task/test_taskcomputeradapter.py
  tests/golem/task/test_taskserver.py
Labels: 0.22 release

#4977 Stop DockerManager after stopping Client
  golem/node.py
Labels: 0.22 release, bug, clay, docker, important, windows

#4978 Use utc timestamp when checking task deadline
  golem/client.py
  golem/core/common.py
  golem/model.py
  golem/task/requestedtaskmanager.py
  golem/task/taskserver.py
  tests/golem/task/test_requestedtaskmanager.py
Labels: 0.22 release

#4969 task-api task timeout bugfix
  golem/model.py
  golem/task/requestedtaskmanager.py
  scripts/node_integration_tests/tasks/__init__.py
  scripts/task_api_tests/basic_integration.py
  tests/golem/task/test_requestedtaskmanager.py
Labels: 0.22 release

#4972 Store subtask budget in CompTaskKeeper
  golem/task/taskkeeper.py
  golem/task/taskmanager.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  tests/golem/envs/docker/cpu/test_runtime.py
  tests/golem/task/test_taskkeeper.py
  tests/golem/task/test_taskserver.py
  tests/golem/task/test_tasksession.py
Labels: 0.22 release

#4975 Introduced DummyHyperVHypervisor
  golem/docker/hypervisor/docker_for_mac.py
  golem/docker/hypervisor/docker_machine.py
  golem/docker/hypervisor/dummy.py
  golem/envs/docker/non_hypervised.py
  tests/golem/docker/test_hypervisor.py
Labels: 0.22 release, bug, clay, docker, important, windows

#4952 [P6b] Transcoding: Audio sample rate validation
  apps/transcoding/ffmpeg/ffmpeg_docker_api.py
  apps/transcoding/ffmpeg/resources/ffmpeg-scripts/ffmpeg_task.py
  apps/transcoding/ffmpeg/utils.py
  apps/transcoding/task.py
  tests/apps/ffmpeg/task/test_ffmpegtranscoding.py
Labels: cgi, transcoding

#4953 Transcoding: Fix duplicate container in extra_data
  apps/transcoding/ffmpeg/task.py
Labels: cgi, transcoding

#4982 Container not shut down on task creation failure
  golem/task/requestedtaskmanager.py
  golem/task/rpc.py
  requirements.txt
  requirements_to-freeze.txt
  scripts/task_api_tests/basic_integration.py
  tests/golem/task/test_requestedtaskmanager.py
  tests/golem/task/test_rpc.py
  tests/golem/task/test_rpc_task_api.py
Labels: 0.22 release, bug, clay

#4990 update requirements
  requirements-lint.txt
  requirements-test.txt
  requirements.txt
  requirements_to-freeze.txt
Labels: 0.22 release

#4991 fix Concent force download handler
  golem/network/concent/received_handler.py
  loggingconfig.py
  tests/golem/network/concent/test_received_handler.py
Labels: concent

#4954 [I6] Transcoding: Automatic detection of target video codec and resolution
  apps/transcoding/task.py
  tests/apps/ffmpeg/task/test_ffmpegintegration.py
  tests/apps/ffmpeg/task/test_ffmpegtask.py
Labels: cgi, transcoding

#4955 Transcoding: Fix wrong frame counts in transcoding-video-bundle
  tests/apps/ffmpeg/task/test_ffmpegintegration_all_bundle_files.py
  tests/apps/ffmpeg/transcoding_video_bundle/build-name.sh
  tests/apps/ffmpeg/transcoding_video_bundle/download-bundle.sh
Labels: cgi, transcoding

#4956 Transcoding test fixes
  tests/apps/ffmpeg/task/test_ffmpegintegration_all_bundle_files.py
  tests/apps/ffmpeg/task/utils/test_ffprobe_report.py
Labels: cgi, transcoding

#4992 Task-api handle `cannot_compute_task` message
  golem/task/requestedtaskmanager.py
  golem/task/tasksession.py
  tests/golem/task/test_tasksession.py
Labels: 0.22 release

#4999 Fixed recovery logic for DockerMachineHypervisor
  golem/docker/commands/docker.py
  golem/docker/hypervisor/docker_machine.py
  tests/golem/docker/test_hyperv.py
Labels: 0.22 release, bug, docker, important, windows

#5004 Properly handle timeouts/cancellations of Task API subtasks
  golem/task/taskcomputer.py
  golem/task/taskserver.py
  tests/golem/task/test_newtaskcomputer.py
  tests/golem/task/test_taskcomputeradapter.py
  tests/golem/task/test_taskserver.py
Labels: bug

#5005 Update blenderapp to 0.7.2 and golem-task-api to 0.24.1
  golem/apps/default.py
  requirements.txt
  requirements_to-freeze.txt
Labels: 0.22 release, important

#5006 early exit from blockchain monitor on shutdown
  golem/ethereum/web3/providers.py
  requirements.txt
  requirements_to-freeze.txt
Labels: brass

#5003 Resolved misc task-api related warnings
  golem/ethereum/fundslocker.py
  golem/marketplace/brass_marketplace.py
  golem/marketplace/marketplace.py
  golem/marketplace/wasm_marketplace.py
  golem/task/taskserver.py
  tests/golem/marketplace/test_marketplace.py
Labels: 0.22 release
