Repository golemfactory/golem, pull requests merged in 2019-10, with the labels that each got.

#4777 RequestedTaskManager: make sure that database is set properly in peewee models
  golem/model.py
Labels: clay

#4785 Include market strategy in app definition
  golem/app_manager.py
  golem/marketplace/__init__.py
  golem/task/requestedtaskmanager.py
  golem/task/taskserver.py
  golem/task/tasksession.py
Labels: clay

#4816 fix payment calculation in BrassMarketplace
  golem/marketplace/brass_marketplace.py
  tests/golem/marketplace/test_marketplace.py
Labels: brass, important

#4823 catch openvc errors better
  apps/rendering/task/framerenderingtask.py
Labels: 0.21 release

#4824 Update to Task API v0.21.0
  golem/task/requestedtaskmanager.py
  requirements.txt
  requirements_to-freeze.txt
  tests/golem/task/test_requestedtaskmanager.py
Labels: clay

#4789 Task API app benchmarks
  golem/database/database.py
  golem/database/schemas/043_app_benchmarks.py
  golem/model.py
  golem/task/__init__.py
  golem/task/benchmarkmanager.py
  golem/task/exceptions.py
  golem/task/taskserver.py
  tests/golem/task/test_appbenchmarkmanager.py
  tests/golem/task/test_taskserver.py
Labels: clay

#4829 cleanup and typing
  golem/network/p2p/peersession.py
  golem/network/transport/session.py
  golem/network/transport/tcpserver.py
  golem/task/server/queue_.py
  golem/task/tasksession.py
Labels: cleanup

#4832 Don't count type checking imports in coverage report
  .coveragerc
Labels: ci & tests

#4820 NV driver semver
  apps/core/nvgpu/__init__.py
Labels: bug

#4813 New logic for setting up and cleaning up environments
  golem/envs/auto_setup.py
  golem/envs/default.py
  golem/task/envmanager.py
  scripts/task_api_tests/basic_integration.py
  tests/golem/envs/test_auto_setup.py
  tests/golem/task/test_envmanager.py
Labels: clay

#4830 Fixed task timeout in RequestedTaskManager
  golem/task/requestedtaskmanager.py
  golem/task/taskstate.py
  tests/golem/task/test_requestedtaskmanager.py
Labels: clay

#4837 Provider/requestor switch
  golem/client.py
  golem/task/requestedtaskmanager.py
  golem/task/rpc.py
  golem/task/taskserver.py
  golem/task/taskstate.py
  tests/golem/task/test_requestedtaskmanager.py
  tests/golem/task/test_rpc_task_api.py
  tests/golem/task/test_taskserver.py
  tests/golem/test_client.py
Labels: clay

#4841 Fix MaskUpdateService
  golem/client.py
Labels: clay

#4839 Task API v0.22.0
  golem/apps/default.py
  golem/task/requestedtaskmanager.py
  golem/task/taskkeeper.py
  requirements.txt
  requirements_to-freeze.txt
  scripts/node_integration_tests/tasks/__init__.py
  tests/golem/envs/localhost.py
  tests/golem/envs/test_localhost_env.py
  tests/golem/task/test_requestedtaskmanager.py
  tests/golem/task/test_taskkeeper.py
Labels: clay
