Repository golemfactory/golem, pull requests merged in 2019-06, with the labels that each got.

#4262 bump messages to 3.6
  requirements.txt
  requirements_to-freeze.txt
Labels: brass

#4258 Crossbar json serializer
  golem/node.py
  golem/rpc/router.py
  golemapp.py
  scripts/node_integration_tests/nodes/json_serializer.py
  scripts/node_integration_tests/playbooks/golem/json_serializer/__init__.py
  scripts/node_integration_tests/playbooks/golem/json_serializer/playbook.py
  scripts/node_integration_tests/playbooks/golem/json_serializer/test_config.py
  scripts/node_integration_tests/playbooks/test_config_base.py
  tests/golem/test_opt_node.py
Labels: 0.20 release, _current, brass

#4209 StatusPublisher's events with message codes
  golem/docker/hypervisor/hyperv.py
  golem/report.py
  tests/golem/test_client.py
Labels: 0.20 release

#4277 requirements update
  requirements-lint.txt
  requirements-test.txt
  requirements.txt
  requirements_to-freeze.txt
Labels: brass

#4280 one more bump
  requirements.txt
  requirements_to-freeze.txt
Labels: brass

#4282 fix concent acceptance tests
  scripts/concent_acceptance_tests/additional_verification/base.py
  scripts/concent_acceptance_tests/additional_verification/test_messages.py
  scripts/concent_acceptance_tests/base.py
  scripts/concent_acceptance_tests/basic/test_basic.py
  scripts/concent_acceptance_tests/force_accept/test_requestor_doesnt_send.py
  scripts/concent_acceptance_tests/force_download/base.py
  scripts/concent_acceptance_tests/force_download/test_messages.py
  scripts/concent_acceptance_tests/force_payment/test_payment.py
  scripts/concent_acceptance_tests/force_report/test_messages.py
Labels: concent

#4170 [WTCT] explicit ETH addr instead of derivation from ETH pub key
  golem/core/keysauth.py
  golem/database/schemas/018_schema.py
  golem/task/taskserver.py
  golem/utils.py
  requirements.txt
  requirements_to-freeze.txt
  scripts/concent_acceptance_tests/force_payment/test_payment.py
  tests/golem/task/test_taskserver.py
  tests/golem/test_utils.py
Labels: in progress

#4268 Don't allow use to chose Docker Toolbox if Hyper-V is installed
  .gitignore
  Installer/Installer_Win/Golem.aip
  scripts/virtualization/check-hyperv-installation.ps1
Labels: 0.20 release, windows

#4296 fix gvisor installation in the Linux installer
  Installer/Installer_Linux/install.sh
Labels: brass

#4292 Linux: install hyperg from the 'simple-transfer' repo
  Installer/Installer_Linux/install.sh
Labels: 0.20 release

#4299 Bump min required HyperG version to 0.3.1
  golem/network/hyperdrive/daemon_manager.py
Labels: 0.20 release

#4298 Linux installer: Docker: test after the service is restarted
  Installer/Installer_Linux/install.sh
Labels: 0.20 release

#4305 treat retrieval of an incompatible message from history as a "message…
  golem/network/history.py
  tests/golem/network/test_history.py
Labels: brass, bug

#4289 Added config to node_integration_tests, ignoring non test directories
  scripts/node_integration_tests/pytest.ini
Labels: ci & tests

#4312 bring `node_name` back to `SubtaskState` ...
  golem/task/taskmanager.py
  tests/factories/model.py
  tests/golem/task/test_taskmanager.py
Labels: brass

#4249 Enhanced transcoding integration tests with ffprobe report
  apps/transcoding/ffmpeg/utils.py
  golem/testutils.py
  requirements-test.txt
  requirements-test_to-freeze.txt
  tests/apps/ffmpeg/task/test_ffmpegintegration.py
  tests/apps/ffmpeg/task/utils/ffprobe_report.py
  tests/apps/ffmpeg/task/utils/ffprobe_report_sample_reports.py
  tests/apps/ffmpeg/task/utils/ffprobe_report_set.py
  tests/apps/ffmpeg/task/utils/simulated_transcoding_operation.py
  tests/apps/ffmpeg/task/utils/test_ffprobe_report.py
  tests/apps/ffmpeg/task/utils/test_ffprobe_report_set.py
  tests/apps/ffmpeg/task/utils/test_fmmpegtranscoding.py
  tests/apps/ffmpeg/task/utils/test_simulated_transcoding_operation.py
Labels: cgi, transcoding

#4322 add `eventlet` to requirements
  requirements.txt
Labels: brass

#4327 Remove the 'duration' field from RPC Task dict representation
  golem/task/taskmanager.py
Labels: 0.20 release

#4328 Add hook for numpy in pyinstaller
  scripts/pyinstaller/hooks/hook-numpy.core.py
Labels: 0.20 release

#4331 fixes the `object has no attribute '_handshake_error'` error
  golem/task/server/resources.py
  tests/golem/task/server/test_resources.py
Labels: 0.20 release, brass

#4276 node_integration_tests - use granary for key reuse
  scripts/node_integration_tests/conftest.py
  scripts/node_integration_tests/helpers.py
  scripts/node_integration_tests/key_reuse.py
  scripts/node_integration_tests/playbooks/test_config_base.py
  scripts/node_integration_tests/tests/base.py
  scripts/node_integration_tests/tests/test_fails.py
  tests/factories/granary.py
Labels: clay

#4235 Non-hypervised Docker CPU Environment
  golem/docker/hypervisor/dummy.py
  golem/envs/docker/non_hypervised.py
  golem/task/taskcomputer.py
  golem/task/taskkeeper.py
  golem/task/taskserver.py
  requirements.txt
  requirements_to-freeze.txt
  tests/factories/taskserver.py
  tests/golem/docker/test_docker_task.py
  tests/golem/docker/test_docker_task_thread.py
  tests/golem/network/concent/test_received_handler.py
  tests/golem/network/p2p/test_peersession.py
  tests/golem/task/dummy/runner.py
  tests/golem/task/dummy/test_runner_script.py
  tests/golem/task/server/test_queue.py
  tests/golem/task/server/test_resources.py
  tests/golem/task/test_rpc.py
  tests/golem/task/test_taskcomputer.py
  tests/golem/task/test_taskkeeper.py
  tests/golem/task/test_taskserver.py
  tests/golem/test_client.py
Labels: clay

#4309 Transcoding video bundle
  tests/apps/ffmpeg/resources/.gitignore
  tests/apps/ffmpeg/transcoding_video_bundle/.gitignore
  tests/apps/ffmpeg/transcoding_video_bundle/README.md
  tests/apps/ffmpeg/transcoding_video_bundle/build-name.sh
  tests/apps/ffmpeg/transcoding_video_bundle/build.sh
  tests/apps/ffmpeg/transcoding_video_bundle/count-key-frames.sh
  tests/apps/ffmpeg/transcoding_video_bundle/download-bundle.sh
  tests/apps/ffmpeg/transcoding_video_bundle/shorten-video.sh
  tests/apps/ffmpeg/transcoding_video_bundle/video-sources.txt
Labels: cgi, transcoding

#4340 Requestor task models
  golem/database/database.py
  golem/database/schemas/032_requestor_models.py
  golem/model.py
Labels: clay

#4353 Fix HyperV warning events
  golem/docker/hypervisor/hyperv.py
  tests/golem/docker/test_hyperv.py
Labels: 0.20 release, bug

#4355 B0.20 develop
  .gitignore
  apps/images.ini
  golem/docker/hypervisor/hyperv.py
  golem/ethereum/transactionsystem.py
  golem/manager/nodestatesnapshot.py
  golem/network/hyperdrive/daemon_manager.py
  golem/task/server/resources.py
  golem/task/taskcomputer.py
  golem/task/taskmanager.py
  golem/verificator/blender_verifier.py
  requirements.txt
  scripts/node_integration_tests/helpers.py
  scripts/node_integration_tests/playbooks/golem/nested_column/__init__.py
  scripts/node_integration_tests/playbooks/golem/nested_column/playbook.py
  scripts/node_integration_tests/playbooks/golem/nested_column/test_config.py
  scripts/node_integration_tests/playbooks/test_config_base.py
  scripts/node_integration_tests/run_test.py
  scripts/node_integration_tests/tasks/column/assets/altocumulus.jpg
  scripts/node_integration_tests/tasks/column/assets/column.blend
  scripts/node_integration_tests/tasks/column/assets/jello.blend
  scripts/node_integration_tests/tasks/column/the_column.blend
  scripts/node_integration_tests/tests/test_golem.py
  scripts/pyinstaller/hooks/hook-numpy.core.py
  tests/golem/docker/test_hyperv.py
  tests/golem/ethereum/test_transactionsystem.py
  tests/golem/task/server/test_resources.py
Labels: brass

#4354 Disable Task.initialize execution timeout
  golem/core/deferred.py
Labels: bug

#4358 + `test_large_result` node integration test optimization
  scripts/node_integration_tests/tasks/__init__.py
  scripts/node_integration_tests/tests/test_golem.py
Labels: brass

#4360 * reduce severity of mask mismatch
  golem/environments/environment.py
  golem/task/taskkeeper.py
  tests/golem/task/test_taskkeeper.py
Labels: brass

#4356 Models for new environment performance
  golem/database/database.py
  golem/database/schemas/033_new_performance.py
  golem/model.py
Labels: clay

#4361 Moved requesting resources out of TaskComputer
  golem/client.py
  golem/task/taskcomputer.py
  golem/task/taskserver.py
  tests/golem/docker/test_docker_task.py
  tests/golem/task/test_taskcomputer.py
  tests/golem/task/test_taskserver.py
Labels: clay

#4387 send srr if fgtrf is in history
  golem/network/concent/received_handler.py
  tests/golem/network/concent/test_received_handler.py
Labels: brass, concent

#4392 + Docker image integrity verifier
  requirements-test_to-freeze.txt
  scripts/docker_integrity/README.md
  scripts/docker_integrity/image_integrity.ini
  scripts/docker_integrity/verify.py
Labels: brass
