Repository golemfactory/golem, pull requests merged in 2019-03, with the labels that each got.

#3917 Remove resource size from task header
  apps/core/task/coretask.py
  golem/resource/resourcehandshake.py
  golem/task/rpc.py
  golem/task/server/helpers.py
  golem/task/server/resources.py
  golem/task/taskkeeper.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  requirements.txt
  requirements_to-freeze.txt
  tests/golem/docker/test_docker_blender_task.py
  tests/golem/task/dummy/task.py
  tests/golem/task/test_concent_logic.py
  tests/golem/task/test_taskkeeper.py
  tests/golem/task/test_taskserver.py
  tests/golem/task/test_tasksession.py
Labels: in progress, needs review

#3938 Fix docker scripts [b0.19]
  golem/core/windows.py
  golem/docker/hypervisor/hyperv.py
  scripts/docker/create-share.ps1
  scripts/docker/prepare-docker-for-windows.ps1
Labels: 0.19.1 release, bug, docker, in progress, windows

#3939 Fix docker scripts
  scripts/docker/create-share.ps1
  scripts/docker/prepare-docker-for-windows.ps1
Labels: bug, docker, in progress, windows

#3948 Fix TestBlenderVerifier: copy resource instead of creating hard link
  tests/golem/verificator/test_blenderverifier.py
Labels: in progress

#3946 Fix iterating over subtasks_given in coretask.py
  apps/core/task/coretask.py
Labels: in progress

#3959 Cleanup Windows-specific Rust code
  rust/golem/src/os/windows.rs
Labels: in progress

#3941 Remove old ResourceManager
  golem/resource/resource.py
  golem/resource/resourcesmanager.py
  golem/task/rpc.py
  golem/task/taskcomputer.py
  tests/golem/docker/test_docker_task.py
  tests/golem/resource/test_resource.py
  tests/golem/resource/test_resourcemanager.py
  tests/golem/task/test_taskcomputer.py
Labels: needs review

#3967 Bugfix logic of verification task
  golem/verificator/core_verifier.py
  tests/golem/verificator/test_core_verifier.py
Labels: in progress

#3964 Fix free providers
  golem/client.py
  golem/task/taskkeeper.py
  golem/task/tasksession.py
  scripts/node_integration_tests/playbooks/base.py
  scripts/node_integration_tests/playbooks/golem/zero_price.py
  scripts/node_integration_tests/tests/test_golem.py
  tests/golem/task/test_concent_logic.py
Labels: _current, in progress

#3957 Remove dead code all over the project
  golem/client.py
  golem/core/deferred.py
  golem/core/fileshelper.py
  golem/core/simpleauth.py
  golem/environments/environmentsconfig.py
  golem/ethereum/paymentskeeper.py
  golem/network/adapter/__init__.py
  golem/network/adapter/adapter.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  golem/task/taskstate.py
  golem/tools/captureoutput.py
  golem/tools/ci.py
  golem/tools/memoryhelper.py
  golem/verificator/common/rendering_task_utils.py
Labels: in progress

#3932 Replace script_filepath with a custom command
  apps/blender/task/blenderrendertask.py
  apps/dummy/task/dummytask.py
  golem/docker/job.py
  golem/docker/task_thread.py
  golem/verificator/blender_verifier.py
  tests/golem/docker/test_docker_job.py
  tests/golem/task/test_localcomputer.py
  tests/golem/verificator/test_blenderverifier.py
Labels: in progress

#3923 Fix GNT conversion when there's GNT top up in the meantime
  golem/ethereum/transactionsystem.py
  requirements.txt
  requirements_to-freeze.txt
  tests/golem/ethereum/test_transactionsystem.py
Labels: in progress

#3976 fix math of calculating scaled price for marketplace
  golem/marketplace/__init__.py
  golem/marketplace/offerpool.py
  golem/task/tasksession.py
  rust/golem/src/marketplace.rs
  tests/golem/marketplace/test_offerpool.py
  tests/golem/marketplace/test_rust.py
Labels: _current, in progress

#3974 Verifier cleanup/fix existing unit tests
  golem/verificator/imgverifier.py
  golem/verificator/rendering_verifier.py
  tests/golem/verificator/imgs_for_verification_tests/300x400spp50_run0.png
  tests/golem/verificator/imgs_for_verification_tests/300x400spp50_run1.png
  tests/golem/verificator/imgs_for_verification_tests/malicious300x400spp1_run0.png
  tests/golem/verificator/imgs_for_verification_tests/malicious300x400spp1_run1.png
  tests/golem/verificator/imgs_for_verification_tests/malicious300x400spp5_run0.png
  tests/golem/verificator/imgs_for_verification_tests/malicious300x400spp5_run1.png
  tests/golem/verificator/imgs_for_verification_tests/maliciousBlankWhite.png
  tests/golem/verificator/imgs_for_verification_tests/maliciousKitty.png
  tests/golem/verificator/test_core_verifier.py
  tests/golem/verificator/test_image_verifier.py
  tests/golem/verificator/test_renderingverifier.py
Labels: in progress

#3979 add node shutdown message
  scripts/node_integration_tests/helpers.py
Labels: in progress

#3914 Differentiate CannotAssignTask responses
  golem/network/p2p/peersession.py
  golem/network/transport/session.py
  golem/task/taskmanager.py
  golem/task/tasksession.py
  tests/golem/task/dummy/runner.py
  tests/golem/task/dummy/test_runner_script.py
  tests/golem/task/test_taskmanager.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#3695 Removing pil module
  apps/blender/task/blenderrendertask.py
  apps/rendering/benchmark/renderingbenchmark.py
  apps/rendering/resources/imgcompare.py
  apps/rendering/resources/imgrepr.py
  apps/rendering/resources/imgverifier.py
  apps/rendering/resources/renderingtaskcollector.py
  apps/rendering/resources/utils.py
  apps/rendering/task/framerenderingtask.py
  apps/rendering/task/renderingtask.py
  golem/verificator/imgrepr.py
  golem/verificator/imgverifier.py
  golem/verificator/rendering_verifier.py
  requirements.txt
  requirements_to-freeze.txt
  tests/apps/blender/resources/test_blenderimgcompare.py
  tests/apps/blender/task/test_blenderrendertask.py
  tests/apps/core/benchmark/test_benchmark.py
  tests/apps/rendering/resources/imghelper.py
  tests/apps/rendering/resources/test_imgcompare.py
  tests/apps/rendering/resources/test_imgrepr.py
  tests/apps/rendering/resources/test_renderingtaskcollector.py
  tests/apps/rendering/resources/test_utils.py
  tests/apps/rendering/task/test_framerenderingtask.py
  tests/apps/rendering/task/test_renderingtask.py
  tests/apps/test_appsmanager.py
  tests/golem/verificator/test_image_verifier.py
  tests/golem/verificator/test_renderingverifier.py
Labels: in progress

#3988 B0.19 develop
  golem/client.py
  golem/core/windows.py
  golem/docker/hypervisor/hyperv.py
  golem/ethereum/transactionsystem.py
  golem/marketplace/__init__.py
  golem/marketplace/offerpool.py
  golem/task/taskkeeper.py
  golem/task/tasksession.py
  requirements.txt
  requirements_to-freeze.txt
  rust/golem/src/marketplace.rs
  scripts/node_integration_tests/playbooks/base.py
  scripts/node_integration_tests/playbooks/golem/zero_price.py
  scripts/node_integration_tests/tests/test_golem.py
  tests/golem/ethereum/test_transactionsystem.py
  tests/golem/marketplace/test_offerpool.py
  tests/golem/marketplace/test_rust.py
  tests/golem/task/test_concent_logic.py
Labels: in progress

#3942 Use res_id instead task_id in ResourceManager
  golem/client.py
  golem/resource/base/resourceserver.py
  golem/resource/hyperdrive/resource.py
  golem/resource/hyperdrive/resourcesmanager.py
  golem/task/rpc.py
  golem/task/server/resources.py
  golem/task/taskcomputer.py
  tests/golem/docker/test_docker_task.py
  tests/golem/resource/base/common.py
  tests/golem/resource/base/test_base_resourceserver.py
  tests/golem/resource/hyperdrive/test_hyperdrive_resource.py
  tests/golem/resource/hyperdrive/test_hyperdrive_resourcemanager.py
  tests/golem/task/test_rpc.py
  tests/golem/task/test_taskcomputer.py
  tests/golem/task/test_taskserver.py
Labels: needs review

#3918 Many improvements spread all over
  apps/core/task/coretask.py
  golem/appconfig.py
  golem/client.py
  golem/clientconfigdescriptor.py
  golem/ethereum/fundslocker.py
  golem/ethereum/paymentskeeper.py
  golem/ethereum/transactionsystem.py
  golem/rpc/mapping/rpceventnames.py
  golem/rpc/mapping/rpcmethodnames.py
  golem/task/acl.py
  golem/task/taskmanager.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  golem/task/taskstate.py
  tests/golem/task/test_acl.py
  tests/golem/task/test_taskserver.py
  tests/golem/task/test_tasksession.py
  tests/golem/task/test_taskstate.py
  tests/golem/test_client.py
Labels: in progress

#3983 Restructure scripts in Blender Docker so PYTHONPATH is not required
  apps/blender/blenderenvironment.py
  apps/blender/resources/images/blender.Dockerfile
  apps/blender/resources/images/blender_verifier.Dockerfile
  apps/blender/resources/images/entrypoints/render_entrypoint.py
  apps/blender/resources/images/entrypoints/scripts/render_tools/blender_render.py
  apps/blender/resources/images/entrypoints/scripts/render_tools/scenefileeditor.py
  apps/blender/resources/images/entrypoints/scripts/render_tools/templates/blendercrop.py.template
  apps/blender/resources/images/entrypoints/scripts/verifier_tools/__init__.py
  apps/blender/resources/images/entrypoints/scripts/verifier_tools/copy.sh
  apps/blender/resources/images/entrypoints/scripts/verifier_tools/crop_generator.py
  apps/blender/resources/images/entrypoints/scripts/verifier_tools/decision_tree.py
  apps/blender/resources/images/entrypoints/scripts/verifier_tools/edges.py
  apps/blender/resources/images/entrypoints/scripts/verifier_tools/histograms_correlation.py
  apps/blender/resources/images/entrypoints/scripts/verifier_tools/img_format_converter.py
  apps/blender/resources/images/entrypoints/scripts/verifier_tools/img_metrics_calculator.py
  apps/blender/resources/images/entrypoints/scripts/verifier_tools/imgmetrics.py
  apps/blender/resources/images/entrypoints/scripts/verifier_tools/mass_center_distance.py
  apps/blender/resources/images/entrypoints/scripts/verifier_tools/psnr.py
  apps/blender/resources/images/entrypoints/scripts/verifier_tools/requirements.txt
  apps/blender/resources/images/entrypoints/scripts/verifier_tools/skimage.py
  apps/blender/resources/images/entrypoints/scripts/verifier_tools/ssim.py
  apps/blender/resources/images/entrypoints/scripts/verifier_tools/tree35_[crr=87.71][frr=0.92].pkl
  apps/blender/resources/images/entrypoints/scripts/verifier_tools/variance.py
  apps/blender/resources/images/entrypoints/scripts/verifier_tools/verificator.py
  apps/blender/resources/images/entrypoints/scripts/verifier_tools/wavelet.py
  apps/blender/resources/images/entrypoints/verifier_entrypoint.py
  apps/blender/task/blenderrendertask.py
  apps/images.ini
  golem/verificator/blender_verifier.py
  scripts/pyinstaller/hooks/hook-golem.py
  setup.py
  tests/apps/blender/resources/test_scenefileditor.py
  tests/golem/docker/docker-blender-cycles-task.json
  tests/golem/docker/docker-blender-render-task.json
  tests/golem/docker/test_blender_job.py
  tests/golem/docker/test_docker_blender_task.py
  tests/golem/docker/test_docker_environment.py
  tests/golem/verificator/test_blenderverifier.py
Labels: in progress

#3975 Fix and add logs in blender verifier
  golem/verificator/blender_verifier.py
Labels: in progress

#3993 B0.19 to develop
  apps/core/task/coretask.py
  golem/appconfig.py
  golem/client.py
  golem/clientconfigdescriptor.py
  golem/ethereum/fundslocker.py
  golem/ethereum/paymentskeeper.py
  golem/ethereum/transactionsystem.py
  golem/rpc/mapping/rpceventnames.py
  golem/rpc/mapping/rpcmethodnames.py
  golem/task/acl.py
  golem/task/taskmanager.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  tests/golem/task/test_acl.py
  tests/golem/task/test_taskserver.py
  tests/golem/task/test_tasksession.py
  tests/golem/task/test_taskstate.py
  tests/golem/test_client.py
Labels: in progress

#3992 B0.19
  apps/core/task/coretask.py
  golem/appconfig.py
  golem/client.py
  golem/clientconfigdescriptor.py
  golem/ethereum/fundslocker.py
  golem/ethereum/paymentskeeper.py
  golem/ethereum/transactionsystem.py
  golem/rpc/mapping/rpceventnames.py
  golem/rpc/mapping/rpcmethodnames.py
  golem/task/acl.py
  golem/task/taskmanager.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  golem/task/taskstate.py
  tests/golem/task/test_acl.py
  tests/golem/task/test_taskserver.py
  tests/golem/task/test_tasksession.py
  tests/golem/task/test_taskstate.py
  tests/golem/test_client.py
Labels: in progress

#3990 Remove luxrender leftover
  luxrender-output.exr
Labels: in progress

#3997 + additional docs for running node integration tests on a Mac
  scripts/node_integration_tests/README.md
Labels: in progress

#3930 Feature reuse keys and run faster node integration tests
  scripts/node_integration_tests/README.md
  scripts/node_integration_tests/conftest.py
  scripts/node_integration_tests/playbooks/base.py
  scripts/node_integration_tests/tests/base.py
  scripts/node_integration_tests/tests/test_concent.py
Labels: in progress

#3994 Verifier cleanup/add unit tests for coverage
  golem/verificator/blender_verifier.py
  golem/verificator/rendering_verifier.py
  tests/golem/verificator/test_blenderverifier.py
Labels: in progress

#3998 cherry pick of: Feature reuse keys and run faster node integration tests (#3930)
  scripts/node_integration_tests/README.md
  scripts/node_integration_tests/conftest.py
  scripts/node_integration_tests/playbooks/base.py
  scripts/node_integration_tests/tests/base.py
  scripts/node_integration_tests/tests/test_concent.py
Labels: in progress

#4000 bump pyyaml
  requirements.txt
  requirements_to-freeze.txt
Labels: in progress

#3995 Add version to temp dir name
  Installer/Installer_Win/Golem.aip
  scripts/docker/prepare-docker-for-windows.ps1
Labels: in progress

#3991 Keep Golem running after Docker issues at startup
  golem/docker/manager.py
  golem/node.py
  golem/task/rpc.py
  tests/golem/test_opt_node.py
Labels: in progress

#4002 fix an error message when migrating a transaction storage file
  golem/ethereum/transactionsystem.py
Labels: in progress

#4001 B0.19 develop
  requirements.txt
  requirements_to-freeze.txt
  scripts/node_integration_tests/README.md
Labels: in progress

#4007 Improved hint when CLI is ran on wrong chain
  golemcli.py
  tests/golem/interface/test_golemcli.py
Labels: in progress

#3999 Make TaskSession stateless
  golem/task/exceptions.py
  golem/task/tasksession.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#4009 Cherry pick of: Keep Golem running after Docker error at startup (#3991)
  golem/docker/manager.py
  golem/node.py
  golem/task/rpc.py
  tests/golem/test_opt_node.py
Labels: in progress

#4013 Update Product Code
  Installer/Installer_Win/Golem.aip
Labels: in progress

#3982 Refactor simplify classes in terms of verification data usage
  apps/core/verification_task.py
  apps/dummy/benchmark/benchmark.py
  apps/dummy/task/verifier.py
  golem/verificator/blender_verifier.py
  golem/verificator/core_verifier.py
  golem/verificator/rendering_verifier.py
  tests/apps/blender/task/test_blenderrendertask.py
  tests/golem/verificator/test_blenderverifier.py
  tests/golem/verificator/test_core_verifier.py
  tests/golem/verificator/test_renderingverifier.py
Labels: in progress

#3865 Add WebAssembly sandbox task
  apps/images.ini
  apps/registered_test.ini
  apps/wasm/README.md
  apps/wasm/__init__.py
  apps/wasm/benchmark.py
  apps/wasm/environment.py
  apps/wasm/resources/images/Dockerfile
  apps/wasm/resources/images/scripts/job.py
  apps/wasm/task.py
  apps/wasm/test_data/input/test.js
  apps/wasm/test_data/input/test.wasm
  apps/wasm/test_data/input/test_subtask/in.txt
  tests/apps/wasm/__init__.py
  tests/apps/wasm/test_benchmark.py
  tests/apps/wasm/test_job.py
  tests/apps/wasm/test_task.py
  tests/golem/docker/test_docker_manager.py
Labels: in progress

#4014 Fix check_docker_images which always equated to false
  golem/task/tasksession.py
Labels: bug, in progress

#4006 + standard issue template
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: in progress

#3956 Add integretion tests of transcoding
  golem/task/taskmanager.py
  golem/testutils.py
  tests/apps/ffmpeg/task/test_ffmpegintegration.py
Labels: cgi, in progress

#3841 Remove compatibility check based on app version
  golem/task/taskkeeper.py
  tests/golem/task/test_taskkeeper.py
Labels: in progress

#4019 Remove README.md; created Wiki entry instead
  apps/wasm/README.md
Labels: documentation, enhancement, in progress

#4021 Cherry pick of: Disabled virtualization check on Linux (#3949)
  golem/core/virtualization.py
  tests/golem/core/test_virtualization.py
Labels: in progress

#4020 optionally dump node output on fail of a node integration test
  scripts/node_integration_tests/conftest.py
  scripts/node_integration_tests/playbooks/base.py
  scripts/node_integration_tests/run_test.py
  scripts/node_integration_tests/tests/base.py
Labels: in progress

#4026 additional readme for the `--dump-output-*` parameters
  scripts/node_integration_tests/README.md
Labels: in progress

#3977 Interfaces for environments refactoring
  golem/envs/__init__.py
  tests/golem/envs/__init__.py
  tests/golem/envs/test_environment_manager.py
Labels: clay

#4010 Re-enabled un-installing of docker toolbox
  Installer/Installer_Win/Golem.aip
Labels: in progress

#4025 Fixed virtualization detection on Windows
  golem/core/virtualization.py
  golem/docker/hypervisor/hyperv.py
  scripts/pyinstaller/hooks/hook-golem.py
  scripts/virtualization/get-hyperv-state.ps1
  scripts/virtualization/get-virtualization-state.ps1
  tests/golem/core/test_virtualization.py
Labels: in progress

#4030 Additional information in the logs on task failure
  golem/docker/task_thread.py
Labels: in progress

#4012 Fixed Hyper-V VM remaining in invalid state
  golem/docker/commands/docker_machine.py
  golem/docker/hypervisor/docker_machine.py
  golem/docker/hypervisor/hyperv.py
Labels: 0.19.1 release, bug, docker, in progress, windows

#4029 Random hacks of kindness
  apps/core/task/coretask.py
  apps/core/task/coretaskstate.py
  apps/dummy/task/verifier.py
  apps/rendering/task/renderingtask.py
  apps/rendering/task/renderingtaskstate.py
  golem/appconfig.py
  golem/docker/task_thread.py
  golem/network/transport/session.py
  golem/network/transport/tcpnetwork.py
  golem/task/taskserver.py
  golem/verificator/core_verifier.py
  golem/verificator/verifier.py
  tests/apps/core/task/test_coretaskstate.py
  tests/apps/rendering/task/test_renderingtaskstate.py
  tests/golem/docker/docker-blender-cycles-task.json
  tests/golem/docker/docker-blender-render-task.json
  tests/golem/docker/docker-dummy-test-task.json
  tests/golem/network/transport/test_network.py
  tests/golem/task/test_taskserver.py
Labels: in progress

#4031 0.19 to develop
  Installer/Installer_Win/Golem.aip
  golem/core/virtualization.py
  golem/docker/commands/docker_machine.py
  golem/docker/hypervisor/docker_machine.py
  golem/docker/hypervisor/hyperv.py
  golem/docker/task_thread.py
  golem/ethereum/transactionsystem.py
  golemcli.py
  scripts/docker/prepare-docker-for-windows.ps1
  scripts/node_integration_tests/README.md
  scripts/node_integration_tests/conftest.py
  scripts/node_integration_tests/playbooks/base.py
  scripts/node_integration_tests/run_test.py
  scripts/node_integration_tests/tests/base.py
  scripts/pyinstaller/hooks/hook-golem.py
  scripts/virtualization/get-hyperv-state.ps1
  scripts/virtualization/get-virtualization-state.ps1
  tests/golem/core/test_virtualization.py
  tests/golem/interface/test_golemcli.py
  tests/golem/test_opt_node.py
Labels: in progress

#4036 Extended interval between remove VM attempts
  golem/docker/hypervisor/hyperv.py
Labels: 0.19.1 release, bug

#4016 Message Queue Storage
  golem/client.py
  golem/core/variables.py
  golem/database/database.py
  golem/database/schemas/024_create_message_queue.py
  golem/model.py
  golem/network/p2p/p2pservice.py
  golem/network/transport/msg_queue.py
  tests/golem/network/transport/test_msg_queue.py
  tests/golem/task/test_taskserver.py
Labels: in progress

#4037 Create a separate directory for every task's output
  apps/core/task/coretask.py
  scripts/node_integration_tests/playbooks/base.py
  tests/apps/core/task/test_coretask.py
  tests/apps/rendering/task/test_renderingtask.py
  tests/golem/task/test_rpc.py
Labels: in progress

#3986 Simplify overriding structure
  apps/dummy/benchmark/benchmark.py
  golem/verificator/blender_verifier.py
  golem/verificator/core_verifier.py
  golem/verificator/rendering_verifier.py
  tests/golem/verificator/test_blenderverifier.py
  tests/golem/verificator/test_core_verifier.py
  tests/golem/verificator/test_renderingverifier.py
Labels: in progress

#3952 Revive ResourceManagerBase tests
  golem/resource/hyperdrive/resource.py
  tests/golem/resource/hyperdrive/test_hyperdrive_resource.py
  tests/golem/resource/hyperdrive/test_hyperdrive_resourcemanager.py
Labels: in progress, needs review

#4045 Add test for images with different crop edge
  tests/golem/verificator/test_blenderverifier.py
Labels: in progress

#4044 Improved checking Hyper-V status on Windows
  scripts/virtualization/get-hyperv-state.ps1
Labels: in progress

#4053 B0.19 to develop
  golem/docker/hypervisor/hyperv.py
  scripts/virtualization/get-hyperv-state.ps1
Labels: in progress

#4052 Require administrator privilege to run the Windows installer
  Installer/Installer_Win/Golem.aip
Labels: 0.19.1 release, bug, in progress, windows

#4047 [payments processor] currencies in logs
  golem/ethereum/fundslocker.py
  golem/ethereum/paymentprocessor.py
  golem/ethereum/transactionsystem.py
Labels: in progress

#4043 Verifier cleanup/docker sanity check
  apps/blender/resources/images/blender_verifier.Dockerfile
  apps/blender/resources/images/entrypoints/test_entrypoint.py
  golem/verificator/blender_verifier.py
  tests/apps/blender/verification/test_data/chessboard_400x400_5x5.blend
  tests/golem/verificator/test_blenderverifier.py
Labels: in progress

#4055 Add 'raw_verification' method for testing verification crop windows
  apps/blender/resources/images/entrypoints/scripts/verifier_tools/img_metrics_calculator.py
  apps/blender/resources/images/entrypoints/scripts/verifier_tools/verificator.py
  apps/blender/resources/images/entrypoints/test_entrypoint.py
Labels: in progress

#4057 Change 'entrypoint' path in BlenderVerifier test setup
  tests/golem/verificator/test_blenderverifier.py
Labels: in progress
