Repository golemfactory/golem, pull requests merged in 2019-07, with the labels that each got.

#4396 node_integration_tests - Remove repeated part of datadirs
  scripts/node_integration_tests/tests/base.py
Labels: ci & tests, cleanup

#4404 Drop xhyve support
  golem/docker/hypervisor/xhyve.py
  golem/docker/manager.py
  golem/envs/docker/cpu.py
  golem/verificator/common/common.py
  tests/golem/docker/test_docker_manager.py
  tests/golem/docker/test_hypervisor.py
  tests/golem/envs/docker/cpu/test_env.py
Labels: macos

#4428 Windows docker ports
  golem/docker/commands/docker_machine.py
  golem/docker/hypervisor/docker_machine.py
  golem/envs/docker/cpu.py
  tests/golem/docker/test_hypervisor.py
Labels: clay

#4405 Linux installer: kill hyperg-worker and hyperg on upgrade
  Installer/Installer_Linux/install.sh
Labels: 0.20 release

#4177 send multiple TTC in response to multi-WTCT
  apps/core/task/coretask.py
  apps/glambda/task/glambdatask.py
  golem/task/taskbase.py
  golem/task/taskclient.py
  golem/task/taskmanager.py
  golem/task/tasksession.py
  tests/apps/blender/task/test_blenderrendertask.py
  tests/apps/core/benchmark/test_benchmarkrunner.py
  tests/apps/core/task/test_coretask.py
  tests/golem/docker/test_docker_task.py
  tests/golem/task/dummy/task.py
  tests/golem/task/test_taskclient.py
  tests/golem/task/test_taskmanager.py
  tests/golem/task/test_taskserver.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#4436 Updated boot2docker to v18.09.7
  golem/docker/hypervisor/hyperv.py
Labels: clay, docker

#4439 catch exception for `taskcomputer.get_progress` for non-blender tasks
  golem/task/taskcomputer.py
Labels: brass

#4398 Move benchmarks from TaskComputer to TaskServer
  golem/task/benchmarkmanager.py
  golem/task/taskcomputer.py
  golem/task/taskserver.py
  tests/golem/task/test_taskcomputer.py
  tests/golem/task/test_taskserver.py
Labels: clay, cleanup

#4450 A different workaround for missing docker output issue
  golem/envs/docker/cpu.py
Labels: bug, clay, docker

#4449 Stop Golem from crashing on benchmark failure
  apps/glambda/glambdaenvironment.py
  golem/environments/environment.py
Labels: bug

#4452 Docker environment integration tests cleanup
  tests/golem/envs/docker/cpu/test_integration.py
Labels: ci & tests, clay, cleanup, docker

#4455 Added .coveragerc to exclude some lines
  .coveragerc
  golem/core/fileencrypt.py
  golem/core/service.py
  golem/diag/service.py
  golem/docker/environment.py
  golem/envs/__init__.py
  golem/interface/formatters.py
  golem/monitor/model/modelbase.py
  golem/network/transport/network.py
  golem/network/transport/session.py
  golem/network/upnp/mapper.py
  golem/task/acl.py
  golem/task/appcallbacks/appcallbacks.py
  golem/task/result/resultmanager.py
  golem/task/result/resultpackage.py
  golem/task/taskbase.py
  golem/vm/vm.py
  tests/golem/task/test_taskbase.py
  tests/golem/task/test_taskmanager.py
Labels: ci & tests, cleanup

#4486 Small cleanups in task_server and old environments
  golem/environments/environment.py
  golem/task/benchmarkmanager.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  tests/golem/task/test_taskserver.py
Labels: cleanup

#4502 stop sci threads on `concent_acceptance_tests` sci tests' teardown...
  scripts/concent_acceptance_tests/base.py
Labels: concent

#4493 remove unused task_persistance from taskmanager and taskkeeper
  golem/task/server/resources.py
  golem/task/taskkeeper.py
  golem/task/taskmanager.py
  tests/golem/task/test_taskkeeper.py
  tests/golem/task/test_taskmanager.py
Labels: cleanup

#4504 closes https://github.com/golemfactory/golem/issues/4390
  scripts/concent_acceptance_tests/README.md
Labels: concent

#4517 Moved multi line log with task_header to debug
  golem/task/taskserver.py
Labels: cleanup

#4523 fix test
  scripts/node_integration_tests/helpers.py
Labels: brass

#4519 node_integration_tests::multinode_regular_run - Wait for at least one payment per node
  scripts/node_integration_tests/playbooks/golem/multinode_regular_run/playbook.py
Labels: ci & tests

#4520 Mark test_fails as skip since it is expected to fail
  scripts/node_integration_tests/tests/test_fails.py
Labels: ci & tests

#4540 Removed unused utility functions
  golem/utils.py
  tests/golem/test_golem_utils.py
Labels: cleanup

#4542 Fix task status when not enough funds are available
  golem/task/rpc.py
  golem/task/taskmanager.py
  tests/golem/task/test_rpc.py
Labels: bug

#4417 Asyncio reactor
  golem/core/common.py
  golem/node.py
  golem/rpc/__init__.py
  golem/rpc/cert.py
  golem/rpc/router.py
  golemapp.py
  requirements-build.txt
  requirements-lint.txt
  requirements-test.txt
  requirements.txt
  requirements_to-freeze.txt
  scripts/node_integration_tests/nodes/json_serializer.py
  scripts/node_integration_tests/nodes/node.py
  scripts/node_integration_tests/nodes/provider/cannot_compute.py
  scripts/node_integration_tests/nodes/provider/day_backwards.py
  scripts/node_integration_tests/nodes/provider/impatient_frct.py
  scripts/node_integration_tests/nodes/provider/no_wtct_after_ttc.py
  scripts/node_integration_tests/nodes/requestor/always_accept_provider.py
  scripts/node_integration_tests/nodes/requestor/day_backwards_dont_pay.py
  scripts/node_integration_tests/nodes/requestor/dont_pay.py
  scripts/node_integration_tests/nodes/requestor/fail_results.py
  scripts/node_integration_tests/nodes/requestor/no_ack_rct.py
  scripts/node_integration_tests/nodes/requestor/no_sra.py
  scripts/node_integration_tests/nodes/requestor/reject_results.py
  scripts/node_integration_tests/playbooks/base.py
  tests/golem/rpc/test_cert.py
  tests/golem/test_opt_node.py
  tests/test_golemapp.py
Labels: P1

#4544 Make the Concent Service optional from Provider's POV
  golem/network/concent/client.py
  golem/network/concent/soft_switch.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  scripts/node_integration_tests/playbooks/base.py
  scripts/node_integration_tests/playbooks/concent/concent_base.py
  scripts/node_integration_tests/playbooks/concent/concent_config_base.py
  scripts/node_integration_tests/playbooks/golem/concent/__init__.py
  scripts/node_integration_tests/playbooks/golem/concent/playbook.py
  scripts/node_integration_tests/playbooks/golem/concent/test_config.py
  scripts/node_integration_tests/playbooks/golem/concent_provider/__init__.py
  scripts/node_integration_tests/playbooks/golem/concent_provider/playbook.py
  scripts/node_integration_tests/playbooks/golem/concent_provider/test_config.py
  scripts/node_integration_tests/playbooks/golem/jpg/test_config.py
  scripts/node_integration_tests/playbooks/golem/rpc_test/concent/test_config.py
  scripts/node_integration_tests/playbooks/golem/task_timeout/playbook.py
  scripts/node_integration_tests/playbooks/test_config_base.py
  scripts/node_integration_tests/run_test.py
  scripts/node_integration_tests/tasks/__init__.py
  scripts/node_integration_tests/tests/test_golem.py
  tests/golem/network/concent/test_soft_switch.py
  tests/golem/task/test_concent_logic.py
  tests/golem/task/test_taskserver.py
Labels: brass, concent

#4501 Implement new env performance before sending WTCT
  golem/task/envmanager.py
  golem/task/taskkeeper.py
  golem/task/taskmanager.py
  golem/task/taskserver.py
  tests/golem/task/test_envmanager.py
  tests/golem/task/test_taskkeeper.py
  tests/golem/task/test_taskserver.py
  tests/golem/task/test_tasksession.py
Labels: clay

#4510 New TaskComputer
  golem/core/deferred.py
  golem/task/taskcomputer.py
  golem/task/taskserver.py
  requirements_to-freeze.txt
  tests/golem/core/test_deferred.py
  tests/golem/network/p2p/test_peersession.py
  tests/golem/resource/base/common.py
  tests/golem/task/dummy/task.py
  tests/golem/task/dummy/test_runner_script.py
  tests/golem/task/test_localcomputer.py
  tests/golem/task/test_newtaskcomputer.py
  tests/golem/task/test_rpc.py
  tests/golem/task/test_taskcomputer.py
  tests/golem/task/test_taskcomputeradapter.py
  tests/golem/task/test_taskserver.py
Labels: clay
