Repository golemfactory/golem, pull requests merged in 2019-02, with the labels that each got.

#3840 + actual payment check
  scripts/node_integration_tests/helpers.py
  scripts/node_integration_tests/playbooks/base.py
  scripts/node_integration_tests/playbooks/concent/force_payment.py
Labels: concent, in progress

#3847 Add check that only peers with valid address are returned
  golem/network/p2p/p2pservice.py
  tests/golem/network/p2p/test_p2pservice.py
Labels: in progress

#3848 Remove unused DummyVerifier
  golem/verificator/dummy_verifier.py
  tests/golem/verificator/test_dummyverifier.py
Labels: in progress

#3852 Fix resource package subdirectories
  golem/task/result/resultpackage.py
  tests/golem/task/result/test_resultpackage.py
Labels: 0.19 release, bug, in progress

#3855 Checking task deadline when restoring from pickle
  golem/task/taskmanager.py
  tests/golem/task/test_taskmanager.py
Labels: in progress

#3861 Revert checking task deadline when unpickling
  golem/task/taskmanager.py
  tests/golem/task/test_taskmanager.py
Labels: in progress

#3863 Disable removing old tasks by default
  golem/appconfig.py
  golem/client.py
Labels: in progress

#3845 start_docker None deferred fix
  golem/node.py
  tests/golem/test_opt_node.py
Labels: in progress

#3857 Use native SSH in docker-machine
  golem/docker/commands/docker_machine.py
  golem/docker/hypervisor/hyperv.py
  scripts/docker/start-hyperv-docker-vm.ps1
  scripts/pyinstaller/hooks/hook-golem.py
  tests/golem/docker/test_hyperv.py
Labels: 0.19 release, bug, docker, in progress, windows

#3715 Move validations from enqueue_new_task method before it in create_task
  golem/ethereum/fundslocker.py
  golem/ethereum/transactionsystem.py
  golem/task/rpc.py
  golem/task/tasksession.py
  tests/golem/ethereum/test_transactionsystem.py
  tests/golem/task/test_rpc.py
Labels: in progress

#3843 Update Golem-Verificator to 1.6.3.2
  apps/images.ini
  requirements.txt
  requirements_to-freeze.txt
Labels: in progress

#3866 Added -PasswordNeverExpires flag to New-LocalUser
  scripts/docker/prepare-docker-for-windows.ps1
Labels: 0.19 release, bug, docker, in progress, windows

#3864 Fix subscription to batch transfers
  golem/ethereum/transactionsystem.py
  tests/golem/ethereum/test_transactionsystem.py
Labels: in progress

#3875 Remove unnecessary attributes from TaskSession
  golem/resource/resourcehandshake.py
  golem/task/tasksession.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#3849 Move logs
  golem/task/rpc.py
Labels: bug, in progress

#3876 Collect transcoding results
  apps/transcoding/common.py
  apps/transcoding/ffmpeg/resources/ffmpeg-scripts/ffmpeg_commands.py
  apps/transcoding/ffmpeg/task.py
  apps/transcoding/ffmpeg/utils.py
  apps/transcoding/task.py
  golem/verificator/ffmpeg_verifier.py
  tests/apps/ffmpeg/task/test_ffmpegtask.py
  tests/apps/ffmpeg/task/test_fmmpegtranscoding.py
  tests/golem/docker/test_docker_manager.py
  tests/golem/verificator/test_ffmpeg_verifier.py
Labels: cgi, in progress

#3744 Remove GetResources and ResourceList message
  apps/core/task/coretask.py
  golem/task/server/resources.py
  golem/task/taskcomputer.py
  golem/task/taskkeeper.py
  golem/task/tasksession.py
  requirements.txt
  requirements_to-freeze.txt
  tests/golem/resource/base/common.py
  tests/golem/task/dummy/task.py
  tests/golem/task/server/test_resources.py
  tests/golem/task/test_taskcomputer.py
  tests/golem/task/test_taskkeeper.py
  tests/golem/task/test_tasksession.py
Labels: in progress, needs review

#3884 bump messages to 2.24.3
  requirements.txt
  requirements_to-freeze.txt
Labels: brass, in progress

#3878 Prevent loading default clean interval from old config
  golem/appconfig.py
  golem/client.py
  golem/clientconfigdescriptor.py
  tests/golem/test_client.py
Labels: in progress

#3885 Bump version to 0.19.0
  Installer/Installer_Win/Golem.aip
Labels: in progress

#3887 fix logging message
  golem/task/taskmanager.py
Labels: in progress

#3886 Add `sleep` in `RequestorPaysTest` tests
  scripts/concent_acceptance_tests/base.py
  scripts/concent_acceptance_tests/force_payment/test_payment.py
Labels: in progress

#3888 Properly break task selection algorithm to ask for subtasks
  golem/task/taskserver.py
  golem/task/tasksession.py
  tests/golem/task/test_taskserver.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#3891 Remove PeerManager artefacts
  golem/client.py
  golem/task/server/resources.py
  golem/task/tasksession.py
Labels: in progress

#3889 Enabled frame restarts on finished tasks
  golem/client.py
  golem/task/rpc.py
  golem/task/taskmanager.py
  tests/golem/task/test_rpc.py
  tests/golem/task/test_taskmanager.py
  tests/golem/test_client.py
Labels: in progress

#3894 Added integration test for frame restarts
  golem/task/rpc.py
  scripts/node_integration_tests/nodes/requestor/always_accept_provider.py
  scripts/node_integration_tests/playbooks/golem/restart_frame.py
  scripts/node_integration_tests/tests/test_golem.py
  tests/golem/task/test_rpc.py
Labels: in progress

#3897 B0.19 to develop
  golem/client.py
  golem/task/rpc.py
  golem/task/taskmanager.py
  scripts/node_integration_tests/nodes/requestor/always_accept_provider.py
  scripts/node_integration_tests/playbooks/golem/restart_frame.py
  scripts/node_integration_tests/tests/test_golem.py
  tests/golem/task/test_rpc.py
  tests/golem/task/test_taskmanager.py
  tests/golem/test_client.py
Labels: in progress

#3844 Use different Docker image for blender verification
  apps/blender/blender_reference_generator.py
  apps/blender/resources/images/blender_verifier.Dockerfile
  apps/blender/resources/images/scripts_verifier/__init__.py
  apps/blender/resources/images/scripts_verifier/copy.sh
  apps/blender/resources/images/scripts_verifier/crop_generator.py
  apps/blender/resources/images/scripts_verifier/decision_tree.py
  apps/blender/resources/images/scripts_verifier/edges.py
  apps/blender/resources/images/scripts_verifier/histograms_correlation.py
  apps/blender/resources/images/scripts_verifier/img_format_converter.py
  apps/blender/resources/images/scripts_verifier/img_metrics_calculator.py
  apps/blender/resources/images/scripts_verifier/imgmetrics.py
  apps/blender/resources/images/scripts_verifier/mass_center_distance.py
  apps/blender/resources/images/scripts_verifier/psnr.py
  apps/blender/resources/images/scripts_verifier/requirements.txt
  apps/blender/resources/images/scripts_verifier/runner.py
  apps/blender/resources/images/scripts_verifier/skimage.py
  apps/blender/resources/images/scripts_verifier/ssim.py
  apps/blender/resources/images/scripts_verifier/tree35_[crr=87.71][frr=0.92].pkl
  apps/blender/resources/images/scripts_verifier/variance.py
  apps/blender/resources/images/scripts_verifier/verificator.py
  apps/blender/resources/images/scripts_verifier/wavelet.py
  apps/blender/task/blenderrendertask.py
  apps/core/task/coretask.py
  apps/images.ini
  golem/verificator/blender_verifier.py
  golem/verificator/rendering_verifier.py
  golem/verificator/verifier.py
  tests/apps/blender/task/test_blenderrendertask.py
  tests/apps/blender/verification/test_blender_reference_generator.py
  tests/apps/blender/verification/test_verification_queue.py
  tests/apps/blender/verification/test_verificator_integration.py
  tests/golem/verificator/test_blenderverifier.py
  tests/golem/verificator/test_renderingverifier.py
Labels: in progress

#3903 Do not ban providers on CannotComputeTask (OfferCancelled)
  apps/core/task/coretask.py
  apps/rendering/task/framerenderingtask.py
  apps/rendering/task/renderingtask.py
  golem/appconfig.py
  golem/clientconfigdescriptor.py
  golem/task/taskbase.py
  golem/task/taskclient.py
  golem/task/taskmanager.py
  golem/task/tasksession.py
  golem/task/taskstate.py
  tests/apps/core/benchmark/test_benchmarkrunner.py
  tests/golem/task/dummy/task.py
  tests/golem/task/test_taskmanager.py
  tests/golem/task/test_tasksession.py
Labels: in progress, needs review

#3896 TaskSession almost stateless
  apps/core/task/coretask.py
  golem/task/server/resources.py
  golem/task/taskbase.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  golem/task/taskstate.py
  requirements.txt
  requirements_to-freeze.txt
  tests/golem/task/dummy/task.py
  tests/golem/task/server/test_resources.py
  tests/golem/task/test_taskserver.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#3901 Merge video
  apps/transcoding/ffmpeg/environment.py
  apps/transcoding/ffmpeg/resources/ffmpeg-scripts/ffmpeg_commands.py
  apps/transcoding/ffmpeg/resources/ffmpeg-scripts/ffmpeg_task.py
  apps/transcoding/ffmpeg/resources/ffmpeg-scripts/m3u8_utils.py
  apps/transcoding/ffmpeg/utils.py
  apps/transcoding/task.py
  tests/apps/ffmpeg/task/test_ffmpegtask.py
  tests/apps/ffmpeg/task/test_fmmpegtranscoding.py
Labels: cgi, in progress

#3909 Cleanup apps/rendering/resources
  apps/rendering/resources/images/Dockerfile
  apps/rendering/resources/images/requirements.txt
  apps/rendering/resources/scripts/__init__.py
  apps/rendering/resources/scripts/decision_tree.py
  apps/rendering/resources/scripts/img_format_converter.py
  apps/rendering/resources/scripts/img_metrics_calculator.py
  apps/rendering/resources/scripts/imgmetrics.py
  apps/rendering/resources/scripts/metrics/__init__.py
  apps/rendering/resources/scripts/metrics/edges.py
  apps/rendering/resources/scripts/metrics/histograms_correlation.py
  apps/rendering/resources/scripts/metrics/mass_center_distance.py
  apps/rendering/resources/scripts/metrics/psnr.py
  apps/rendering/resources/scripts/metrics/ssim.py
  apps/rendering/resources/scripts/metrics/variance.py
  apps/rendering/resources/scripts/metrics/wavelet.py
  apps/rendering/resources/scripts/runner.py
  apps/rendering/resources/scripts/tree35_[crr=87.71][frr=0.92].pkl
  scripts/pyinstaller/hooks/hook-golem.py
  tests/golem/verificator/test_blenderverifier.py
Labels: in progress

#3904 Fix concent node integration tests
  golem/task/tasksession.py
  scripts/node_integration_tests/playbooks/concent/force_accept.py
Labels: in progress

#3912 make the node control scripts/playbooks more universal
  scripts/node_integration_tests/helpers.py
  scripts/node_integration_tests/playbooks/base.py
Labels: in progress

#3922 feat: change video & audio codec
  apps/transcoding/common.py
  apps/transcoding/ffmpeg/resources/ffmpeg-scripts/ffmpeg_commands.py
  tests/apps/ffmpeg/task/test_ffmpegtask.py
Labels: cgi, in progress

#3919 ....... don't even...
  scripts/node_integration_tests/helpers.py
Labels: in progress

#3921 Try explicit exit 0 at the end of the script
  scripts/docker/prepare-docker-for-windows.ps1
Labels: in progress

#3910 Update develop with latest from b0.19
  Installer/Installer_Linux/install.sh
  apps/core/task/coretask.py
  apps/rendering/task/framerenderingtask.py
  apps/rendering/task/renderingtask.py
  golem/appconfig.py
  golem/clientconfigdescriptor.py
  golem/task/taskbase.py
  golem/task/taskclient.py
  golem/task/taskmanager.py
  golem/task/tasksession.py
  golem/task/taskstate.py
  scripts/docker/prepare-docker-for-windows.ps1
  scripts/node_integration_tests/helpers.py
  scripts/node_integration_tests/playbooks/base.py
  scripts/node_integration_tests/playbooks/concent/force_accept.py
  tests/apps/core/benchmark/test_benchmarkrunner.py
  tests/golem/task/dummy/task.py
  tests/golem/task/test_taskmanager.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#3931 Fixed folder name in readme
  scripts/concent_acceptance_tests/README.md
Labels: in progress

#3934 Differentiate provider reaction to CAT
  golem/task/taskcomputer.py
  golem/task/taskkeeper.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  requirements.txt
  requirements_to-freeze.txt
  tests/golem/task/test_taskcomputer.py
  tests/golem/task/test_taskserver.py
  tests/golem/task/test_tasksession.py
Labels: in progress
