Repository golemfactory/golem, pull requests merged in 2019-04, with the labels that each got.

#4062 Fix additional_verification Concent acceptance test
  scripts/concent_acceptance_tests/additional_verification/base.py
Labels: in progress

#4011 Verifier cleanup/bugfix crop workaround
  apps/blender/resources/images/entrypoints/scripts/verifier_tools/crop_generator.py
  apps/blender/resources/images/entrypoints/scripts/verifier_tools/img_metrics_calculator.py
  apps/blender/resources/images/entrypoints/scripts/verifier_tools/verificator.py
  apps/blender/resources/images/entrypoints/verifier_entrypoint.py
Labels: in progress

#4071 Update Wasm sandbox to v0.2.0
  apps/wasm/environment.py
  apps/wasm/resources/images/Dockerfile
Labels: in progress

#4072 update ToS
  golem/CONCENT_TERMS.html
  golem/TERMS.html
  golem/terms.py
Labels: 0.19.1 release, in progress

#4064 Install as admin
  Installer/Installer_Win/Golem.aip
  scripts/docker/prepare-docker-as-admin.ps1
  scripts/docker/prepare-docker-for-windows.ps1
  scripts/run-as-admin.ps1
Labels: 0.19.1 release, bug, in progress, windows

#4063 Add test with random crop window of a subtask
  apps/blender/resources/images/entrypoints/test_entrypoint.py
  tests/golem/verificator/test_blenderverifier.py
Labels: in progress

#4078 Always use long Windows paths for shared directories
  golem/docker/smbshare.py
  scripts/docker/create-share.ps1
  tests/golem/docker/test_smbshare.py
Labels: 0.19.1 release, bug, docker, in progress, windows

#4068 Fix ffmpeg integration tests splitting file twice in setup
  tests/apps/ffmpeg/task/test_ffmpegtask.py
Labels: in progress

#4080 B0.19
  Installer/Installer_Win/Golem.aip
  golem/CONCENT_TERMS.html
  golem/TERMS.html
  golem/docker/smbshare.py
  golem/terms.py
  scripts/docker/create-share.ps1
  scripts/docker/prepare-docker-as-admin.ps1
  scripts/docker/prepare-docker-for-windows.ps1
  scripts/run-as-admin.ps1
  tests/golem/docker/test_smbshare.py
Labels: in progress

#4076 Update wasm in images.ini to v0.2.0
  apps/images.ini
Labels: in progress

#4082 fix "unacceptable" characters ;p
  golem/TERMS.html
  tests/golem/test_terms.py
Labels: in progress

#4084 B0.19
  golem/TERMS.html
  tests/golem/test_terms.py
Labels: in progress

#4087 Update Advanced installer config
  Installer/Installer_Win/Golem.aip
Labels: in progress

#4089 Fix linter breakage and warning filtering
  lintdiff.sh
Labels: in progress

#4050 ResourceHandshake stateless
  golem/client.py
  golem/database/database.py
  golem/database/schemas/025_create_node_cache.py
  golem/decorators.py
  golem/model.py
  golem/network/nodeskeeper.py
  golem/network/transport/msg_queue.py
  golem/resource/resourcehandshake.py
  golem/task/server/queue.py
  golem/task/server/resources.py
  golem/task/taskkeeper.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  scripts/test-fill-nodeskeeper.py
  tests/golem/resource/test_resourcehandshake.py
  tests/golem/task/server/test_queue.py
  tests/golem/task/server/test_resources.py
  tests/golem/task/test_taskserver.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#4091 revert lintdiff change
  lintdiff.sh
Labels: in progress

#4054 Enable HyperG to work using arbitrary ports
  golem/appconfig.py
  golem/client.py
  golem/clientconfigdescriptor.py
  golem/docker/task_thread.py
  golem/network/hyperdrive/client.py
  golem/network/hyperdrive/daemon_manager.py
  golem/resource/hyperdrive/resourcesmanager.py
  golem/task/taskmanager.py
  golem/task/taskserver.py
  golem/testutils.py
  golemapp.py
  scripts/node_integration_tests/playbooks/base.py
  tests/apps/blender/verification/test_verification_queue.py
  tests/factories/hyperdrive.py
  tests/golem/docker/test_docker_dummy_task.py
  tests/golem/docker/test_docker_image.py
  tests/golem/network/hyperdrive/test_hyperdrive_client.py
  tests/golem/network/hyperdrive/test_hyperdrive_daemon_manager.py
  tests/golem/resource/base/common.py
  tests/golem/resource/base/test_base_resourceserver.py
  tests/golem/resource/hyperdrive/test_hyperdrive_resourcemanager.py
  tests/golem/resource/test_resourcehandshake.py
  tests/golem/task/result/test_resultmanager.py
  tests/golem/task/test_taskmanager.py
  tests/golem/task/test_taskserver.py
  tests/golem/test_client.py
Labels: brass, in progress

#4093 0.19 hyperg port
  golem/appconfig.py
  golem/client.py
  golem/clientconfigdescriptor.py
  golem/docker/task_thread.py
  golem/network/hyperdrive/client.py
  golem/network/hyperdrive/daemon_manager.py
  golem/resource/hyperdrive/resourcesmanager.py
  golem/task/taskmanager.py
  golem/task/taskserver.py
  golem/testutils.py
  golemapp.py
  tests/apps/blender/verification/test_verification_queue.py
  tests/factories/hyperdrive.py
  tests/golem/docker/test_docker_dummy_task.py
  tests/golem/docker/test_docker_image.py
  tests/golem/network/hyperdrive/test_hyperdrive_client.py
  tests/golem/network/hyperdrive/test_hyperdrive_daemon_manager.py
  tests/golem/resource/base/common.py
  tests/golem/resource/base/test_base_resourceserver.py
  tests/golem/resource/hyperdrive/test_hyperdrive_resourcemanager.py
  tests/golem/resource/test_resourcehandshake.py
  tests/golem/task/result/test_resultmanager.py
  tests/golem/task/test_taskmanager.py
  tests/golem/task/test_taskserver.py
  tests/golem/test_client.py
Labels: in progress

#4081 Fix handling task output directories
  apps/core/task/coretask.py
  golem/task/taskmanager.py
  golem/testutils.py
  tests/apps/core/task/test_coretask.py
  tests/golem/docker/docker-blender-cycles-task.json
  tests/golem/docker/docker-blender-render-task.json
  tests/golem/docker/docker-dummy-test-task.json
  tests/golem/task/test_taskmanager.py
  tests/golem/task/test_taskserver.py
  tests/golem/test_client.py
Labels: in progress

#4094 Call p2pservice.connect_network() once on start
  golem/client.py
  golem/network/p2p/p2pservice.py
  golem/network/p2p/peersession.py
  golem/network/transport/session.py
Labels: in progress

#4092 Fix linter breakage and warning filtering (attempt 2)
  lintdiff.sh
Labels: in progress

#4018 Completed the rename from private to public
  scripts/concent_acceptance_tests/base.py
  scripts/concent_acceptance_tests/force_payment/test_payment.py
Labels: in progress

#4085 Fix connection failure handler for verification
  golem/task/taskserver.py
  tests/golem/task/test_taskserver.py
Labels: in progress

#4083 New approach for privilege elevation in create-share.ps1
  scripts/docker/create-share.ps1
Labels: bug, docker, windows

#4100 Raise timeout from 60 to 120 to give slower machines time to finish
  golem/docker/smbshare.py
Labels: in progress

#4079 Update README.md
  README.md
Labels: in progress

#4103 0.19 result larger than res
  scripts/node_integration_tests/helpers.py
  scripts/node_integration_tests/nodes/provider/separate_hyperg.py
  scripts/node_integration_tests/playbooks/golem/separate_hyperg.py
  scripts/node_integration_tests/tasks/__init__.py
  scripts/node_integration_tests/tasks/cubes/cubes.blend
  scripts/node_integration_tests/tests/test_golem.py
Labels: in progress

#4109 Handle empty node_info in Hello
  golem/core/variables.py
  golem/task/tasksession.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#4112 Handle bogus nodes in payments DB
  golem/model.py
Labels: in progress

#4110 Move _handshake_timeout to server
  golem/core/variables.py
  golem/resource/resourcehandshake.py
  golem/task/server/resources.py
  tests/golem/resource/test_resourcehandshake.py
  tests/golem/task/server/test_resources.py
Labels: in progress

#4119 Set DNS servers for the Docker daemon on macOS
  golem/docker/hypervisor/docker_for_mac.py
  tests/golem/docker/test_hypervisor.py
Labels: in progress, needs review

#4113 DockerJob: Fix container command for Windows
  golem/docker/job.py
Labels: in progress

#4033 SM 6.2 and 7.5 filters + kernels for Cycles
  apps/blender/blenderenvironment.py
  apps/blender/resources/images/blender_nvgpu.Dockerfile
  apps/core/resources/images/nvgpu.Dockerfile
  apps/images.ini
Labels: GPU, needs review

#4115 Retrieve samples parameter on 'comp.task' RPC
  apps/blender/task/blenderrendertask.py
  tests/apps/blender/task/test_blenderrendertask.py
Labels: in progress

#4120 Created task fragments RPC
  golem/task/rpc.py
  tests/golem/task/test_rpc.py
Labels: in progress

#4046 Created integration test for task output directories
  scripts/node_integration_tests/playbooks/base.py
  scripts/node_integration_tests/playbooks/golem/task_output/__init__.py
  scripts/node_integration_tests/playbooks/golem/task_output/playbook.py
  scripts/node_integration_tests/playbooks/golem/task_output/test_config.py
  scripts/node_integration_tests/tests/test_golem.py
Labels: in progress

#4101 duplicate p2psession fix cherry-picked to b0.19
  golem/client.py
  golem/network/p2p/p2pservice.py
  golem/network/p2p/peersession.py
  golem/network/transport/session.py
Labels: in progress

#4124 'TaskServer' object has no attribute 'key_id'
  golem/task/server/resources.py
  tests/golem/task/server/test_resources.py
Labels: in progress

#3421 Removed legacy version file
  Installer/Installer_Win/version.py
Labels: needs review

#4122 Cleaned up typing for linter errors in taskkeeper
  golem/task/taskkeeper.py
Labels: cleanup, in progress

#4125 Bump wasm sandbox version to 0.2.1
  apps/images.ini
  apps/wasm/environment.py
  apps/wasm/resources/images/Dockerfile
Labels: in progress

#4128 Task is finished when it's not active
  golem/task/taskmanager.py
  golem/task/tasksession.py
  tests/golem/task/test_concent_logic.py
  tests/golem/task/test_taskmanager.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#4111 Message Queue
  golem/core/common.py
  golem/network/p2p/p2pservice.py
  golem/network/p2p/peersession.py
  golem/network/transport/msg_queue.py
  golem/task/acl.py
  golem/task/server/helpers.py
  golem/task/server/queue.py
  golem/task/server/queue_.py
  golem/task/server/resources.py
  golem/task/server/verification.py
  golem/task/taskcomputer.py
  golem/task/taskmanager.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  golem/testutils.py
  requirements.txt
  requirements_to-freeze.txt
  tests/factories/taskserver.py
  tests/golem/network/test_nodeskeeper.py
  tests/golem/task/dummy/runner.py
  tests/golem/task/dummy/task.py
  tests/golem/task/dummy/test_runner_script.py
  tests/golem/task/server/test_helpers.py
  tests/golem/task/server/test_queue.py
  tests/golem/task/test_concent_logic.py
  tests/golem/task/test_taskcomputer.py
  tests/golem/task/test_taskmanager.py
  tests/golem/task/test_taskserver.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#4135 Only ask for new tETH donation when half of donated funds are used
  golem/ethereum/transactionsystem.py
Labels: in progress

#3860 Create DockerWhitelist class
  golem/database/database.py
  golem/database/schemas/026_create_docker_whitelist.py
  golem/envs/__init__.py
  golem/envs/docker/cpu.py
  golem/envs/docker/whitelist.py
  golem/model.py
  tests/golem/envs/docker/cpu/test_env.py
  tests/golem/envs/docker/test_whitelist.py
Labels: in progress

#4141 Update README.md
  scripts/node_integration_tests/README.md
Labels: in progress

#4138 Added more detailed error info to task creation RPC
  golem/ethereum/exceptions.py
  golem/ethereum/transactionsystem.py
  golem/interface/client/tasks.py
  golem/task/rpc.py
  tests/golem/ethereum/test_exceptions.py
  tests/golem/ethereum/test_transactionsystem.py
  tests/golem/task/test_rpc.py
Labels: in progress

#4127 Issue template for new features
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/new-feature.md
Labels: in progress

#4137 sign promissory notes in TTC and SRV
  golem/task/tasksession.py
  requirements.txt
  requirements_to-freeze.txt
  tests/golem/task/test_concent_logic.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#4144 Make node_integration_tests green on buildbot.
  scripts/node_integration_tests/playbooks/golem/exr.py
  scripts/node_integration_tests/playbooks/golem/jpeg.py
  scripts/node_integration_tests/playbooks/golem/jpg/test_config.py
  scripts/node_integration_tests/playbooks/golem/restart_frame/test_config.py
  scripts/node_integration_tests/playbooks/golem/task_timeout/test_config.py
  scripts/node_integration_tests/playbooks/test_config_base.py
  scripts/node_integration_tests/tests/test_golem.py
Labels: brass, ci & tests, in progress

#4142 Added support for estimation of task restart cost
  golem/task/rpc.py
  tests/golem/task/test_rpc.py
Labels: in progress

#4017 Allow to push resources after query_extra_data
  golem/task/rpc.py
  golem/task/tasksession.py
  tests/golem/task/test_concent_logic.py
  tests/golem/task/test_tasksession.py
Labels: needs review
