Repository golemfactory/golem, pull requests merged in 2019-11, with the labels that each got.

#4842 A different approach to TaskServer.quit
  golem/client.py
  golem/task/taskserver.py
Labels: bug, clay

#4849 Fix shutdown issues in TaskServer tests
  golem/task/taskcomputer.py
  tests/golem/envs/localhost.py
  tests/golem/task/test_taskserver.py
Labels: clay

#4817 Use App Definition in task_api_tests/basic_integration.py
  scripts/task_api_tests/basic_integration.py
Labels: clay

#4848 Update to Task API v0.23.0
  golem/apps/default.py
  golem/task/requestedtaskmanager.py
  requirements.txt
  requirements_to-freeze.txt
  scripts/node_integration_tests/tasks/__init__.py
  tests/golem/task/test_requestedtaskmanager.py
Labels: clay

#4870 Fixed: requestor prerequisites never installed in RequestedTaskManager
  golem/task/requestedtaskmanager.py
  tests/golem/task/test_requestedtaskmanager.py
Labels: bug

#4864 Common RPC call for creating tasks
  golem/task/requestedtaskmanager.py
  golem/task/rpc.py
  scripts/node_integration_tests/helpers.py
  scripts/node_integration_tests/playbooks/golem/task_api.py
  scripts/node_integration_tests/playbooks/golem/task_api/playbook.py
  scripts/node_integration_tests/tasks/__init__.py
  tests/golem/task/test_rpc_task_api.py
Labels: clay

#4815 update FrameState when restarting task
  apps/rendering/task/framerenderingtask.py
  golem/task/taskbase.py
  golem/task/taskmanager.py
Labels: 0.21 release

#4868 Dump docker logs
  golem/core/common.py
  golem/envs/__init__.py
  golem/envs/auto_setup.py
  golem/envs/docker/cpu.py
  golem/envs/wrappers/__init__.py
  golem/envs/wrappers/auto_setup.py
  golem/envs/wrappers/dump_logs.py
  golem/task/envmanager.py
  golem/task/task_api/__init__.py
  golem/task/taskserver.py
  scripts/task_api_tests/basic_integration.py
  tests/golem/envs/localhost.py
  tests/golem/envs/test_auto_setup.py
  tests/golem/task/server/test_queue.py
  tests/golem/task/test_appbenchmarkmanager.py
  tests/golem/task/test_envmanager.py
  tests/golem/task/test_taskkeeper.py
Labels: clay

#4880 Fix for Task API mainnet benchmarks
  golem/task/taskcomputer.py
Labels: bug

#4881 Fix: Check whether env is registered in EnvironmentManager.enabled
  golem/task/envmanager.py
Labels: bug

#4876 Fixed DummyHypervisor port mapping for Windows
  golem/docker/hypervisor/dummy.py
  tests/golem/docker/test_hypervisor.py
Labels: bug, clay, docker, windows

#4887 Fixed integration test for DockerCPUEnvironment
  golem/docker/hypervisor/__init__.py
  tests/golem/envs/docker/cpu/test_integration.py
Labels: bug, ci & tests, clay, docker

#4895 Convert mask from and to bytes while decreasing
  golem/client.py
  golem/task/requestedtaskmanager.py
Labels: bug

#4893 Fix: client.get_subtask
  golem/client.py
Labels: bug

#4897 Fix: add a `app_id in self._apps` check to AppManager.enabled
  golem/apps/manager.py
Labels: bug, clay

#4903 Fix: Task API 'comp.task.subtask' RPC call compatibility
  golem/client.py
  golem/task/requestedtaskmanager.py
  golem/task/server/verification.py
  tests/golem/task/server/test_verification.py
Labels: bug, clay

#4907 Fix: Only disable new apps in AppManager.register_app
  golem/apps/manager.py
Labels: bug, clay

#4910 Fix: use system time instead of UTC in ResourceManager.share
  golem/resource/resourcemanager.py
  tests/golem/resource/test_resourcemanager.py
Labels: bug, clay

#4894 Restore task-api task timeouts after restarting node
  golem/client.py
  golem/task/requestedtaskmanager.py
  tests/golem/task/test_requestedtaskmanager.py
Labels: bug

#4914 Fix: disable only new envs in EnvironmentManager.register_env
  golem/task/envmanager.py
Labels: bug, clay

#4916 b0.22 - e2e - Updated verification to new dict format of task-api tasks
  scripts/node_integration_tests/playbooks/base.py
  scripts/node_integration_tests/tasks/__init__.py
Labels: 0.22 release

#4926 Add subtask_budget to task-api task_headers
  golem/task/taskserver.py
  tests/golem/task/test_taskserver.py
Labels: 0.22 release

#4938 Return timestamp instead of datetime.datetime()
  golem/client.py
Labels: 0.22 release

#4937 b0.22 - task-api - Take peers from resources_options['options']
  golem/resource/resourcemanager.py
  golem/task/taskserver.py
Labels: 0.22 release

#4927 Fix: execute _resource_downloaded on successful resource download
  golem/task/taskserver.py
Labels: 0.22 release, bug, clay

#4940 Task API task control RPC calls
  golem/client.py
  golem/core/golem_async.py
  golem/node.py
  golem/task/requestedtaskmanager.py
  golem/task/rpc.py
  tests/factories/task/requestedtaskmanager.py
  tests/golem/core/test_golem_async.py
  tests/golem/task/test_requestedtaskmanager.py
  tests/golem/task/test_rpc.py
  tests/golem/task/test_rpc_task_api.py
  tests/golem/test_client.py
Labels: 0.22 release, bug, clay
