Repository golemfactory/golem, pull requests merged in 2019-01, with the labels that each got.

#3632 Change params.py to params.json
  apps/blender/resources/scripts/docker_blendertask.py
  apps/dummy/resources/scripts/docker_dummytask.py
  golem/docker/job.py
  golem/task/taskthread.py
  requirements.txt
  requirements_to-freeze.txt
  tests/golem/docker/test_docker_job.py
Labels: in progress

#3684 Hide withdraw in golecli account if not mainnet
  golem/interface/cli.py
  tests/golem/interface/test_cli.py
Labels: in progress

#3702 Fix docker VM reconfiguration during startup
  golem/docker/hypervisor/hyperv.py
  golem/docker/manager.py
  golem/hardware/__init__.py
  golem/node.py
Labels: 0.19 release, bug, docker, in progress

#3626 Prepare new docker images
  apps/blender/blender_reference_generator.py
  apps/blender/blenderenvironment.py
  apps/blender/resources/__init__.py
  apps/blender/resources/images/blender.Dockerfile
  apps/blender/resources/images/scripts/blender_render.py
  apps/blender/resources/images/scripts/scenefileeditor.py
  apps/blender/resources/images/scripts/templates/blendercrop.py.template
  apps/blender/resources/scenefileeditor.py
  apps/blender/resources/scripts/docker_blendertask.py
  apps/blender/task/blenderrendertask.py
  apps/core/resources/images/base.Dockerfile
  apps/core/resources/images/scripts/entrypoint.sh
  apps/core/resources/images/scripts/install_py_libs.sh
  apps/dummy/dummyenvironment.py
  apps/images.ini
  apps/rendering/task/renderingtask.py
  golem/docker/job.py
  golem/docker/task_thread.py
  requirements.txt
  requirements_to-freeze.txt
  scripts/concent_acceptance_tests/additional_verification/base.py
  scripts/pyinstaller/hooks/hook-golem.py
  setup.py
  tests/apps/blender/resources/test_scenefileditor.py
  tests/apps/blender/task/test_blenderrendertask.py
  tests/apps/blender/verification/test_blender_reference_generator.py
  tests/apps/blender/verification/test_verificator_integration.py
  tests/golem/docker/docker-blender-cycles-task.json
  tests/golem/docker/docker-blender-render-task.json
  tests/golem/docker/docker-dummy-test-task.json
  tests/golem/docker/test_blender_job.py
  tests/golem/docker/test_docker_blender_task.py
  tests/golem/docker/test_docker_environment.py
  tests/golem/docker/test_docker_image.py
  tests/golem/docker/test_docker_job.py
  tests/golem/docker/test_docker_task_thread.py
  tests/golem/docker/test_dummy_job.py
  tests/golem/manager/test_nodestatesnapshot.py
  tests/golem/test_client.py
Labels: in progress, needs review

#3716 Bump golem-messages to 2.22.1
  requirements.txt
  requirements_to-freeze.txt
  tests/golem/task/test_tasksession.py
Labels: in progress

#3717 Remove unnecessary get_subtask_id from TaskThread
  golem/docker/task_thread.py
  golem/task/localcomputer.py
  golem/task/taskcomputer.py
  golem/task/taskthread.py
  tests/golem/docker/test_docker_task_thread.py
  tests/golem/task/test_taskcomputer.py
Labels: in progress

#3721 Bump golem-messages to 2.22.1
  requirements.txt
  requirements_to-freeze.txt
  tests/golem/task/test_tasksession.py
Labels: in progress

#3725 Fixed mounting error on Windows with Docker Toolbox
  golem/docker/manager.py
  golem/docker/task_thread.py
Labels: 0.19 release, bug, docker, needs review, windows

#3732 Partial payment
  scripts/concent_acceptance_tests/force_payment/test_payment.py
Labels: in progress

#3650 2526 force payment full node tests
  golem/network/concent/client.py
  golem/network/concent/received_handler.py
  golem/task/taskmanager.py
  golem/task/tasksession.py
  requirements-lint.txt
  requirements-test.txt
  requirements-test_to-freeze.txt
  scripts/node_integration_tests/helpers.py
  scripts/node_integration_tests/nodes/provider/day_backwards.py
  scripts/node_integration_tests/nodes/provider/debug.py
  scripts/node_integration_tests/nodes/requestor/day_backwards_dont_pay.py
  scripts/node_integration_tests/nodes/requestor/dont_pay.py
  scripts/node_integration_tests/nodes/requestor/reject_results.py
  scripts/node_integration_tests/playbooks/base.py
  scripts/node_integration_tests/playbooks/concent/additional_verification.py
  scripts/node_integration_tests/playbooks/concent/concent_base.py
  scripts/node_integration_tests/playbooks/concent/force_accept.py
  scripts/node_integration_tests/playbooks/concent/force_download.py
  scripts/node_integration_tests/playbooks/concent/force_payment.py
  scripts/node_integration_tests/playbooks/concent/force_report.py
  scripts/node_integration_tests/playbooks/golem/task_timeout.py
  scripts/node_integration_tests/run_test.py
  scripts/node_integration_tests/tests/test_concent.py
  tests/apps/blender/verification/test_blender_reference_generator.py
  tests/golem/docker/test_docker_job.py
  tests/golem/interface/test_cli.py
  tests/golem/network/concent/test_received_handler.py
Labels: _current, in progress

#3733 Wrong task header received: '<' not supported between instances of 'N…
  apps/core/task/coretask.py
Labels: in progress

#3724 Replayed forced payment
  scripts/concent_acceptance_tests/force_payment/test_payment.py
Labels: in progress

#3701 Cleanup and test version specifications
  apps/core/task/coretask.py
  golem/constants.py
  golem/network/p2p/peersession.py
  golem/task/taskkeeper.py
  golem/utils.py
  scripts/concent_acceptance_tests/basic/test_basic.py
  tests/golem/task/test_taskkeeper.py
  tests/golem/test_utils.py
Labels: in progress

#3727 Hide console during installation
  scripts/docker/create-share.ps1
  scripts/docker/prepare-docker-for-windows.ps1
Labels: in progress

#3737 * `pay.balance` + `contract_addresses` dictionary
  golem/client.py
  tests/golem/test_client.py
Labels: 0.19 release, brass, in progress

#3739 Added -NoProfile flag to powershell.exe
  golem/docker/hypervisor/hyperv.py
Labels: 0.19 release, in progress, needs review, windows

#3740 Information about Hyper-V in the installer
  Installer/Installer_Win/Golem.aip
Labels: 0.19 release, docker, needs review, windows

#3736 More hyperv events for electron
  golem/docker/hypervisor/hyperv.py
Labels: in progress

#2701 StatusPublisher: keep last status of all components
  golem/report.py
  golem/rpc/session.py
  golem/task/rpc.py
  tests/golem/test_client.py
Labels: 2, _current, in progress, needs review

#3735 B0.19 develop
  apps/core/task/coretask.py
  golem/docker/hypervisor/hyperv.py
  golem/docker/manager.py
  golem/docker/task_thread.py
  golem/hardware/__init__.py
  golem/network/concent/client.py
  golem/network/concent/received_handler.py
  golem/node.py
  golem/task/taskmanager.py
  golem/task/tasksession.py
  requirements-lint.txt
  requirements-test.txt
  requirements-test_to-freeze.txt
  scripts/node_integration_tests/helpers.py
  scripts/node_integration_tests/nodes/provider/day_backwards.py
  scripts/node_integration_tests/nodes/provider/debug.py
  scripts/node_integration_tests/nodes/requestor/day_backwards_dont_pay.py
  scripts/node_integration_tests/nodes/requestor/dont_pay.py
  scripts/node_integration_tests/nodes/requestor/reject_results.py
  scripts/node_integration_tests/playbooks/base.py
  scripts/node_integration_tests/playbooks/concent/additional_verification.py
  scripts/node_integration_tests/playbooks/concent/concent_base.py
  scripts/node_integration_tests/playbooks/concent/force_accept.py
  scripts/node_integration_tests/playbooks/concent/force_download.py
  scripts/node_integration_tests/playbooks/concent/force_payment.py
  scripts/node_integration_tests/playbooks/concent/force_report.py
  scripts/node_integration_tests/playbooks/golem/task_timeout.py
  scripts/node_integration_tests/run_test.py
  scripts/node_integration_tests/tests/test_concent.py
  tests/golem/interface/test_cli.py
  tests/golem/network/concent/test_received_handler.py
Labels: in progress

#3711 [Concent] UC5 Acceptance test: add test for the Provider requests ForcedPayment but requestor has already paid
  scripts/concent_acceptance_tests/base.py
  scripts/concent_acceptance_tests/force_payment/test_payment.py
Labels: in progress

#3738 store proper type in msg_date in network history
  golem/network/history.py
  tests/golem/network/test_history.py
Labels: in progress

#3183 Ability to set custom gas price during withdrawal
  golem/client.py
  golem/ethereum/transactionsystem.py
  golem/interface/client/account.py
  tests/golem/ethereum/test_transactionsystem.py
  tests/golem/test_client.py
Labels: in progress

#3681 Hyper-V RPC events
  golem/docker/hypervisor/__init__.py
  golem/docker/hypervisor/hyperv.py
  golem/node.py
  golem/report.py
Labels: 0.19 release, in progress, needs review

#3718 Feature fill wtct with task header
  golem/resource/resourcehandshake.py
  golem/task/tasksession.py
  requirements.txt
  requirements_to-freeze.txt
  tests/golem/core/test_keysauth.py
  tests/golem/network/concent/test_received_handler.py
  tests/golem/resource/test_resourcehandshake.py
  tests/golem/task/test_concent_logic.py
  tests/golem/task/test_taskarchiver.py
  tests/golem/task/test_taskmanager.py
  tests/golem/task/test_taskproviderstats.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#3741 Move jobpy to Docker images
  apps/blender/benchmark/benchmark.py
  apps/blender/blenderenvironment.py
  apps/blender/resources/images/scripts/job.py
  apps/blender/task/blenderrendertask.py
  apps/core/task/coretask.py
  apps/core/task/coretaskstate.py
  apps/dummy/benchmark/benchmark.py
  apps/dummy/dummyenvironment.py
  apps/dummy/resources/images/Dockerfile
  apps/dummy/resources/images/scripts/job.py
  apps/dummy/task/dummytask.py
  apps/images.ini
  golem/docker/environment.py
  golem/docker/job.py
  golem/docker/task_thread.py
  golem/environments/environment.py
  golem/resource/dirmanager.py
  golem/task/benchmarkmanager.py
  golem/task/localcomputer.py
  golem/task/taskbase.py
  golem/task/taskcomputer.py
  golem/task/tasksession.py
  golem/task/taskthread.py
  golem/verificator/blender_verifier.py
  golem/verificator/docker/blender/images/scripts/runner.py
  scripts/pyinstaller/hooks/hook-golem.py
  setup.py
  tests/apps/blender/benchmark/test_blenderbenchmark.py
  tests/apps/blender/task/test_blenderrendertask.py
  tests/apps/blender/test_blenderenvironment.py
  tests/apps/blender/verification/test_verificator_integration.py
  tests/apps/core/benchmark/test_benchmarkrunner.py
  tests/apps/core/task/test_coretask.py
  tests/apps/core/task/test_coretaskstate.py
  tests/apps/dummy/benchmark/test_dummybenchmark.py
  tests/apps/dummy/test_dummyenvironment.py
  tests/apps/rendering/task/test_renderingtask.py
  tests/golem/docker/docker-blender-cycles-task.json
  tests/golem/docker/docker-blender-render-task.json
  tests/golem/docker/docker-dummy-test-task.json
  tests/golem/docker/test_blender_job.py
  tests/golem/docker/test_docker_blender_task.py
  tests/golem/docker/test_docker_environment.py
  tests/golem/docker/test_docker_job.py
  tests/golem/docker/test_docker_manager.py
  tests/golem/docker/test_docker_task_thread.py
  tests/golem/docker/test_dummy_job.py
  tests/golem/environments/test_environment.py
  tests/golem/resource/test_dirmanager.py
  tests/golem/task/dummy/runner.py
  tests/golem/task/dummy/task.py
  tests/golem/task/test_localcomputer.py
  tests/golem/task/test_taskcomputer.py
  tests/golem/task/test_taskmanager.py
  tests/golem/task/test_tasksession.py
  tests/golem/task/test_tasktester.py
Labels: in progress

#3743 Buildbot: hyperg 0.2.9
  scripts/test-daemon-start.ps1
Labels: in progress

#3753 Buildbot: hyperg 0.2.9 (develop)
  scripts/test-daemon-start.ps1
Labels: in progress

#3467 Check for NoMoreSubtasks earlier
  golem/task/tasksession.py
Labels: in progress

#3703 Updated stats RPC with accepted/rejected subtasks
  golem/client.py
  golem/task/taskmanager.py
  golem/task/taskproviderstats.py
  golem/task/tasksession.py
  tests/golem/task/test_taskproviderstats.py
  tests/golem/task/test_tasksession.py
  tests/golem/test_client.py
Labels: in progress

#3754 TaskComputer has no counting_task
  golem/task/taskcomputer.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  tests/golem/task/test_taskcomputer.py
Labels: _current, brass, in progress

#3755 main_program_file cleanup
  golem/task/taskcomputer.py
  golem/task/tasktester.py
  scripts/concent_acceptance_tests/additional_verification/base.py
  tests/apps/core/task/test_coretask.py
  tests/apps/rendering/task/test_framerenderingtask.py
  tests/apps/rendering/task/test_renderingtask.py
Labels: in progress

#3759 Create Hyper-VM VM with minimum of memory
  golem/docker/hypervisor/hyperv.py
  tests/golem/docker/test_hyperv.py
Labels: 0.19 release, docker, in progress, windows

#3751 Created RPC call for checking VT/VT-x status
  golem/core/virtualization.py
  golem/core/windows.py
  golem/docker/hypervisor/hyperv.py
  golem/docker/smbshare.py
  golem/node.py
  golem/rpc/session.py
  requirements.txt
  requirements_to-freeze.txt
  scripts/virtualization/get-virtualization-state.ps1
  tests/golem/core/test_virtualization.py
Labels: in progress

#3700 argv-like invocation in entrypoint.sh
  apps/blender/blenderenvironment.py
  apps/blender/resources/images/blender.Dockerfile
  apps/blender/resources/images/blender_nvgpu.Dockerfile
  apps/core/resources/images/base.Dockerfile
  apps/dummy/dummyenvironment.py
  apps/dummy/resources/images/Dockerfile
  apps/entrypoint.sh
  apps/images.ini
  apps/rendering/resources/images/Dockerfile
  apps/rendering/resources/images/requirements.txt
  golem/docker/job.py
  golem/verificator/blender_verifier.py
  scripts/pyinstaller/hooks/hook-golem.py
  setup.py
  tests/apps/blender/verification/test_verificator_integration.py
  tests/golem/docker/docker-blender-cycles-task.json
  tests/golem/docker/docker-blender-render-task.json
  tests/golem/docker/docker-dummy-test-task.json
  tests/golem/docker/test_blender_job.py
  tests/golem/docker/test_docker_blender_task.py
  tests/golem/docker/test_docker_environment.py
  tests/golem/docker/test_docker_image.py
  tests/golem/docker/test_docker_job.py
  tests/golem/docker/test_docker_task_thread.py
  tests/golem/docker/test_dummy_job.py
Labels: clay, in progress

#3761 Use new but pretty much the same tETH faucet
  golem/ethereum/faucet.py
  golem/ethereum/transactionsystem.py
  tests/golem/ethereum/test_faucet.py
  tests/golem/ethereum/test_transactionsystem.py
Labels: in progress

#3766 b0.19
  golem/ethereum/faucet.py
  golem/ethereum/transactionsystem.py
  tests/golem/ethereum/test_faucet.py
  tests/golem/ethereum/test_transactionsystem.py
Labels: in progress

#3765 Remove unused create_reference_data_for_task_validation
  golem/task/taskbase.py
  golem/task/taskmanager.py
  tests/golem/docker/test_docker_dummy_task.py
Labels: in progress

#3771 Docker argv: execute 'python3' instead of '/usr/bin/python3' in DockerJob
  golem/docker/job.py
Labels: in progress

#3769 Remove get_task_env
  golem/task/taskkeeper.py
  golem/task/tasksession.py
  tests/golem/task/test_taskkeeper.py
Labels: in progress

#3770 Node._stop_on_error: print error message
  golem/node.py
  tests/golem/test_opt_node.py
Labels: 0.19 release, brass, in progress

#3767 Initial Concent soft switch status is off
  golem/network/concent/soft_switch.py
  tests/golem/network/concent/test_soft_switch.py
Labels: _current, concent, in progress

#3750 Don't ask for gntdeposit function when deposit address is unknown
  golem/client.py
  golem/core/variables.py
  golem/ethereum/exceptions.py
  golem/ethereum/transactionsystem.py
  tests/golem/ethereum/test_transactionsystem.py
  tests/golem/test_client.py
Labels: in progress

#3776 Fix geth address argument
  golem/client.py
  golem/node.py
  tests/golem/test_opt_node.py
Labels: in progress

#3778 Hyper-V process detection on Windows
  golem/core/virtualization.py
  scripts/virtualization/get-virtualization-state.ps1
  tests/golem/core/test_virtualization.py
Labels: in progress

#3782 Included virtualization check script in binaries
  scripts/pyinstaller/hooks/hook-golem.py
Labels: in progress

#3775 Remove unused method from coretask
  apps/blender/task/blenderrendertask.py
  apps/core/task/coretask.py
  tests/apps/blender/task/test_blenderrendertask.py
  tests/apps/core/task/test_coretask.py
Labels: in progress

#3784 Remove KeysAuth from BaseResourcesServer
  golem/client.py
  golem/resource/base/resourceserver.py
  tests/golem/resource/base/common.py
  tests/golem/resource/base/test_base_resourceserver.py
Labels: in progress

#3789 Remove unused TaskDefaults from TaskTypeInfo
  apps/blender/task/blenderrendertask.py
  apps/core/task/coretask.py
  apps/dummy/task/dummytask.py
  golem/task/taskbase.py
  tests/apps/core/task/test_coretask.py
  tests/apps/dummy/task/test_dummytask.py
  tests/apps/rendering/task/test_renderingtask.py
  tests/golem/task/test_taskmanager.py
Labels: in progress

#3787 Remove unpack_delta
  golem/client.py
  golem/resource/base/resourceserver.py
  golem/task/taskcomputer.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  tests/golem/docker/test_docker_task.py
  tests/golem/task/test_taskcomputer.py
Labels: in progress

#3802 Substract gas cost from ETH withdrawal
  golem/ethereum/transactionsystem.py
  tests/golem/ethereum/test_transactionsystem.py
Labels: in progress

#3803 Update to boot2docker v18.09.1
  golem/docker/hypervisor/hyperv.py
Labels: docker, in progress, windows

#3808 B0.19 develop
  golem/client.py
  golem/core/variables.py
  golem/core/virtualization.py
  golem/core/windows.py
  golem/ethereum/exceptions.py
  golem/ethereum/transactionsystem.py
  golem/network/concent/soft_switch.py
  golem/network/p2p/p2pservice.py
  golem/network/transport/tcpnetwork.py
  golem/node.py
  golem/task/taskserver.py
  requirements.txt
  requirements_to-freeze.txt
  scripts/concent_acceptance_tests/base.py
  scripts/concent_acceptance_tests/basic/test_basic.py
  scripts/concent_acceptance_tests/force_accept/test_requestor_doesnt_send.py
  scripts/concent_acceptance_tests/force_download/test_filetransfers.py
  scripts/pyinstaller/hooks/hook-golem.py
  scripts/virtualization/get-virtualization-state.ps1
  tests/golem/core/test_virtualization.py
  tests/golem/ethereum/test_transactionsystem.py
  tests/golem/network/concent/test_soft_switch.py
  tests/golem/task/dummy/task.py
  tests/golem/task/test_taskserver.py
  tests/golem/test_client.py
  tests/golem/test_opt_node.py
Labels: in progress

#3801 RPC for estimated Concent deposit payment and tx fee
  golem/client.py
  golem/core/common.py
  golem/ethereum/transactionsystem.py
  golem/task/rpc.py
  golem/task/taskkeeper.py
  golem/task/taskmanager.py
  tests/golem/task/test_rpc.py
  tests/golem/task/test_taskmanager.py
  tests/golem/test_client.py
Labels: in progress

#3812 additional debug logs for `Tasks` message exchange et al
  golem/network/p2p/peersession.py
  golem/network/transport/tcpserver.py
  golem/task/taskkeeper.py
Labels: in progress

#3805 Minimum Windows 10 version 1709
  Installer/Installer_Win/Golem.aip
Labels: in progress, windows

#3742 Linux installer: install the correct version of Docker for nvidia-docker2
  Installer/Installer_Linux/install.sh
Labels: in progress, needs review

#3816 fix `subtasks` parameter in the `test_jpg` integration test
  apps/core/task/coretask.py
  scripts/node_integration_tests/tasks/__init__.py
Labels: in progress

#3811 B0.19
  Installer/Installer_Win/Golem.aip
  apps/core/task/coretask.py
  golem/client.py
  golem/core/common.py
  golem/ethereum/transactionsystem.py
  golem/network/p2p/peersession.py
  golem/network/transport/tcpserver.py
  golem/task/rpc.py
  golem/task/taskkeeper.py
  golem/task/taskmanager.py
  scripts/concent_acceptance_tests/base.py
  scripts/node_integration_tests/tasks/__init__.py
  tests/golem/task/test_rpc.py
  tests/golem/task/test_taskmanager.py
  tests/golem/test_client.py
Labels: in progress

#3819 Don't broadcast peers with invalid address information
  golem/network/p2p/p2pservice.py
  golem/network/p2p/peersession.py
  tests/golem/network/p2p/test_p2pservice.py
Labels: in progress

#3823 B0.19
  golem/network/p2p/p2pservice.py
  golem/network/p2p/peersession.py
  requirements.txt
  requirements_to-freeze.txt
  tests/golem/network/p2p/test_p2pservice.py
Labels: in progress

#3822 fix kwargs
  scripts/concent_acceptance_tests/force_payment/test_payment.py
Labels: in progress

#3824 Just check for waiting in TaskServer
  golem/task/taskserver.py
  tests/golem/task/test_taskserver.py
Labels: in progress

#3826 Hyper-V memory fixes
  golem/docker/hypervisor/hyperv.py
  golem/hardware/presets.py
  tests/golem/docker/test_hyperv.py
  tests/golem/hardware/test_presets.py
Labels: 0.19 release, bug, important, in progress, needs review

#3781 Move the verificator Dockerfile and scripts to apps
  apps/rendering/resources/images/Dockerfile
  apps/rendering/resources/images/requirements.txt
  apps/rendering/resources/scripts/decision_tree.py
  apps/rendering/resources/scripts/img_format_converter.py
  apps/rendering/resources/scripts/img_metrics_calculator.py
  apps/rendering/resources/scripts/imgmetrics.py
  apps/rendering/resources/scripts/metrics/__init__.py
  apps/rendering/resources/scripts/metrics/edges.py
  apps/rendering/resources/scripts/metrics/histograms_correlation.py
  apps/rendering/resources/scripts/metrics/mass_center_distance.py
  apps/rendering/resources/scripts/metrics/psnr.py
  apps/rendering/resources/scripts/metrics/ssim.py
  apps/rendering/resources/scripts/metrics/variance.py
  apps/rendering/resources/scripts/metrics/wavelet.py
  apps/rendering/resources/scripts/runner.py
  apps/rendering/resources/scripts/tree35_[crr=87.71][frr=0.92].pkl
  golem/verificator/docker/__init__.py
  golem/verificator/docker/blender/images/Dockerfile
  golem/verificator/docker/blender/images/entrypoint.sh
  golem/verificator/docker/blender/images/requirements.txt
  golem/verificator/docker/blender/images/scripts/__init__.py
  golem/verificator/docker/blender/images/scripts/img_format_converter.py
  golem/verificator/docker/blender/images/scripts/img_metrics_calculator.py
  golem/verificator/docker/blender/images/scripts/imgmetrics.py
  golem/verificator/docker/blender/images/scripts/metrics/__init__.py
  golem/verificator/docker/blender/images/scripts/metrics/edges.py
  golem/verificator/docker/blender/images/scripts/metrics/psnr.py
  golem/verificator/docker/blender/images/scripts/metrics/ssim.py
  golem/verificator/docker/blender/images/scripts/metrics/variance.py
  golem/verificator/docker/blender/images/scripts/metrics/wavelet.py
  golem/verificator/docker/blender/images/scripts/runner.py
Labels: in progress

#3825 Fix force payment acceptance tests
  scripts/concent_acceptance_tests/force_payment/test_payment.py
Labels: in progress

#3821 + add a description of the `TaskTimeoutAndRestart` integration test p…
  scripts/node_integration_tests/playbooks/golem/task_timeout.py
Labels: in progress

#3827 Silence `appconfig` warnings for properties otherwise known but saved…
  golem/appconfig.py
Labels: in progress

#3828 fix retry_until_timeout() for batch transfers
  scripts/concent_acceptance_tests/force_payment/test_payment.py
Labels: in progress

#3834 Extend Hyper-V VM start timeout to 120s
  golem/docker/hypervisor/hyperv.py
Labels: 0.19 release, in progress

#3835 Add handling of `ForceSubtaskResultsRejected` to force_accept node test
  scripts/node_integration_tests/playbooks/concent/force_accept.py
Labels: in progress

#3836 fix detection of the `AckReportComputedTask` message in the Concent's…
  scripts/node_integration_tests/playbooks/concent/force_report.py
Labels: in progress

#3837 Additional task debug logs
  apps/core/task/coretask.py
  golem/ranking/manager/database_manager.py
  golem/task/rpc.py
  golem/task/taskmanager.py
  golem/task/taskstate.py
Labels: in progress
