Repository golemfactory/golem, pull requests merged in 2019-05, with the labels that each got.

#4149 Previous code for computing output path in ffmpeg task
  apps/transcoding/task.py
  tests/apps/ffmpeg/task/test_ffmpegtask.py
Labels: in progress

#4133 New subtask status "Cancelled"
  apps/blender/task/blenderrendertask.py
  apps/core/task/coretask.py
  apps/rendering/task/framerenderingtask.py
  golem/task/rpc.py
  golem/task/taskmanager.py
  golem/task/taskrequestorstats.py
  golem/task/tasksession.py
  golem/task/taskstate.py
  tests/apps/blender/task/test_blenderrendertask.py
  tests/apps/rendering/task/test_framerenderingtask.py
  tests/factories/task/taskstate.py
  tests/golem/task/test_concent_logic.py
  tests/golem/task/test_rpc.py
  tests/golem/task/test_taskmanager.py
  tests/golem/task/test_taskrequestorstats.py
  tests/golem/task/test_tasksession.py
  tests/golem/task/test_taskstate.py
Labels: in progress

#4155 Added graceful shutdown status to status publisher
  golem/client.py
  golem/node.py
Labels: in progress

#4156 Fix TestClient::test_restore_locks
  golem/client.py
  tests/golem/task/test_rpc.py
  tests/golem/test_client.py
Labels: in progress

#4147 Make incomes and payments CLI calls print short-id by default
  golem/interface/client/payments.py
  tests/golem/interface/test_client_commands.py
Labels: cli, in progress

#4104 Fix race condition in taskmanager
  golem/task/taskmanager.py
Labels: in progress

#4150 Moved responsibility for web3 retry to the ProxyProvider
  golem/ethereum/node.py
  golem/ethereum/web3/middleware.py
  golem/ethereum/web3/providers.py
  tests/golem/ethereum/test_ethereum_node.py
  tests/golem/ethereum/web3/test_middleware.py
  tests/golem/ethereum/web3/test_providers.py
Labels: in progress

#4152 Brass Marketplace paper linked in docs + naming fix for thirst
  golem/ranking/__init__.py
  golem/ranking/manager/database_manager.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  golem/task/timer.py
  lintdiff.sh
  rust/golem/src/marketplace.rs
  tests/golem/task/test_timer.py
Labels: in progress

#4160 Cargo.lock with comment for rust on BB upgraded
  lint.sh
  rust/golem/Cargo.lock
Labels: in progress

#4058 Multinode integration tests
  requirements-test.txt
  requirements-test_to-freeze.txt
  scripts/node_integration_tests/README.md
  scripts/node_integration_tests/playbook_loader.py
  scripts/node_integration_tests/playbooks/base.py
  scripts/node_integration_tests/playbooks/concent/additional_verification/playbook.py
  scripts/node_integration_tests/playbooks/concent/additional_verification/test_config.py
  scripts/node_integration_tests/playbooks/concent/concent_base.py
  scripts/node_integration_tests/playbooks/concent/force_accept/playbook.py
  scripts/node_integration_tests/playbooks/concent/force_accept/test_config.py
  scripts/node_integration_tests/playbooks/concent/force_download/playbook.py
  scripts/node_integration_tests/playbooks/concent/force_download/test_config.py
  scripts/node_integration_tests/playbooks/concent/force_payment/playbook.py
  scripts/node_integration_tests/playbooks/concent/force_payment/test_config.py
  scripts/node_integration_tests/playbooks/concent/force_report/playbook.py
  scripts/node_integration_tests/playbooks/concent/force_report/test_config.py
  scripts/node_integration_tests/playbooks/golem/multinode_regular_run/__init__.py
  scripts/node_integration_tests/playbooks/golem/multinode_regular_run/playbook.py
  scripts/node_integration_tests/playbooks/golem/multinode_regular_run/test_config.py
  scripts/node_integration_tests/playbooks/golem/no_concent.py
  scripts/node_integration_tests/playbooks/golem/regular_run_stop_on_reject/playbook.py
  scripts/node_integration_tests/playbooks/golem/restart_frame/playbook.py
  scripts/node_integration_tests/playbooks/golem/restart_frame/test_config.py
  scripts/node_integration_tests/playbooks/golem/rpc_test/mainnet/test_config.py
  scripts/node_integration_tests/playbooks/golem/rpc_test/no_concent/playbook.py
  scripts/node_integration_tests/playbooks/golem/rpc_test/no_concent/test_config.py
  scripts/node_integration_tests/playbooks/golem/rpc_test/playbook.py
  scripts/node_integration_tests/playbooks/golem/task_output/playbook.py
  scripts/node_integration_tests/playbooks/golem/task_timeout/playbook.py
  scripts/node_integration_tests/playbooks/golem/task_timeout/test_config.py
  scripts/node_integration_tests/playbooks/golem/zero_price.py
  scripts/node_integration_tests/playbooks/test_config_base.py
  scripts/node_integration_tests/run_nodes.py
  scripts/node_integration_tests/run_test.py
  scripts/node_integration_tests/tests/base.py
Labels: in progress

#4140 Docker input & output
  golem/docker/hypervisor/dummy.py
  golem/envs/__init__.py
  golem/envs/docker/cpu.py
  tests/golem/envs/docker/cpu/test_input.py
  tests/golem/envs/docker/cpu/test_input_socket.py
  tests/golem/envs/docker/cpu/test_integration.py
  tests/golem/envs/docker/cpu/test_output.py
  tests/golem/envs/docker/cpu/test_runtime.py
Labels: clay, in progress, needs review

#4163 Integration tests minor stuff
  scripts/node_integration_tests/conftest.py
  scripts/node_integration_tests/helpers.py
  scripts/node_integration_tests/playbooks/__init__.py
  scripts/node_integration_tests/playbooks/base.py
  scripts/node_integration_tests/playbooks/concent/concent_base.py
  scripts/node_integration_tests/playbooks/concent/force_accept/playbook.py
  scripts/node_integration_tests/playbooks/concent/force_payment/test_config.py
  scripts/node_integration_tests/playbooks/golem/multinode_regular_run/test_config.py
  scripts/node_integration_tests/playbooks/golem/restart_frame/test_config.py
  scripts/node_integration_tests/playbooks/golem/task_timeout/test_config.py
  scripts/node_integration_tests/playbooks/test_config_base.py
  scripts/node_integration_tests/tasks/__init__.py
  scripts/node_integration_tests/tests/base.py
  scripts/node_integration_tests/tests/test_concent.py
  scripts/node_integration_tests/tests/test_golem.py
Labels: in progress

#4167 Remove unused argument from BaseResourceServer
  golem/client.py
  golem/resource/base/resourceserver.py
  tests/golem/resource/base/common.py
  tests/golem/resource/base/test_base_resourceserver.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#3978 Add GLambda app
  Installer/Installer_Linux/install.sh
  apps/glambda/benchmark/benchmark.py
  apps/glambda/glambdaenvironment.py
  apps/glambda/resources/images/Dockerfile
  apps/glambda/resources/scripts/job.py
  apps/glambda/task/glambdatask.py
  apps/images.ini
  apps/registered_test.ini
  golem/client.py
  golem/config/environments/testnet.py
  golem/environments/environment.py
  golem/node.py
  golem/rpc/router.py
  golem/task/result/resultpackage.py
  golem/task/taskbase.py
  golem/task/taskmanager.py
  golem/task/taskstate.py
  golem/tools/remotefs.py
  golem/tools/uploadcontroller.py
  golem/verificator/verifier.py
  requirements.txt
  tests/apps/glambda/test_glambda_benchmark.py
  tests/apps/glambda/test_job.py
  tests/apps/glambda/test_task.py
  tests/golem/docker/test_docker_manager.py
  tests/golem/task/test_taskmanager.py
Labels: in progress

#4158 thrist introduced to improve readability
  golem/task/timer.py
Labels: in progress

#4175 [golemcli] tasks subtasks ETA removed
  golem/interface/client/tasks.py
  tests/golem/interface/test_client_commands.py
Labels: in progress

#4178 Green control_test for b0.19
  lint.sh
  rust/golem/Cargo.lock
  scripts/test-daemon-start.sh
  scripts/test-daemon-stop.sh
  tests/golem/docker/test_docker_dummy_task.py
  tests/golem/rpc/test_router.py
Labels: in progress

#4159 0.19 Task computer "stuck" on subtask
  golem/task/taskcomputer.py
  golem/task/taskkeeper.py
  tests/golem/task/test_taskkeeper.py
Labels: in progress

#4176 Improved crop file detection in Blender verifier
  apps/blender/resources/images/entrypoints/scripts/verifier_tools/file_extension/__init__.py
  apps/blender/resources/images/entrypoints/scripts/verifier_tools/file_extension/matcher.py
  apps/blender/resources/images/entrypoints/scripts/verifier_tools/file_extension/types.py
  apps/blender/resources/images/entrypoints/scripts/verifier_tools/verificator.py
  tests/apps/blender/verification/test_extension_matcher.py
Labels: in progress

#4181 Fix 'TaskComputer' object has no attribute 'session_closed'
  golem/resource/resourcehandshake.py
  tests/golem/resource/test_resourcehandshake.py
Labels: in progress

#4186 Remove usage of Hello.client_key_id
  golem/network/p2p/peersession.py
  golem/task/tasksession.py
  tests/golem/network/p2p/test_peersession.py
  tests/golem/task/test_tasksession.py
Labels: in progress

#4187 Bump blender_verifier version to 1.2
  apps/images.ini
  golem/verificator/blender_verifier.py
  scripts/node_integration_tests/tests/test_golem.py
Labels: in progress

#4183 Eliminate hanging processes left after `rpc/test_router.py` tests
  golem/core/processmonitor.py
  golem/tools/testchildprocesses.py
  golem/tools/testwithreactor.py
  tests/golem/resource/test_resourcehandshake.py
  tests/golem/rpc/test_router.py
Labels: in progress

#4196 Fixes potential overwriting bug in WasmTask
  apps/wasm/task.py
Labels: in progress

#4198 adv inst update
  Installer/Installer_Win/Golem.aip
Labels: in progress

#4169 Transaction history update
  golem/client.py
  golem/ethereum/incomeskeeper.py
  golem/ethereum/paymentprocessor.py
  golem/ethereum/paymentskeeper.py
  golem/ethereum/transactionsystem.py
  golem/interface/client/payments.py
  golem/model.py
  tests/factories/model.py
  tests/golem/ethereum/test_incomeskeeper.py
  tests/golem/ethereum/test_paymentprocessor.py
  tests/golem/ethereum/test_transactionsystem.py
  tests/golem/interface/test_client_commands.py
  tests/golem/test_client.py
  tests/golem/test_model.py
Labels: in progress

#4190 A non-flaky unit test for TaskServer.test_send_results()
  golem/task/taskserver.py
  tests/golem/docker/test_docker_task.py
  tests/golem/task/test_taskserver.py
Labels: bug, ci & tests, needs review

#4195 New unit tests for MemoryChecker
  tests/golem/vm/test_memorychecker.py
Labels: bug, ci & tests, in progress, needs review

#4200 fix: clean-docker-vm assumes Docker Toolbox is installed
  Installer/Installer_Win/Golem.aip
  scripts/docker/clean-docker-vm.ps1
Labels: in progress

#4203 Verifier cleanup/docker image fixes after review
  apps/blender/resources/images/entrypoints/scripts/verifier_tools/crop_generator.py
  apps/blender/resources/images/entrypoints/scripts/verifier_tools/image_metrics.py
  apps/blender/resources/images/entrypoints/scripts/verifier_tools/image_metrics_calculator.py
  apps/blender/resources/images/entrypoints/scripts/verifier_tools/skimage.py
  apps/blender/resources/images/entrypoints/scripts/verifier_tools/verifier.py
  apps/blender/resources/images/entrypoints/verifier_entrypoint.py
  tests/golem/verifier/test_blenderverifier.py
  tests/golem/verifier/test_utils/helpers.py
Labels: in progress

#4202 Specify gVisor secure runtime version
  Installer/Installer_Linux/install.sh
Labels: in progress

#4206 Cgi/transcoding/ffmpeg tools
  apps/core/resources/images/scripts/install_py_libs.sh
  apps/images.ini
  apps/transcoding/common.py
  apps/transcoding/ffmpeg/benchmark/benchmark.py
  apps/transcoding/ffmpeg/environment.py
  apps/transcoding/ffmpeg/resources/ffmpeg-scripts/ffmpeg_commands.py
  apps/transcoding/ffmpeg/resources/ffmpeg-scripts/ffmpeg_task.py
  apps/transcoding/ffmpeg/resources/ffmpeg-scripts/requirements.txt
  apps/transcoding/ffmpeg/resources/images/ffmpeg.Dockerfile
  apps/transcoding/ffmpeg/task.py
  apps/transcoding/ffmpeg/utils.py
  apps/transcoding/task.py
  requirements.txt
  tests/apps/ffmpeg/task/test_ffmpegintegration.py
  tests/apps/ffmpeg/task/test_ffmpegtask.py
  tests/apps/ffmpeg/task/test_fmmpegtranscoding.py
Labels: in progress

#4205 Always override docker-machine.exe and docker.exe on upgrade
  Installer/Installer_Win/Golem.aip
Labels: in progress

#4210 update Concent Service certificates
  golem/network/concent/resources/ssl/certs/staging.crt
  golem/network/concent/resources/ssl/certs/test.crt
Labels: brass, concent

#4185 Environment events & runtime events
  golem/envs/__init__.py
  golem/envs/docker/cpu.py
  tests/golem/envs/docker/cpu/test_env.py
  tests/golem/envs/docker/cpu/test_integration.py
  tests/golem/envs/docker/cpu/test_runtime.py
  tests/golem/envs/test_env.py
  tests/golem/envs/test_runtime.py
Labels: clay, in progress, needs review

#4218 Environment refactoring cleanup
  golem/envs/__init__.py
  golem/envs/docker/cpu.py
  tests/golem/envs/docker/cpu/test_env.py
  tests/golem/envs/docker/cpu/test_integration.py
  tests/golem/envs/docker/cpu/test_runtime.py
Labels: clay

#4226 node_integration_tests - Added failure after 100 tries on the same step
  scripts/node_integration_tests/playbooks/base.py
Labels: ci & tests

#4130 Fix ffmpeg.task._get_extra_data() truncating chunk names at the first dot
  apps/transcoding/ffmpeg/task.py
  tests/apps/ffmpeg/task/test_ffmpegtask.py
Labels: in progress

#4227 node_integration_tests - Make step_verify_income retry like all others.
  scripts/node_integration_tests/playbooks/base.py
Labels: ci & tests

#4129 Epic: Computational environments refactoring
  golem/core/simpleserializer.py
  golem/database/database.py
  golem/database/schemas/026_create_docker_whitelist.py
  golem/docker/commands/docker.py
  golem/docker/hypervisor/__init__.py
  golem/docker/hypervisor/docker_machine.py
  golem/docker/hypervisor/dummy.py
  golem/docker/hypervisor/hyperv.py
  golem/docker/hypervisor/virtualbox.py
  golem/docker/hypervisor/xhyve.py
  golem/docker/manager.py
  golem/envs/__init__.py
  golem/envs/docker/__init__.py
  golem/envs/docker/cpu.py
  golem/envs/docker/whitelist.py
  golem/envs/manager.py
  golem/model.py
  requirements-lint.txt
  requirements-test.txt
  requirements-test_to-freeze.txt
  tests/golem/docker/test_docker_manager.py
  tests/golem/docker/test_hypervisor.py
  tests/golem/envs/__init__.py
  tests/golem/envs/docker/__init__.py
  tests/golem/envs/docker/cpu/__init__.py
  tests/golem/envs/docker/cpu/test_config.py
  tests/golem/envs/docker/cpu/test_env.py
  tests/golem/envs/docker/cpu/test_input.py
  tests/golem/envs/docker/cpu/test_input_socket.py
  tests/golem/envs/docker/cpu/test_integration.py
  tests/golem/envs/docker/cpu/test_output.py
  tests/golem/envs/docker/cpu/test_runtime.py
  tests/golem/envs/docker/test_payload.py
  tests/golem/envs/docker/test_prerequisites.py
  tests/golem/envs/docker/test_whitelist.py
  tests/golem/envs/test_env.py
  tests/golem/envs/test_manager.py
  tests/golem/envs/test_runtime.py
Labels: clay, in progress

#4131 Fix some of the warnings from CGI/transcoding/master branch
  apps/transcoding/common.py
  apps/transcoding/ffmpeg/resources/ffmpeg-scripts/ffmpeg_task.py
  apps/transcoding/ffmpeg/resources/images/ffmpeg.Dockerfile
  apps/transcoding/ffmpeg/task.py
  apps/transcoding/ffmpeg/utils.py
  apps/transcoding/task.py
  tests/apps/ffmpeg/task/test_ffmpegtask.py
  tests/apps/ffmpeg/task/test_fmmpegtranscoding.py
Labels: in progress

#4228 node_integration_tests - Add 30 seconds of sleep after requesting tETH or tGNT
  scripts/node_integration_tests/playbooks/base.py
Labels: ci & tests

#4219 node_integration_tests - Fix timeout test on buildbot
  scripts/node_integration_tests/playbooks/golem/task_timeout/playbook.py
  scripts/node_integration_tests/tasks/__init__.py
Labels: ci & tests

#4239 Misc log improvements
  golem/network/transport/tcpnetwork.py
  golem/rpc/session.py
  golem/tools/talkback.py
Labels: cleanup

#4236 Wamp serialization error fix: huge unsigned int
  golem/rpc/utils.py
  golem/task/rpc.py
Labels: _current, brass

#4134 Update urllib3 to 1.24.3
  requirements-lint.txt
  requirements-lint_to-freeze.txt
  requirements-test.txt
  requirements-test_to-freeze.txt
  requirements.txt
  requirements_to-freeze.txt
Labels: in progress

#4241 Fix race condition in taskkeeper test
  tests/golem/task/test_taskkeeper.py
Labels: ci & tests

#4004 per task disable or lenient verification
  apps/core/task/coretask.py
  apps/core/task/coretaskstate.py
  golem/appconfig.py
  golem/client.py
  golem/clientconfigdescriptor.py
  golem/core/simpleserializer.py
  golem/core/variables.py
  golem/task/server/verification.py
  golem/task/taskserver.py
  requirements.txt
  requirements_to-freeze.txt
  scripts/node_integration_tests/playbooks/base.py
  scripts/node_integration_tests/playbooks/golem/disabled_verification.py
  scripts/node_integration_tests/playbooks/golem/fake_result.png
  scripts/node_integration_tests/playbooks/golem/lenient_verification/__init__.py
  scripts/node_integration_tests/playbooks/golem/lenient_verification/playbook.py
  scripts/node_integration_tests/playbooks/golem/lenient_verification/test_config.py
  scripts/node_integration_tests/playbooks/golem/multinode_regular_run/playbook.py
  tests/golem/core/test_simpleserializer.py
  tests/golem/docker/docker-blender-cycles-task.json
  tests/golem/docker/docker-blender-render-task.json
  tests/golem/docker/docker-dummy-test-task.json
Labels: _current, in progress

#4194 Bump GM to 3.5
  golem/network/p2p/peersession.py
  golem/task/server/helpers.py
  golem/task/taskmanager.py
  golem/task/taskserver.py
  golem/task/tasksession.py
  requirements.txt
  requirements_to-freeze.txt
  tests/golem/core/test_keysauth.py
  tests/golem/network/p2p/test_peersession.py
  tests/golem/task/server/test_helpers.py
  tests/golem/task/test_taskmanager.py
  tests/golem/task/test_taskserver.py
  tests/golem/task/test_tasksession.py
Labels: in progress
